### ISSUE TITLE
Make zip.js an AMD module

### ISSUE THREAD

**Issue by Yoric** [gildas-lormeau/zip.js#102]
I am currently using zip.js in [an application](https://github.com/Yoric/lector) that is otherwise based on [AMD](https://en.wikipedia.org/wiki/Asynchronous_module_definition). It would be a bit cleaner (and possibly better on startup lag) if zip.js could be used directly as an AMD.

There is an example on how to do this [here](https://github.com/umdjs/umd).

**Comment by Noitidart** [comment]
I was trying to use zip.js in firefox addon. Actually to replace the nsIZipWriter and nsIZipReader so I can do things async and replace nsIFile with OS.File. As the user I'm collaborating with does not want to go to OS.File because zipping is sync: https://github.com/diegocr/GitHubExtIns/pull/10

When I came to issues page it was a nice surprise to see a fellow firefox guy! Do you have a version I can plop into my firefox addon?

**Comment by Rob--W** [comment]
Hi there @Noitidart! The addon SDK expects modules in the CommonJS format, while the repo that you linked doesn't appear to be using that kind of module. It seems that you're actually looking for a JSM, right?

If so, I guess that something like the following will do:

```js
// Let's call this file zip.js/zip.js
const EXPORTED_SYMBOLS = ['zip'];
// zip.js content here
```

```js
// Main code
Cu.import('resource://my-addon/zip.js/zip.js');
// Here, you can use the zip object.
```

**Comment by Noitidart** [comment]
Hey Rob! :) Thank yo uvery much for that I'll test that out! :)

**Comment by Noitidart** [comment]
Hey @Rob--W I got got this set up here: 

But I get this error:
```
"onerror callback, error:" error { target: Worker, isTrusted: true, message: "Error: Failed to load script (nsresult = 0x805303f4)", filename: "", lineno: 0, colno: 0, currentTarget: Worker, eventPhase: 2, bubbles: true, cancelable: true, defaultPrevented: false } bootstrap.js:215
Error: Failed to load script (nsresult = 0x805303f4)
```

Do you know what could be causing that?

To replicate please install the addon from here: https://github.com/Noitidart/AysncZip

Then click the icon that gets added to the toolbar and then type a url of a zip file. Then please pick "Decompressed". Then select folder destination, and then a subfolder if you would like to make one, then you will see the error in the browser console.

I'm just writing this as a demo/template addon so I can use it in other works and show others how to use it from firefox addons.

Thanks!

**Comment by Rob--W** [comment]
@Noitidart I will take a look at your issue later.

Why do you want to use zip.js instead of the built-in zip reader in a Firefox addon, by the way? I reckon that the built-in zip reader can be implemented much more efficiently than zip.js, and it is less likely to contain bugs since it has been around much longer. See https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIZipReader

**Comment by Noitidart** [comment]
Thanks @Rob--W for such a fast reply! Main reason is because zip.js is async. Which I thought would give it a one up on perf. But do you think nsIZipReader/Writer would be better for perf?

**Comment by Noitidart** [comment]
Blogged about why I decided to go with zip.js in ff-addons here: https://github.com/Noitidart/AysncZip/wiki/AsyncZip

**Comment by Rob--W** [comment]
@Noitidart Lack of async sounds like a great reason to prefer a non-synchronous API such as zip.js

It seems that you've already been experimenting with nsIZipReader (https://codereview.stackexchange.com/questions/56821/improvements-to-nsizipreader-and-nsiscriptableinputstream and https://stackoverflow.com/questions/24344470/learning-nsizipwriter-and-nsizipreader).

I spend an hour on looking through the documentation and source code, then created a seemingly working asynchronous zip reading example using nsIZipReader, see my answer to your question at https://stackoverflow.com/a/30099862/938089.

Let me know if you still want me to look in why zip.js doesn't work in a Firefox addon.

**Comment by Noitidart** [comment]
@Rob--W wow thank you so much for your effort!! This is very interesting!

If you have time in the future not now you already spent a ton! That would be awesome I'll also be revisiting zip.js to see what's up with it as I think I'm real close. Reason is than it will be off-mainthread. I'm also debating stripping apart zip.js sometime and change to be OS.File based so it can be used easily from ChromeWorker's :P

**Comment by Noitidart** [comment]
Hey Rob I was trying to use this to open a crx file. I used the sync api and it failed apparently nsIZipReader cant read crx files (google chrome extension files), do you know the deal with it?

I also tried to use this, and it seems firefox got rid of FileReader from workers and now only offer FileReaderSync. Should we submit patch to this?

**Comment by Noitidart** [comment]
Aww absolute bogus there is some extra crap in the header, and the utility is mia:

Section titled "How To Convert a CRX File to a ZIP file:" here: http://www.lyraphase.com/wp/projects/software/about-crx-files/

**Comment by Noitidart** [comment]
Ah heres the info on the header: https://developer.chrome.com/extensions/crx

Working on trying to strip it righ tnow

**Comment by Rob--W** [comment]
@Noitidart I've written a CRX-to-zip converter before, see https://github.com/Rob--W/crxviewer/blob/master/src/lib/crx-to-zip.js.

**Comment by Noitidart** [comment]
Thanks @Rob--W I actually did something similar last night I found PK43 then stripped up till there :d

https://github.com/Noitidart/Foxified-Chrome-Extensions-and-Store/blob/master/bootstrap.js#L182-L192
