### ISSUE TITLE
epub support (not a bug)

### ISSUE THREAD

**Issue by shorshe** [gildas-lormeau/zip.js#120]
Hi... just a quick feature request.
Since epub is a special case of a zip file. Do you think adding epub support to your lib would be an option?

**Comment by Rob--W** [comment]
When I viewed a .epub file, I saw that it started with the magic bytes `Pk\x03\x04`, which suggests that epub files are just regular zip files. I then opened the zip file with http://gildas-lormeau.github.io/zip.js/demos/demo2.html and didn't have any problems with listing the contents.

Given that .epub files can already be opened with zip.js, what do you mean by "adding epub support to zip.js"?

**Comment by shorshe** [comment]
Hi Rob!

Thanks for you reply!
Unzipping epubs is easy, yes. 
Zipping is a special case though:


"E-book readers require that the mimetype file is the first one in the zip document. What's more, to be fully compliant, this file should start at a very specific point - a 30-byte offset from the beginning of the zip file (so that the mimetype text itself starts at byte 38)."

Maybe this is outside the scope of your lib.

**Comment by duanyao** [comment]
Actually I have used zip.js to produce epub files for a long time. You just have to add the file "mimetype" firstly to a ZipWriter with compression level 0 (don't compress) to produce a valid epub file. I think zip.js itself doesn't have to known anything about epub.

http://www.idpf.org/epub/30/spec/epub30-ocf.html#sec-zip-container-mime

>3.3 OCF ZIP Container Media Type Identification

>OCF ZIP Containers must include a mimetype file as the first file in the Container, and the contents of this file must be the MIME type string application/epub+zip.

>The contents of the mimetype file must not contain any leading padding or whitespace, must not begin with the Unicode signature (or Byte Order Mark), and the case of the MIME type string must be exactly as presented above. The mimetype file additionally must be neither compressed nor encrypted, and there must not be an extra field in its ZIP header.
