### ISSUE TITLE
IE 10 not working with web workers

### ISSUE THREAD

**Issue by NikoDelarich** [gildas-lormeau/zip.js#121]
Due to a [bug in Internet Explorer 10](https://connect.microsoft.com/IE/feedback/details/783468/ie10-window-postmessage-throws-datacloneerror-for-transferrable-arraybuffers), ArrayBuffers can not be transferred to web workers.

For example:

    msg = {buf: myArrayBuffer};
    worker.postMessage(msg, [myArrayBuffer]);
will throw *DataCloneError* on IE10

Changing it to:

    msg = {buf: myArrayBuffer};
    worker.postMessage(msg);
solves the problem.

A simple solution would be to wrap the 2 problematic postMessage() calls (*step() in zip.js & processData() in z-worker.js*) in try/catch blocks and retry without specifying transferrables:

    msg = {buf: myArrayBuffer};
    try {
      worker.postMessage(msg, [myArrayBuffer.buffer]);
    } catch(ex) {
      worker.postMessage(msg); // Workaround for IE 10
    }

**Comment by Rob--W** [comment]
Sounds good to me. Could you submit a PR? Make sure that you add a comment that gives the reason for the try-catch including the affected browser version(s) and a link to the relevant bug report(s).
