### ISSUE TITLE
Uncaught InvalidStateError

### ISSUE THREAD

**Issue by plaastik** [gildas-lormeau/zip.js#125]
Uncaught InvalidStateError: Failed to execute 'write' on 'FileWriter': An operation that depends on state cached in an interface object was made but the state had changed since it was read from disk.writeUint8Array @ zip-ext.js:197onmessage @ zip.js:332

**Comment by Rob--W** [comment]
Do you have a demo page that triggers this error?

**Comment by plaastik** [comment]
It's a Chrome OS app, I seem to be unable to reproduce it now. I'll give it
another try later today and get back to you. Thanks for your prompt reply!

François
