### ISSUE TITLE
File already exists.

### ISSUE THREAD

**Issue by plaastik** [gildas-lormeau/zip.js#126]
I have an app that I am making for Chrome OS that uses your zip library which produces the error titled above.

The error occurs after creating, and every time closing after, several zip files with BlobReader. IT happens in this section of code :

function BlobReader(blob) {
        var that = this;

```
    function init(callback) {
        that.size = blob.size;
        // Here, line 174 of zip.js
                    callback();
    }
```

**Comment by plaastik** [comment]
The zipping of the files is triggered every time files are selected with a html input of type="file".

**Comment by Rob--W** [comment]
Please provide the source code for your Chrome app. And what is the size of the files that you're sending to zip.js?

**Comment by plaastik** [comment]
500-600k each totalling around 3 mb. Ok, one moment for the files.

**Comment by plaastik** [comment]
It ain't pretty yet, but here it is ...


zip.useWebWorkers = true;
zip.workerScriptsPath = "../assets/libs/zip/";

var fs = null;
var akryptikaApp = angular.module('akryptikaApp', []);

akryptikaApp.controller('MainController', ['$scope', MainController]);

function MainController($scope) {
    var contentHash = null;
    var currentContentHash = null;
    var contentProcessingDate = null;
    var cryptoAlgo = 0;
    var cryptoKey = null;
    var currentlyProcessing = false;
    var cryptoKeyType = 0;
    var fileKey = null;
    var encryptedContent = null;
    var decryptedContent = null;
    var signature = null;
    var fileContent = null;
    var encryptButton = document.getElementById('encrypt_btn');
    var decryptButton = document.getElementById('decrypt_btn');
    var selectedAction = 0;
    var filename = 'encrypted_file';
    var zipModel = (function() {
        var zipFileEntry, zipWriter, writer, creationMethod, URL = window.URL || window.webkitURL;

        return {
            addFiles: function addFiles(files, oninit, onadd, onprogress, onend) {
                var addIndex = 0;

                function nextFile() {
                    var file = files[addIndex];
                    onadd(file);
                    
                    zipWriter.add(file.name, new zip.BlobReader(file), function() {
                        addIndex++;
                        if (addIndex < files.length) {
                            nextFile();
                        } else {
                            onend();
                        }
                    }, onprogress);
                }

                function createZipWriter() {
                    zip.createWriter(writer, function(writer) {
                        zipWriter = writer;
                        oninit();
                        nextFile();
                    }, onerror);
                }
                if (zipWriter) nextFile();
                else if (creationMethod == "Blob") {
                    writer = new zip.BlobWriter();
                    createZipWriter();
                }
                else {
                    createTempFile(function(fileEntry) {
                        zipFileEntry = fileEntry;
                        writer = new zip.FileWriter(zipFileEntry);
                        createZipWriter();
                    });
                }
            },
            getFileURL: function(callback) {
                zipWriter.close(function(file) {
                    if(selectedAction === 0) {
                        encryptContent(file);
                    } else {
                        decryptContent(file);
                    }
                });
            },
            getFile: function(callback) {
                zipWriter.close(callback);
            }
        };
    })();
    
    function clearBuffers() {
        var contentHash = null;
        var contentProcessingDate = null;
        var cryptoAlgo = 0;
        var cryptoKey = null;
        var currentlyProcessing = false;
        var cryptoKeyType = 0;
        var fileKey = null;
        var encryptedContent = null;
        var decryptedContent = null;
        var signature = null;
        var fileContent = null;
        document.getElementById('encrypt_btn').removeAttribute('download');
        document.getElementById('decrypt_btn').removeAttribute('download');
        document.getElementById('encrypt_btn').removeAttribute('href');
        document.getElementById('decrypt_btn').removeAttribute('href');
        document.getElementById('detected_encryption').innerHTML = "";
        document.getElementById('passphrase_0').value = "";
        document.getElementById('digits_0').value = "";
        document.getElementById('passphrase_1').value = "";
        document.getElementById('digits_1').value = "";
    }
    
    function clearBuffersAfter() {
        document.getElementById('files').value = "";
        document.getElementById('choose_2').value = "";
        document.getElementById('choose_1_1').value = "";
        document.getElementById('choose_2_1').value = "";
        document.getElementById('choose_3').value = "";
        document.getElementById('selected_0').innerHTML = "";
        document.getElementById('selected_1').innerHTML = "";
        document.getElementById('selected_2').innerHTML = "";
        document.getElementById('selected_3').innerHTML = "";
    }
    
    function displayProgress() {
        document.getElementById('progress').style.display = "block";
    }
    
    function hideProgress() {
        document.getElementById('progress').style.display = "none";
    }

    function onerror(message) {
        console.log(message);
    }

    function createTempFile(callback) {
        var digits = Math.random() * 1000 + 5;
        var tmpFilename = "tmp" + digits.toString() + ".zip";
        console.log('tmpFilename :: ' + tmpFilename);
        window.webkitRequestFileSystem(TEMPORARY, 4 * 1024 * 1024 * 1024, function(filesystem) {
            function create() {
                filesystem.root.getFile(tmpFilename, {
                    create: true
                }, function(zipFile) {
                    callback(zipFile);
                });
            }
            filesystem.root.getFile(tmpFilename, null, function(entry) {
                entry.remove(create, create);
            }, create);
        });
    }

    function createSignature() {
        signature = cryptoAlgo + '^|^|^' + cryptoKeyType + '^|^|^' + contentProcessingDate  + '^|^|^' + contentHash;
    }

    function encryptContent(file) {
        fileContent = file.slice();
        contentHash = CryptoJS.SHA3(CryptoJS.lib.WordArray.create(new Uint8Array(fileContent))).toString();
                    
        switch (cryptoKeyType) {
        case 0:
            cryptoKey = document.getElementById('passphrase_0').value;
            break;
        case 1:
            cryptoKey = fileKey;
            break;
        case 2:
            cryptoKey = document.getElementById('digits_0').value;
            break;
        }

        var advOptions = null;
        var reader = new FileReader();
        var textContent = "";

        reader.onloadend = function() {
            textContent = reader.result;
            switch (cryptoAlgo) {
            case 0:
                encryptedContent = CryptoJS.AES.encrypt(textContent, cryptoKey);
                break;
            case 1:
                advOptions = document.getElementById('des_options').value;

                if (advOptions === '1') {
                    encryptedContent = CryptoJS.TripleDES.encrypt(textContent, cryptoKey);
                    break;
                }

                encryptedContent = CryptoJS.DES.encrypt(textContent, cryptoKey);
                break;
            case 2:
                encryptedContent = CryptoJS.Rabbit.encrypt(textContent, cryptoKey);
                break;
            case 3:
                advOptions = document.getElementById('rc4_options').value;

                if (advOptions === '1') {
                    encryptedContent = CryptoJS.RC4Drop.encrypt(textContent, cryptoKey);
                    break;
                }

                encryptedContent = CryptoJS.RC4.encrypt(textContent, cryptoKey);
                break;
            }
            currentlyProcessing = false;

            contentProcessingDate = Date.now();

            createSignature();

            var strContent = encryptedContent.ciphertext.toString() + '31337' + signature;
            var blobImage = new Blob([strContent], {
                type: 'plain/text'
            });
            
            var fileURL = URL.createObjectURL(blobImage);
            
            var clickEvent;
            clickEvent = document.createEvent("MouseEvent");
            clickEvent.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
            encryptButton.href = fileURL;
            encryptButton.download = filename + '.akry';
            encryptButton.dispatchEvent(clickEvent);
            hideProgress();
            clearBuffersAfter();
        };
        currentlyProcessing = true;
        reader.readAsText(fileContent);
    }

    function decryptContent(file) {
        switch (cryptoKeyType) {
        case 0:
            cryptoKey = document.getElementById('passphrase_1').value;
            break;
        case 1:
            cryptoKey = fileKey;
            break;
        case 2:
            cryptoKey = document.getElementById('digits_1').value;
            break;
        }

        var advOptions = null;
        var reader = new FileReader();
        var textContent = "";
        
        reader.onloadend = function() {
            textContent = reader.result;
            switch (cryptoAlgo) {
            case 0:
                decryptedContent = CryptoJS.AES.decrypt(textContent, cryptoKey);
                break;
            case 1:
                advOptions = document.getElementById('des_options').value;

                if (advOptions === '1') {
                    decryptedContent = CryptoJS.TripleDES.decrypt(textContent, cryptoKey);
                    break;
                }

                decryptedContent = CryptoJS.DES.decrypt(textContent, cryptoKey);
                break;
            case 2:
                decryptedContent = CryptoJS.Rabbit.decrypt(textContent, cryptoKey);
                break;
            case 3:
                advOptions = document.getElementById('rc4_options').value;

                if (advOptions === '1') {
                    decryptedContent = CryptoJS.RC4Drop.decrypt(textContent, cryptoKey);
                    break;
                }

                decryptedContent = CryptoJS.RC4.decrypt(textContent, cryptoKey);
                break;
            }
            currentlyProcessing = false;

            contentProcessingDate = Date.now();

            createSignature();

            var blobImage = new Blob([decryptedContent.ciphertext.toString() + '31337' + signature], {
                type: 'plain/text'
            });
            var fileURL = URL.createObjectURL(blobImage);
            
            var clickEvent;
            clickEvent = document.createEvent("MouseEvent");
            clickEvent.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
            decryptButton.href = fileURL;
            decryptButton.download = filename + '.akry';
            decryptButton.dispatchEvent(clickEvent);
            hideProgress();
            clearBuffersAfter();
        };
        currentlyProcessing = true;
        reader.readAsText(fileContent);
    }

    (function() {
        document.getElementById('files').addEventListener('change', function(evt) {
            var files = evt.target.files;

            zipModel.addFiles(files, function() {
                displayProgress();
            }, function(file) {}, function(current, total) {},
            function() {
                hideProgress();
            });
        }, false);
        encryptButton.addEventListener("click", function(event) {
            if (!encryptButton.download && validateEncryptTab()) {
                selectedAction = 0;
                clearBuffers();
                displayProgress();
                zipModel.getFileURL();
                event.preventDefault();
                return false;
            }
        }, false);
        decryptButton.addEventListener("click", function(event) {
            if (!decryptButton.download && validateDecryptTab()) {
                selectedAction = 1;
                clearBuffers();
                displayProgress();
                zipModel.getFileURL();
                event.preventDefault();
                return false;
            }
        }, false);
        document.getElementById('encryption_type').addEventListener('change', function() {
            var selectedIndex = this.value;

            if (selectedIndex === '1') {
                document.getElementById('algo_additional_options').style.display = "block";
                document.getElementById('rc4_options').style.display = "none";
                document.getElementById('des_options').style.display = "block";
            }
            else if (selectedIndex === '3') {
                document.getElementById('algo_additional_options').style.display = "block";
                document.getElementById('des_options').style.display = "none";
                document.getElementById('rc4_options').style.display = "block";
            }
            else {
                document.getElementById('algo_additional_options').style.display = "none";
            }
            cryptoAlgo = selectedIndex;
        }, false);
        document.getElementById('key_type_0').addEventListener('change', function() {
            var selectedIndex = this.value;

            if (selectedIndex === '0') {
                document.getElementById('passphrase_layer').style.display = "block";
                document.getElementById('filekey_layer').style.display = "none";
                document.getElementById('digits_layer').style.display = "none";
            }
            else if (selectedIndex === '1') {
                document.getElementById('passphrase_layer').style.display = "none";
                document.getElementById('filekey_layer').style.display = "block";
                document.getElementById('digits_layer').style.display = "none";
            }
            else {
                document.getElementById('passphrase_layer').style.display = "none";
                document.getElementById('filekey_layer').style.display = "none";
                document.getElementById('digits_layer').style.display = "block";
            }

            if (selectedIndex === '0') {
                document.getElementById('passphrase_layer_1').style.display = "block";
                document.getElementById('filekey_layer_1').style.display = "none";
                document.getElementById('digits_layer_1').style.display = "none";
            }
            else if (selectedIndex === '1') {
                document.getElementById('passphrase_layer_1').style.display = "none";
                document.getElementById('filekey_layer_1').style.display = "block";
                document.getElementById('digits_layer_1').style.display = "none";
            }
            else {
                document.getElementById('passphrase_layer_1').style.display = "none";
                document.getElementById('filekey_layer_1').style.display = "none";
                document.getElementById('digits_layer_1').style.display = "block";
            }

            document.getElementById('key_type_1').value = selectedIndex;
            cryptoKey = selectedIndex;
        }, false);
        document.getElementById('key_type_1').addEventListener('change', function() {
            var selectedIndex = this.value;

            if (selectedIndex === '0') {
                document.getElementById('passphrase_layer').style.display = "block";
                document.getElementById('filekey_layer').style.display = "none";
                document.getElementById('digits_layer').style.display = "none";
            }
            else if (selectedIndex === '1') {
                document.getElementById('passphrase_layer').style.display = "none";
                document.getElementById('filekey_layer').style.display = "block";
                document.getElementById('digits_layer').style.display = "none";
            }
            else {
                document.getElementById('passphrase_layer').style.display = "none";
                document.getElementById('filekey_layer').style.display = "none";
                document.getElementById('digits_layer').style.display = "block";
            }

            if (selectedIndex === '0') {
                document.getElementById('passphrase_layer_1').style.display = "block";
                document.getElementById('filekey_layer_1').style.display = "none";
                document.getElementById('digits_layer_1').style.display = "none";
            }
            else if (selectedIndex === '1') {
                document.getElementById('passphrase_layer_1').style.display = "none";
                document.getElementById('filekey_layer_1').style.display = "block";
                document.getElementById('digits_layer_1').style.display = "none";
            }
            else {
                document.getElementById('passphrase_layer_1').style.display = "none";
                document.getElementById('filekey_layer_1').style.display = "none";
                document.getElementById('digits_layer_1').style.display = "block";
            }

            document.getElementById('key_type_0').value = selectedIndex;
            cryptoKey = selectedIndex;
        }, false);
        
        document.getElementById('files').addEventListener('change', function() {
            var strArray = document.getElementById('files').value.split("\\");
            var selected = strArray[strArray.length - 1];
            clearBuffers();
            document.getElementById('selected_0').innerHTML = selected;
        });
    
        document.getElementById('choose_2').addEventListener('change', function() {
            var strArray = document.getElementById('choose_2').value.split("\\");
            var selected = strArray[strArray.length - 1];
            clearBuffers();
            document.getElementById('selected_2').innerHTML = selected;
        });

        function handleKeyChange(evt) {
            var files = document.getElementById('choose_2').files;
            var file = files[0];

            fileKey = CryptoJS.SHA3(CryptoJS.lib.WordArray.create(new Uint8Array(file.slice()))).toString();
        }
        
        function handleDecryptFileSelection(evt) {
            var files = document.getElementById('choose_1_1').files;
            var file = files[0];
            clearBuffers();

            if (file.name.indexOf('.akry') !== -1) {
                var strArray = document.getElementById('choose_1_1').value.split("\\");
                var selected = strArray[strArray.length - 1];
            
                document.getElementById('selected_1').innerHTML = selected;
            
                var selectFile = document.getElementById('selectFile_1');
                selectFile.setAttribute('class', '');
            
                readSignature(file);
            } else {
                var selectFile = document.getElementById('selectFile_1');
                
                selectFile.setAttribute('class', 'error');
            }
        }
        
        function readSignature(file) {
            fileContent = file.slice();
            
            var reader = new FileReader();
            var textContent = "";
            
            displayProgress();
    
            reader.onloadend = function(e) {
                textContent = new String(reader.result);
                
                textContent = textContent.split('31337');
                console.log('1 - count :: ' + textContent.length);
                signature = textContent[1];
                signature = signature.split('^|^|^');
                cryptoAlgo = signature[0];
                cryptoKeyType = signature[1];
                contentProcessingDate = signature[2];
                contentHash = signature[3];
                console.log('2 - count :: ' + signature.length);
                currentContentHash = CryptoJS.SHA3(CryptoJS.lib.WordArray.create(new Uint8Array(textContent[0]))).toString();
                console.log('3');
                console.log('Algo :: ' + cryptoAlgo);
                console.log('KeyType :: ' + cryptoKeyType);
                console.log('Processing Date :: ' + contentProcessingDate);
                console.log('Hash (from signature) :: ' + contentHash);
                console.log('Hash (from file) :: ' + currentContentHash);
                console.log('4');
                var controlHandle = document.getElementById('encryption_type');
                document.getElementById('detected_encryption').innerHTML = controlHandle.options[controlHandle.selectedIndex].text;
                document.getElementById('key_type_1').selectedIndex = cryptoKeyType;
                hideProgress();
            }
            reader.readAsText(fileContent);
        }

        document.getElementById('choose_1_1').addEventListener('change', handleDecryptFileSelection, false);
        document.getElementById('choose_3').addEventListener('change', function(evt) {}, false);
        document.getElementById('choose_2').addEventListener('change', handleKeyChange, false);
    })();
}

MainController.$inject = ['$scope'];

**Comment by plaastik** [comment]
The error occurs in this method ...

            function nextFile() {
                var file = files[addIndex];
                onadd(file);

                zipWriter.add(file.name, new zip.BlobReader(file), function() {
                    addIndex++;
                    if (addIndex < files.length) {
                        nextFile();
                    } else {
                        onend();
                    }
                }, onprogress);


in the new BlobReader instance.

**Comment by Rob--W** [comment]
That's a bit too much code to go through. Could you reduce your example to a **runnable** minimum that I can use to reproduce the problem?
