### ISSUE TITLE
Reading big zip files containing 2000 small files

### ISSUE THREAD

**Issue by cecemel** [gildas-lormeau/zip.js#127]
Hi, 

first of all, thank you for publishing such a wonderful library. I've used it so far for creating big zip files of many files, and it works like a charm.

Now I have a question: could you give me some hints, on how to use the library in its most efficient way, where I need to read a big file (approx. 500 MB, containing approx. 2000 files), retrieving the Blob for each file, and storing the Blob to an indexedDB. This (of course) client side on the most modern available browser (firefox, chrome). 

So here is my code:

        var writer = new zip.BlobWriter(); //create only one writer

        zip.createReader(new zip.BlobReader(uploader.files[0]),

        function (zipReader) {

            zipReader.getEntries(function (entries) {

                entries.forEach(function (entry) {

                    if (entry.bitFlag === 0) {
                        return;
                    }

                    //this seems to take a lot of time
                    entry.getData(writer, function (blob) {

                        blob.name = help_generate_guid();

                        //here the file is added to DB (this may be ignored)
                        files_dao.add_file(blob.name, blob, function () {
                            console.log('hurray');
                        }, function () {
                            console.log('booo');
                        });
                        //end database storage

                    });
                });
            });

        });

So, my questions are: 
- is there a possibility to improve speed especially the getData() per file
- is there a way to improve garbage collecting after the entry has been changed into a Blob and pushed to the DB?

I know, very general questions, but I just want to make sure I use this the correct way....

thank you very much

**Comment by duanyao** [comment]
>is there a possibility to improve speed especially the getData() per file

You can use pako or zlib-asm to speed up, see http://gildas-lormeau.github.io/zip.js/core-api.html#alternative-codecs

>is there a way to improve garbage collecting after the entry has been changed into a Blob and pushed to the DB?

Your code above seems inflating all entries concurrently, however at present zip.js only uses one web worker, so there is little performance benefit, and might consume a lot of memory. I suggest do inflation serially.

Also note that a `zip.XxxWriter` should not be shared by multiple `entry.getData()` calls, because  concurrent writing might mess up the output. `zip.BlobWriter` is lightweight so don't worry about creating many of it.

**Comment by cecemel** [comment]
Hello again, 

thank you very very much. 
I took the tips you gave me, and now its all sweetness!

Just side note. I did a some preliminary tests in chrome, and although zlib-asm is (extremely) faster than the default deflater, the memory consumption with regard to the default is 20% higher. 

I finally settled with pako, speed is better than default, memory consumption is a bit lower.

**Comment by duanyao** [comment]
Currently we do deflation/inflation in one shot with zlib-asm, which means a whole entry data has to be loaded into memory, see 
https://github.com/gildas-lormeau/zip.js/blob/master/WebContent/zlib-asm/codecs.js#L32

This may be one of the reason why it uses more memory than pako and the default deflater.
