### ISSUE TITLE
Errors thrown when extracting a zip file that contains zero byte files

### ISSUE THREAD

**Issue by timclipsham** [gildas-lormeau/zip.js#128]
I was able to reproduce it in the demo page (`https://gildas-lormeau.github.io/zip.js/demos/demo2.html`) when I passed the `checkCrc32` argument to `getData` as `true`. It works as expected when `checkCrc32` is `false`.

The actual error:
`TypeError: Cannot read property 'codec' of undefined (z-worker.js:78)`

**Comment by duanyao** [comment]
Oh, my fault. Zero-length file doesn't trigger an 'append' message (only 'flush' is sent), so the task is not created in the worker. Creation of zip is also affected. Fixed in #129.
