### ISSUE TITLE
AE-1 and/or AE-2 AES encrypted file creation

### ISSUE THREAD

**Issue by marcooliveira** [gildas-lormeau/zip.js#13]
I'm interested in adding support to create AES encrypted files to this library. Not sure if this was in your roadmap, but I've been taking a look at the specification, and without actually looking to the `zip.js` implementation in depth, it looks like this is doable. Do you see any pitfall, or do you have any tip on doing this?

Also, from what I understood, `zip.js` does not support generating the file in chunks, right? From what I understood, If I try to create a `4GB` file, the file will be put in RAM/HDD.

Thanks.

**Comment by evilaliv3** [comment]
@marcooliveira / @gildas-lormeau what about this ticket? is still something that you consider doable or even on the roadmap?

**Comment by marcooliveira** [comment]
Hi @evilaliv3, unfortunately I'm no longer in a position in which I can pursue this, no time. But from what I remember, I think it's relatively simple to execute yourself, if you need it. @gildas-lormeau left some nice tips on how to achieve it.

**Comment by gildas-lormeau** [comment]
It's fixed in the version 2 I just published.
