### ISSUE TITLE
mention browserify port

### ISSUE THREAD

**Issue by juliangruber** [gildas-lormeau/zip.js#133]
Hey! I ported this awesome library to browserify: https://github.com/juliangruber/zipjs-browserify.

It could be of help to others using browserify to mention this library somewhere in the docs. There seem to be more ports of zip.js, so a ports section could be cool.

Another cool thing would be to use UMD to make zip.js available to multiple platforms without needing wrappers / parts. What do you think about that? I'd be glad to help.

**Comment by gildas-lormeau** [comment]
I'm closing the issue because I rewrote SingleFile to package it as an UMD module. You would need to update your port.
