### ISSUE TITLE
Read entry as uint8array?

### ISSUE THREAD

**Issue by Noitidart** [gildas-lormeau/zip.js#134]
Currently I am able to read entries as a blob like this:

```
  zip.createReader(new zip.BlobReader(blob), function(zipReader) {
    // get entries from the zip file
    zipReader.getEntries(function(entries) {
      // get data from the first file
      entries[0].getData(new zip.BlobWriter("text/plain"), function(data) {
        // close the reader and calls callback function with uncompressed data as parameter
        zipReader.close();
        callback(data);
      });
    });
  }, onerror);
```

 but i need to read it as a uint8array. I rather not use:

```
var reader = new FileReader();
reader.addEventListener("loadend", function() {
   // reader.result contains the contents of blob as a typed array
});
reader.readAsArrayBuffer(blob);
```

My goal is to convert each entry in `entries` to an arraybuffer. Is there anyway to get the buffer? And does the buffer get transfered over from the worker to the mainthread? (Or is it copied over to the mainthread? (I'm hoping transferred ;) )

By the way, are the blobs transferred from the worker to the mainthread? Or copied?

**Comment by Rob--W** [comment]
Under the hood Uint8Arrays are used to construct the Blob: https://github.com/gildas-lormeau/zip.js/blob/1bead0a3bb9d2e50ea34094bbfe9bb6a2196939a/WebContent/zip.js#L169-L193

And also to write the Uint8Array: https://github.com/gildas-lormeau/zip.js/blob/1bead0a3bb9d2e50ea34094bbfe9bb6a2196939a/WebContent/zip.js#L329-L344

You could create a new `Uint8ArrayWriter` class (look at `BlobWriter`, `TextWriter`, ... for examples) that takes the typed array. If you submit a Pull request I'll review it.

**Comment by Noitidart** [comment]
Thanks @Rob--W I was hoping there was some way without editing it.

However if editing is the only way, I was thinking of making zip.js a worker, so its totally async. Do you see any blockers from making this a worker? I think FileReaderSync is only available to Firefox, so this edit will be Firefox specific: https://developer.mozilla.org/en-US/docs/Web/API/Worker/Functions_and_classes_available_to_workers#workerscope

**Comment by Noitidart** [comment]
To make it compatible with Firefox addons out of the box these are the changes that had to be made:

zip.js was the only thing that needed modification, note especially the lack of FileReader so I had to use XPCOM to get it:

https://github.com/Noitidart/AysncZip/commit/40fde8e1cca92ac1a6d0cd5307f46957cd884e98

**Comment by Rob--W** [comment]
@Noitidart I'll continue the discussion about workers at #135.

**Comment by Noitidart** [comment]
Thanks Rob! Understood

**Comment by maxscipio** [comment]
Hi,

I have a similar problem: I have a bunch of ROM content in the zip file (for emulator) and I am trying to read it into a variable representing the emulated memory.

	for (i = 0; i < entryLength; i++) {
		entry = entries[i];
		fileName = entry.filename;
		fileCRC = displayHex(entry.crc32,8);
		fileUncompressedSize = entry.uncompressedSize; 
		entry.getData(new zip.ArrayBufferWriter(), function(data) {
		   myrom.set(data);
		   console.log(myrom);
		});
	}
myrom is always containing 0 no matter what. What am I doing wrong?
Note once this works for one, I'll add an offset to the .set command.
Thanks!

**Comment by Rob--W** [comment]
`data` is an ArrayBuffer. You need to wrap it in a typed array before it
can be assigned to another typed array, i.e. use `myrom.set(new
Uint8Array(data))`

Also `.set` starts writing at offset 0 by default. If you want to append
all data to your "from", then you need to keep track of the offset, e.g.

Before the loop:

    len = 0;

During the loop:

    myrom.set(new Uint8Array(data), len);
    len += data.byteLength;

**Comment by maxscipio** [comment]
Hi Rob,

I tried but it still doesn't bring back any data. Here the complete code,
just for reference. I loop twice through the entries to find all the files
first but I don't read anything. Could that be causing the issue?
Thanks a lot for looking into it! And great job on this lib.

zip.useWebWorkers = false;//explicitly include (required) zip-workers
['zip.js','zip-fs.js','z-worker.js','inflate.js','deflate.js']

function readEntries(entries) {
    var entryLength = entries.length;
    var candidateMachine = new Object();
    //romDatabase.compileMachineInfo();
    var i;
    var matchingMachine = "";
    var fileCRC;
    var fileUncompressedSize;
    var entry;
    var fileName;
    var matched_string;
    for (i = 0; i < entryLength; i++) {
        entry = entries[i];
fileCRC = entry.crc32;
        fileName = entry.filename; //if inside folder
fileUncompressedSize = entry.uncompressedSize;
if (romDatabase.getRomInfo(fileCRC, fileUncompressedSize) != null) {
            machine = romDatabase.getRomInfo(fileCRC, fileUncompressedSize);
            if (candidateMachine[machine] == undefined) {
                candidateMachine[machine] = 1;
            }
        }
    }
    for (i in candidateMachine) {
        if (romDatabase.isSetComplete(i)) {
            console.log("Found all roms for driver: " + i);
            matchingMachine = i;
}
    }
    var myrom = new Uint8Array(16384);
    myrom.fill(0xff);
    for (i = 0; i < entryLength; i++) {
        entry = entries[i];
        fileCRC = entry.crc32;
        fileName = entry.filename; //if inside folder
        fileUncompressedSize = entry.uncompressedSize;
        if
(romDatabase.isThisRomInTheDriver(fileCRC,fileUncompressedSize,matchingMachine))
{
            entry.getData(new zip.BlobWriter(), function (blob) { //
zip.getMimeType(fileName)
                 let myset = new Uint8Array(blob);
                 myrom.set(myset, romDatabase.getLoadOffset(fileCRC,
fileUncompressedSize);
                 console.log(myset);
                 //console.log(myrom);
           });
        }
    }
}


var openFile = function(event) {
document.getElementById("zipfile").style.visibility = 'hidden';
var fileInput = event.target;
    zip.createReader(new zip.BlobReader(fileInput.files[0]),
function(zipReader) {
        zipReader.getEntries(readEntries);
zipReader.close();
    }, function (error) {
         console.log(error);
    });

};


Here the HTML:
<!DOCTYPE html>
<html>
<head>
    <title>Zip test</title>
</head>
<body>
    <script src="include/zip.js"></script>
    <script src="include/zip-fs.js"></script>
    <script src="include/zip-ext.js"></script>
    <script src="include/deflate.js"></script>
    <script src="include/inflate.js"></script>
    <script src="include/z-worker.js"></script>
    <script src="machine.js"></script>
    <script src="filehandle.js"></script>
    <input  type='file' id="zipfile" onchange='openFile(event)'/>

</body>
</html>

**Comment by Rob--W** [comment]
You should use an ArrayBufferWriter, not BlobWriter.

**Comment by maxscipio** [comment]
thanks Rob! worked like a charm.
