### ISSUE TITLE
callback for succesfull unzip process

### ISSUE THREAD

**Issue by benson-jala** [gildas-lormeau/zip.js#136]
I am downloading 200mb file and unzipping, i need to call a function after everything unzips.
how to get the information that the unzipping process is completed.

Thank you

**Comment by Rob--W** [comment]
What code are you using for unzipping?

**Comment by benson-jala** [comment]
zipFs.importHttpContent(fileUrl, false, function() {
                finalDirEntry.getDirectory(finalDir, {
                        create: true
                    },
                    function(finalDirEntry) {
                        processZipEntry(finalDirEntry, zipFs.entries[0].children, me.itemArray);
                    },
                    function(error) {
                        // console.log(error);
                    });
                // recursive function to run through the directory
                // start it off with the root entry
                function processZipEntry(parentDir, zipEntries, itemArray) {
                    zipEntries.forEach(function(zipEntry) {
                        if (zipEntry.directory) {
                            parentDir.getDirectory(zipEntry.name, {
                                    create: true
                                },
                                function(dirEntry) {
                                    processZipEntry(dirEntry, zipEntry.children, itemArray);
                                },
                                function(error) {
                                });
                        } else {
                            parentDir.getFile(zipEntry.name, {
                                    create: true
                                },
                                function(fileEntry) {
                                    zipEntry.getFileEntry(fileEntry,
                                        function(entry) {
//here i will get the each file entry.
                                        });
                                },
                                function(error) {
                                    me.onError(Utility.DC_UNZIP_FILE_ERROR, error, callback)
                                });
                        }
                    });
                };
            },
            function(error) {
                console.log('outside_error');
                Ext.Msg.alert(Utility.ERROR_TITLE, Utility.DOWNLOAD_FAIL);
            });

**Comment by Rob--W** [comment]
You could initialize a counter at zero, and then increase a counter by `zipEntries.length` at the beginning of `processZipEntry`, and decrease this counter at the end of the success & error callbacks in `getDirectory` / `getFile`. After decreasing the counter, check whether the counter is zero and if so, extraction has finished.

**Comment by benson-jala** [comment]
i am doing the same for now, but is their any success callback.
if the file size is big the counter will update but actual unzip takes couple of  sececonds.
How to overcome this issue?

Thank You

**Comment by Rob--W** [comment]
@benson-jala Did you understand my previous response? I described a method that you can use to detect when unzipping completely finished. Perhaps I was unclear, but by putting the callback at the end of the success / error callbacks, I meant to say that you need to call the callback when the innermost reachable callback has finished.
