### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by kofifus** [gildas-lormeau/zip.js#137]
is there a CDN for zip.js ?
If not can one be created ?

**Comment by jimaek** [comment]
http://www.jsdelivr.com/projects/zip.js

**Comment by kofifus** [comment]
tank you :) is there a minified version on CDN ?

Ideally would be great to have one minified file with zip.js, z-worker.js, deflate.js, and inflate.js on CDN - can this be done ?

Thanks!

**Comment by kofifus** [comment]
also the doc said z-worker.js is necessary but it's missing from the CDN ?

**Comment by jimaek** [comment]
I used the original files as source. You can send a PR to add what is missing

**Comment by kofifus** [comment]
well I can concatenate zip.js, z-worker.js, deflate.js, and inflate.js together and minify them and post that as PR - is that what you mean ?

Would I need to change zip.workerScriptsPath in this case ?

**Comment by jimaek** [comment]
>well I can concatenate zip.js, z-worker.js, deflate.js, and inflate.js together and minify them and post that as PR - is that what you mean ?

Yes

>zip.workerScriptsPath

If you retain the same filename then its not required, right? We can create a new version called `0.1b`

**Comment by kofifus** [comment]
thx I'll give it a try when I have some time 

- what should I call this file ? zipper.min.js ?

- in the mean time is it possible to load z-worker.js to CDN ?

**Comment by PhilippWendler** [comment]
While you are at it, could you please also add `zip-ext.js` to the CDN? That would be great.

**Comment by PhilippWendler** [comment]
jsDelivr now says (on the page linked above) that this project needs GitHub releases in order to make use of the CDN. Would it be possible to do this? (Also requested by #145.)

**Comment by gildas-lormeau** [comment]
I deployed a release for the version 2.0. I guess it will be available soon on https://www.jsdelivr.com.
