### ISSUE TITLE
Extract Zip from project folder or URL

### ISSUE THREAD

**Issue by CiccioCicc** [gildas-lormeau/zip.js#143]
Hi,

I have t extract zip (it contains pdf files) from project folder or from url.
How can I do it? Is there a code example?

Thanks.

Francesco.

**Comment by alexmatveev** [comment]
+1

**Comment by AlexanderMatveev** [comment]
🤷🏻‍♂️🙂

**Comment by gildas-lormeau** [comment]
I closed some old issues to do a little cleaning after having released the new version. @AlexanderMatveev can you give me more details about your need? The `HttpReader` should do the job.

**Comment by gildas-lormeau** [comment]
This test shows how to use it: https://github.com/gildas-lormeau/zip.js/blob/master/tests/test-invalid-crc.js.
