### ISSUE TITLE
Get entry data and stream directly to server

### ISSUE THREAD

**Issue by manderson23** [gildas-lormeau/zip.js#144]
From what I can see getEntry will always read the full data for that entry into browser memory.

It would be useful if an entry could be read and streamed directly to the server via HTTP POST.

**Comment by cecemel** [comment]
+1

**Comment by gildas-lormeau** [comment]
I'm closing the issue because it's old and I'm not sure on how it should be implemented. Feel free to reopen it if you're still interested and if you can provide more details.
