### ISSUE TITLE
Creating Releases

### ISSUE THREAD

**Issue by sreenaths** [gildas-lormeau/zip.js#145]
- Would be great if we can have release versions. That would make dependency addition easier.
- Its simple and straight forward https://help.github.com/articles/creating-releases/

**Comment by sreenaths** [comment]
- We need some way to fix on to a specific commit of the package. If not release versions, SHA is the only other option.
- At times, bower fails when a package is added as a dependency with a SHA.
- Hence this is kind of important for the build stability of projects that use zip.js.

**Comment by gildas-lormeau** [comment]
That's done!
