### ISSUE TITLE
how to get file object after unzipping 

### ISSUE THREAD

**Issue by MuDiAhmed** [gildas-lormeau/zip.js#146]
i need to unzip and then upload every file
i tried entry.getData(new zip.FileWiter() )
i get zip.FileWriter is not a constructor

**Comment by Rob--W** [comment]
Did you load [`zip-ext.js`](https://github.com/gildas-lormeau/zip.js/blob/master/WebContent/zip-ext.js)?

**Comment by MuDiAhmed** [comment]
yes i did after that i get ( fileEntry.createWriter is not a function )

**Comment by Rob--W** [comment]
Can you share a full snippet?

**Comment by MuDiAhmed** [comment]
Thank you for replying.

`zip.createReader(new zip.BlobReader(newValue), function(reader) {
                reader.getEntries(function(entries) {
                    if (entries.length) {
                        for(var i=0;i<entries.length;i++){
                            if(!entries[i].directory){
                                entries[i].getData( new zip.FileWriter(entries[i]), function(file) {
                                    console.log( file);
                                }, function(current, total) {
                                    // onprogress callback
                                });
                            }
                        }
                    }
                });
            }, function(error) {
            });`

**Comment by Rob--W** [comment]
`FileWriter` expects a [`FileEntry` object](https://www.w3.org/TR/2012/WD-file-system-api-20120417/#the-fileentry-interface), while  `entries[i]` in your snippet is an [`Entry` object](https://gildas-lormeau.github.io/zip.js/core-api.html#zip-entry).

If you want a [`File` object](https://developer.mozilla.org/en-US/docs/Web/API/File), consider using a `zip.BlobWriter` instead. `File`s are `Blob` objects + file name, so for all intents and purposes they are equal. If you want a `File` instance, then you can use the `File` constructor (in modern browsers!!!) to turn a `Blob` into a `File`.

**Comment by MuDiAhmed** [comment]
Thank you so much for your help
It works fine now 
but how can i get `FileEntry objects`

**Comment by Rob--W** [comment]
Through the filesystem API. But currently only Chrome supports it (the spec is deprecated and will never be implemented by other browsers).

**Comment by MuDiAhmed** [comment]
Thank you very much, You are so helpful :+1:
