### ISSUE TITLE
Demo - Uncaught TypeError: zip.FileWriter is not a constructor

### ISSUE THREAD

**Issue by jimmywarting** [gildas-lormeau/zip.js#147]
...When using the HDD method it throws an error

```
Uncaught TypeError: zip.FileWriter is not a constructor
   (anonymous function) @ demo1.js:64
   (anonymous function) @ demo1.js:16
```

Also you should switch the order you get URL cuz webkit is deprecated
`URL = obj.webkitURL || obj.mozURL || obj.URL;`
`URL = obj.URL || obj.webkitURL || obj.mozURL;`

**Comment by Rob--W** [comment]
Fixed in https://github.com/gildas-lormeau/zip.js/commit/9a6faf34138c2a0bc85fbdada98d4e76b99825cc

I agree with the prefixes of the prefixes, but since it doesn't break functionality I didn't change it. The filesystem API only works in Chrome and the spec has been deprecated so I don't see a point in putting more efforts in the filesystem API support.

**Comment by jimmywarting** [comment]
Quick fix ;)

Fair enough with the obj.URL.

Thought the naming was a bit confusing, zip.BlobWriter, zip.FileWriter...
I confuse them with writing either to any of this:

```javascript
new Blob([parts], {type: "mime/type"})
new File([parts], 'arcive.zip', {type: "mime/type"})
```

Should be more obvious that says it will write to memory or filesystem
Writing to HDD is in a since misguiding
- It's true since it will write to the HDD, but it's a sandboxed filesystem. 
- It will not really write to a location outside the sandbox that will make the file stick around until user deletes it
- this will also counts toward the origins storage quota, wish you would not think if it did write to the HDD outside the sandboxed filesystem

Cuz now there is a way to write to the HDD directly without any client side storage!
[StreamSaver.js](https://github.com/jimmywarting/StreamSaver.js) is something i have built to help out with that. And that is also the reason why I come here to suggest it

**Comment by jimmywarting** [comment]
...piping would be awesome
