### ISSUE TITLE
How to compress the file on the fly and send to server while submitting the form?

### ISSUE THREAD

**Issue by sriramkp** [gildas-lormeau/zip.js#150]
I have input tag type file and a submit button in a form. So the user can select the file and click on the submit button. My requirement here is the selected file must be read and compressed on the fly in memory and send the compressed file/blob to the server. Here I want to do 2 things. 1. compress the user selected file in memory 2. replace the file with the compressed file/blob to the form. I want handle all this as part of the $("#form").submit(function (event) { ... });

**Comment by Rob--W** [comment]
Use `FormData` objects, see https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects
