### ISSUE TITLE
zip.createWriter is not working

### ISSUE THREAD

**Issue by sriramkp** [gildas-lormeau/zip.js#151]
In the below code is zip.createWriter is giving error.

```
var File = document.getElementById('File').files[0];

zipBlob(File, function (zippedBlob) {

        cmprFormData.set("File", zippedBlob, "filename.zip");
    });

function onerror(message) {

    console.error(message);
    alert(message);
}

function zipBlob(blob, callback) {

    zip.createWriter(new zip.BlobWriter("application/zip"), function (zipWriter) {

        zipWriter.add(blob.name, new zip.BlobReader(blob), function () {

            zipWriter.close(callback);
        });
    }, onerror);
}

```

Error Message:

bubbles
:
false
cancelBubble
:
false
cancelable
:
true
currentTarget
:
Worker
defaultPrevented
:
false
eventPhase
:
0
isTrusted
:
true
isTrusted
:
true
path
:
Array[0]
returnValue
:
true
srcElement
:
Worker
target
:
Worker
timeStamp
:
42883.82
type
:
"error"

**Comment by benwiley4000** [comment]
I'm experiencing the same problem. No need for me to copy paste my error; it's the same as above.

**Comment by theTrip73** [comment]
Same. It's a shame that the error isn't coming back with any useful information. I wonder what could have changed to cause this.

**Comment by theTrip73** [comment]
Here is the part that's throwing the Event object to ```onerror``` instead of an Error object.

zip.js, lines 911-916:

```
        // catch entry script loading error and other unhandled errors
        worker.addEventListener('error', errorHandler);
        function errorHandler(err) {
            worker.terminate();
            onerror(err);
        }
```

I'm continuing to dig on this.

**Comment by theTrip73** [comment]
I attempted to change it to this:

```
        // catch entry script loading error and other unhandled errors
        worker.onerror = function (message, url, line_number) {
            worker.terminate();
            onerror(message);
        }
```

Behavior did not change.

**Comment by theTrip73** [comment]
Well, I was unable to get an actual error to render here, but my problem was that even though zip.js and the other js files were in the same directory, I still needed to declare ```zip.workerScriptsPath```.

I solved my issue with an absolute URL pointing to the folder where the js files reside.

**Comment by Wendanly** [comment]
你好！“一个绝对URL指向js文件所在的文件夹” 怎么理解呀？ 谢谢了哈！！

**Comment by Wendanly** [comment]
@trip-somers 你好！“一个绝对URL指向js文件所在的文件夹” 怎么理解呀？ 期待你的回答！！^O^
