### ISSUE TITLE
unzip the filename not support chinese

### ISSUE THREAD

**Issue by zhoujianlin8** [gildas-lormeau/zip.js#152]
unzip the filename not support chinese  (解压的文件名称中文乱码)

**Comment by duanyao** [comment]
中文 Windows 系统上的 zip 压缩工具一般用 GBK 来编码文件名，但是 zip.js 只支持 UTF-8，这种情况基本是无解的。
Most zip tools on Windows in zh-CN locale encode file names in GBK; however zip.js can only decode UTF-8, so such zip files can hardly be supported.

**Comment by zhoujianlin8** [comment]
我是在Mac 上测试的  解压出来的中文文件名称乱码  
http://gildas-lormeau.github.io/zip.js/demos/demo2.html 
您看下这个demo 出来的结果
@duanyao

**Comment by duanyao** [comment]
你需要提供出问题的zip文件。

**Comment by duanyao** [comment]
Maybe a duplication of #131 ?

**Comment by gildas-lormeau** [comment]
closed as duplicate of https://github.com/gildas-lormeau/zip.js/issues/131
