### ISSUE TITLE
zip.js - unable to zip document from remote location(site)

### ISSUE THREAD

**Issue by Priyanka11june** [gildas-lormeau/zip.js#153]
My requirement is to download the zip file when i click the download button. How to do this? I am completely stuck in generating the zip file.

<body>
    <a id ='file' href="docurl" type="application/pdf" name="Sample.pdf">Sample.pdf</a>
    <button onclick="create_zip()">Click me</button> 

<script type="text/javascript">

var FILENAME = document.getElementById('file').name;
var URL = document.getElementById('file').href;
var zipFs = new zip.fs.FS();
function zipPDF() {
    zipFs.root.addHttpContent(FILENAME, URL);
}
function create_zip(){
    zipPDF();
}
</script>

Also, currently I am using jszip-util.js for the same requirement but for files more than 300MB, it wont work in IE.

**Comment by GrosSacASac** [comment]
maybe IE limits the amount of memory available.
