### ISSUE TITLE
getData method doesn't fire any callback (onend, onprogress or onerror) if the reader has been closed

### ISSUE THREAD

**Issue by bcartolo** [gildas-lormeau/zip.js#157]
Outline of the code to reproduce:

```
zip.createReader(new zip.BlobReader(someBlob), function(zipReader) {

    zipReader.getEntries(function(entries) {

        // Commenting the following line fixes the problem.
        zipReader.close();

        entries[0].getData(new zip.TextWriter(), function() {
            // Not called
        }, function() {
            // Not called
        }, function() {
            // Not called
        });

    });

});
```

getData method should fire the onError callback explaining that the reader was closed.

**Comment by GrosSacASac** [comment]
Why would you close the reader in the first place ?

**Comment by bcartolo** [comment]
It was a bug on my code. With so many callbacks here and there. One of them was closing the reader before another one was trying to use it.

The problem is that that other callback didn't continue onto any of the other callbacks (onend, onerror, etc) making it very difficult to debug.

**Comment by matbo81** [comment]
ok, then please close this issue
