### ISSUE TITLE
Demo fails without web workers

### ISSUE THREAD

**Issue by benbankes** [gildas-lormeau/zip.js#158]
When I turn off web workers in the Chrome CLI
`zip.useWebWorkers = false`
The demo at:
http://gildas-lormeau.github.io/zip.js/demos/demo1.html
Fails with the following message:
`obj.zip.Deflater is not a constructor` (zip.js line 469, commit hash 1bead0a)

**Comment by Rob--W** [comment]
You have to load [`deflate.js`](https://github.com/gildas-lormeau/zip.js/blob/master/WebContent/deflate.js).

E.g. if you use the online demo, run the following from the console:

```
var s = document.createElement('script');
s.src = 'deflate.js';
document.head.appendChild(s);
```
