### ISSUE TITLE
What is the exact license ?

### ISSUE THREAD

**Issue by GrosSacASac** [gildas-lormeau/zip.js#162]
There are many BSD license. Could you put a link, or a copy to one particular BSD license ?

**Comment by pombredanne** [comment]
@GrosSacASac See the comment by @gildas-lormeau  https://github.com/gildas-lormeau/zip.js/issues/10#issuecomment-6495828

> There is a license in each main JS files (deflate, inflate, zip, zip-fs). It's a BSD license.

This is New/Modified or 3 Clause BSD with an  SPDX if of : `BSD-3-Clause` ... The README could be made clearer for sure but each file has its own copy of the license alright.  See also https://github.com/clearlydefined/curated-data/pull/2290 which is how I found out about the issue
