### ISSUE TITLE
Chrome and Codec error

### ISSUE THREAD

**Issue by dolare1** [gildas-lormeau/zip.js#166]
Hi All:

I am using Chrome Version 56.0.2924.87 to develop a zip utility for a custom application. I get the below alert and error when I try to zip the files in Chrome. Any pointers?

> Error: Cannot read property 'Codec' of undefined

> "TypeError: Cannot read property 'codec' of undefined
    at processData (z-worker.js:78:17)
    at z-worker.js:14:5"

Thanks!

**Comment by Rob--W** [comment]
Can you share an example where this happens?

**Comment by dolare1** [comment]
Below is source code. Mainly utilizing zipmodel's addFiles method. Sorry about formatting.

`// JavaScript source code
(function () {       

        window.addEventListener("load", function () {
            $("#mfdbtn").click(function (e) {
                var currentFile = null;
                var totalFiles = 0;
                var currentFileIndex = 0;

                handleDownloadStarted();
                showProgressNotification("Preparing ZIP archive for download...", true);
                console.log("you should see progress notification");

                var fileList = [];
                $("input[id$='itemcb']").each(function () {
                    //alert($(this).attr('id'));                                    
                    if ($(this).is(":checked")) {
                        var idstring = $(this).attr('id');
                        var itempathidstring = idstring.replace('_itemcb', '_item_itemPath');
                        var itemtitleidstring = idstring.replace('_itemcb', '_item_itemTitleLink');
                        //alert('checked and the itempathid will be ' + itempathidstring);
                        var itemPath = $("#" + itempathidstring).attr('title');
                        var itemTitle = $("#" + itemtitleidstring).attr('title');
                        var fileExtension = getfileextension(itemPath);
                        //console.log(itemTitle + '***' + itemPath + '****' + itemTitle + fileExtension);
                        fileList.push({ name: itemTitle + fileExtension, url: itemPath, ext: fileExtension, fsObjType: 0 });
                    }
                });

                for (i in fileList) {
                    if (fileList[i].fsObjType == 0) {
                        totalFiles++;
                    }
                }

                if (totalFiles == 0) {
                    console.log("total files zero");
                    handleDownloadCompleted();
                    return;
                }

                model.setCreationMethod("Blob");
                
                model.addFiles(fileList, function () {
                }, function (file) {
                    currentFile = file;
                    currentFileIndex++;
                    updateProgressNotificationDetails("Processing file " + currentFileIndex + " of " + totalFiles + ": <b>" + getFolderRelativePath(currentFile) + "</b>");
                }, function (current, total) {
                    if (abortingDownload) {
                        updateProgressNotificationDetails("Aborting...");
                        model.abort(handleDownloadAborted);
                        return;
                    }
                    if (currentFile != null) {
                        var zipPercentComplete = ((current / total) * 100).toFixed(2);
                        updateProgressNotificationDetails("Processing file " + currentFileIndex + " of " + totalFiles + ": <b>" + getFolderRelativePath(currentFile) + "</b><br/>Adding to ZIP - " + zipPercentComplete + "%");
                    }
                }, function () {
                    updateProgressNotificationDetails("Finalizing ZIP file...");  
                    model.getBlob(function (blob) {
                    updateProgressNotificationDetails("Initiating download for ZIP file...");
                    console.log("before saveas");
                    saveAs(blob, "files.zip");
                    console.log("after saveas");
                    handleDownloadCompleted(); 
                    });
                }, function () {
                    updateProgressNotificationDetails("Aborting...");
                    model.abort(handleDownloadAborted);
                    console.log("end onabort");
                });
            });
        });
     });`

**Comment by dolare1** [comment]
Please disregard this issue. Thanks!
