### ISSUE TITLE
Internet Explorer 10 (Error in CreateWorker)

### ISSUE THREAD

**Issue by dolare1** [gildas-lormeau/zip.js#167]
Posting this question in a hope that someone can provide suggestions/pointers. Below code works fine in two different environments but not in third environment. All of the environments use IE10. Interestingly it works fine in Chrome in all environments without any code modifications. What are some of the things I need to check?

I get error in the createWorker method of zip.js:

![zipcodecapture](https://cloud.githubusercontent.com/assets/25755364/22940902/137637ba-f2a9-11e6-9c3c-2a208fb27ae6.PNG)

Here's the corresponding output from IE toolbar:

![errorcapture](https://cloud.githubusercontent.com/assets/25755364/22941045/985f7068-f2a9-11e6-94c7-4d49f81c2ee1.PNG)

Here's the workerScriptsPath setting:

![settingscapture](https://cloud.githubusercontent.com/assets/25755364/22941017/7c6ca07e-f2a9-11e6-8891-8c10e99c8919.PNG)

Please let me know if I need to provide any other information.

Thanks!

**Comment by dolare1** [comment]
I have an update. Looks like this is an issue only in Internet Explorer on Windows 10 enterprise. I am using IE toolbar with document mode set to IE10. I will keep you posted.

Thanks!

**Comment by dolare1** [comment]
Upon closely debugging zip.js, I noticed that z-worker.js and deflate.js are displaying different paths. Is that cause for concern even though both of them are in the same folder? Please see the below screenshot. 

z-worker is in /siteassets/multifile-download folder but deflate.js is not being displayed with the same path. How can I verify that deflate.js is being loaded and pulled from the correct folder?

![zipfurthercapture](https://cloud.githubusercontent.com/assets/25755364/22993462/bfea2972-f388-11e6-8b78-513ad63d4a38.PNG)

**Comment by dolare1** [comment]
Any pointers/suggestions?

**Comment by Rob--W** [comment]
Perhaps the path resolving logic is botched?

For the most recent change (so you know where to find the path resolving logic),  seehttps://github.com/gildas-lormeau/zip.js/pull/114/files

**Comment by dolare1** [comment]
Thanks, Rob. I will give it a try. Much appreciated.

**Comment by dolare1** [comment]
Unfortunately, I am getting the same result. Am I supposed to see deflate.js loaded in the network tab of ID developer toolbar? I see zip.js, z-worker.js but not deflate.js. Can you please clarify? I am using webWorkers.

Thank you!

**Comment by dolare1** [comment]
Here's an update:

If I turn off the webWorkers setting, it seems to be working fine, however, I had to manually load deflate.js (see below) into the head of the page using what @Rob--W provided in a different issue thread.

`var s = document.createElement('script');
s.src = '../../../SiteAssets/multifile-download/deflate.js';
document.head.appendChild(s);
`
