### ISSUE TITLE
unable to run this on local

### ISSUE THREAD

**Issue by ManishLSN** [gildas-lormeau/zip.js#169]
hello there,
 I am newbee here and unable to run this project on my local server (wamp), can anyone let me know how can i set up the project and i want to upload files and compress on-the-fly.

**Comment by cameronmoreau** [comment]
Just had the same issue.

On your .html page where you include your `zip.js` file. Under that also include `inflate.js` and `deflate.js` from this project. Then in your script add this line

```
zip.useWebWorkers = false;
```

You can't run it locally because of a CORS issue. This disables that.
