### ISSUE TITLE
Folders without files are not created in the `entries` list

### ISSUE THREAD

**Issue by jarrodek** [gildas-lormeau/zip.js#172]
I have a zip file with following structure:
```
folder A/folder B/
```
And all files are kept in `folder B`. After calling `getEntries` it lists all the files but it missing two entries for both directories. It only shows files.

Current output:
```
folder A/folder B/file 1
folder A/folder B/file 2
folder A/folder B/file 3
folder A/folder B/file 4
```
Expected output:

```
folder A/
folder A/folder B/
folder A/folder B/file 1
folder A/folder B/file 2
folder A/folder B/file 3
folder A/folder B/file 4
```

**Comment by gildas-lormeau** [comment]
zip.js shows the exact structure it finds in the zip file.
