### ISSUE TITLE
Support UTF-8 filename

### ISSUE THREAD

**Issue by danny0838** [gildas-lormeau/zip.js#176]
1. On a OS not using UTF-8 filename en oding, create a zip file by zip.js with a file containing non-ASCII chars.
2. Transfer the file to an OS using UTF-8, and then unzip it.
3. The non-ASCII filenames are garbled.

It would be nice to set the EFS (see [spec](https://www.pkware.com/documents/casestudies/APPNOTE.TXT)) for files added to the zip so that the filename won't be garbled among filesystems using different encodings.

**Comment by greggman** [comment]
Isn't this the same as #131

**Comment by gildas-lormeau** [comment]
duplicate of https://github.com/gildas-lormeau/zip.js/issues/131
