### ISSUE TITLE
unzip the filename not support chinese （解压360压缩的文件名称中文乱码）

### ISSUE THREAD

**Issue by 332140558** [gildas-lormeau/zip.js#181]
unzip the filename not support chinese （解压360压缩的文件名称中文乱码）

**Comment by greggman** [comment]
Isn't this the same as #152 which itself is the same as #131

**Comment by duanyao** [comment]
You have to create zip with UTF-8 file names. It seems 360 doesn't support creating zip with UTF-8: 
http://bbs.360.cn/thread-6400121-1-1.html

**Comment by gildas-lormeau** [comment]
closed as duplicate
