### ISSUE TITLE
Call Stack Exceeded when using zip-fs

### ISSUE THREAD

**Issue by eliphatfs** [gildas-lormeau/zip.js#188]
When calling zip.fs.FS.exportBlob, for each file (I'm using addBlob) that has been added to the fs before, there seem to be one more call to next -> process -> new BlobReader() -> next. And at some two thousand files the stack limit was exceeded, producing an Error.

**Comment by jssuttles** [comment]
Bump. I ran into this today. Is there something that can be done? Maybe some kind of callback hell occurred?

**Comment by jssuttles** [comment]
@gildas-lormeau I'm not sure if you like how I fixed the issue, but I think my PR shows that it's fixable.

**Comment by jssuttles** [comment]
@Rob--W You commented on my other issue, so perhaps you'd like to take a look at this one?

**Comment by Rob--W** [comment]
What specifically should I look into? A test case to reproduce the issue would help.

**Comment by jssuttles** [comment]
https://github.com/gildas-lormeau/zip.js/pull/208 for you @Rob--W

**Comment by gildas-lormeau** [comment]
This issue should be obsolete in the v2
