### ISSUE TITLE
Is it possible to use zip.js with Angular 6

### ISSUE THREAD

**Issue by vhaxha** [gildas-lormeau/zip.js#191]
Hi,

Is it possible to use zip.js with Angular 6 and do you have any example of zip.js working with Angular 6.

Kind regards

**Comment by darrenmothersele** [comment]
Here's how I did it...
https://medium.com/@dazcyril/unzip-files-in-the-browser-with-angular-7-fcdc3040f3c1

**Comment by vhaxha** [comment]
Hi Darren,

Thank you for such brilliant work. We appreciate your hard work.


Kind regards,

Vesel Haxha

________________________________

**Comment by sapeish** [comment]
These are the steps I did to be able to use zip.js in a WebComponent in Angular (without WebWorkers):

1. Install the zip.js module `npm install @lgrignon/zip.js --save`
2. Install the zip.js types `npm install @types/zip.js --save`
3. Add to my project this [ZipExtractor.ts](https://github.com/lgrignon/typescript-zip.js/blob/master/src/modules/ZipExtractor.ts) file (created by @lgrignon)
4. Import the needed files at the top of my ZipExtractor.ts file:
```TS
var zip = require("@lgrignon/zip.js/WebContent/zip.js").zip;
zip.Inflater = require("@lgrignon/zip.js/WebContent/inflate.js").Inflater;
zip.useWebWorkers = false;
```

5. Use the ZipExtractor:
```TS
public async unzipFile(zippedFile: Blob): Promise<ZipContent> {
    let extractor: ZipExtractor = new ZipExtractor();
    let zipContent: ZipContent = await extractor.extract(zippedFile);

    for (let filename of Object.keys(zipContent)) {
        console.info(`ZipExtractor: filename = ${filename}`);
        console.info(`ZipExtractor: content = ${zipContent[filename].content}`);
    }
    return zipContent;
}
```

**Comment by vhaxha** [comment]
Hi Diego,

Thank you so much for your time and help.



Kind regards,

Vesel Haxha

________________________________

**Comment by lgrignon** [comment]
Thanks for all your answers.
@vhaxha can we close this issue?

**Comment by vhaxha** [comment]
Hi Louis,

Yes, please close this issue.



Kind regards,

Vesel Haxha

________________________________

**Comment by lgrignon** [comment]
Actually, since you opened the issue, you are the one able to close it :)

**Comment by mebibou** [comment]
Getting this to work with webworker is not the simplest, but here is what worked for me:
1. Install the module: `npm install @zip.js/zip.js`
2. In your angular.json file, in the `projects.[name].architect.build.options.assets` array, add:
```json
{ "glob": "**/*", "input": "./node_modules/@zip.js/zip.js/dist/", "output": "./zip/" }
```
3. In your `index.html`, add:
```html
<script type="text/javascript" src="zip/zip.js"></script>
```
4. Now you can import the module in your file:
```typescript
const zip = require('@zip.js/zip.js');
zip.configure({
  workerScriptsPath: 'zip/'
});
const blobWriter = new zip.BlobWriter('application/zip');
...
```

**Comment by hosuaby** [comment]
I found the way to import library into Angular application using Ecmascript `import`;

```typescript
import {BlobReader, ZipReader} from 'zip.js';
```

To achieve it, need to add mapping path to `tsconfig.app.json`:

```json
{
  // ...
  "compilerOptions": {
    // ...
    "paths": {
      "zip.js": ["../node_modules/@zip.js/zip.js"]
    }
  },
  // ...
}
```
