### ISSUE TITLE
Unable to Extract the below string

### ISSUE THREAD

**Issue by JenishaDalin** [gildas-lormeau/zip.js#198]
1. Zipped json file was send and saved in filesystem using nodejs.
2.  Sending that data like stream from nodejs
3. Response look like below stream:

![image](https://user-images.githubusercontent.com/45335022/64060171-c801f980-cbe6-11e9-9fb7-ec549eaa4531.png)

How to unzip this zip stream. ?

**Comment by Rob--W** [comment]
Your `response` variable looks like a string. You should read the response as `Blob` instead (or `ArrayBuffer`). Then the zip data can be read using a `BlobReader` (or another custom `Reader` implementation that offers access to the `ArrayBuffer`).

If you use `XMLHttpRequest`, set `responseType` property - https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType
If you use `fetch`, use the `response.blob` or `response.arrayBuffer` methods - https://developer.mozilla.org/en-US/docs/Web/API/Response#Methods
If the data is available via URL, then you could also use a `HttpReader`, for more info see http://gildas-lormeau.github.io/zip.js/core-api.html#zip-reading
