### ISSUE TITLE
no constructor new obj.zip.Inflater() if disabling webworkers

### ISSUE THREAD

**Issue by ensonic** [gildas-lormeau/zip.js#200]
when setting `zip.useWebWorkers = false` we get the above error and indeed
https://github.com/gildas-lormeau/zip.js/blob/master/WebContent/zip.js#L922
does have Inflater() and Deflater().

The reason we've set useWebWorkers = false was that we already use webworkers and with the nested use of WebWorkers we would need to patch
https://github.com/gildas-lormeau/zip.js/blob/master/WebContent/zip.js#L864

**Comment by Rob--W** [comment]
You need to manually import `deflate.js` and/or `inflate.js` with `importScripts` (in a Web Worker) or `<script>` tags (in a web page) if you disable web workers. See https://gildas-lormeau.github.io/zip.js/core-api.html#configuration
