### ISSUE TITLE
Uncaught ReferenceError: zip is not defined

### ISSUE THREAD

**Issue by first100** [gildas-lormeau/zip.js#202]
Hello, i have experienced issue whe import module zip-ext.js at the very beginning in fourth row :
var Reader = zip.Reader; 
the error is:
Uncaught ReferenceError: zip is not defined in Chrome.
i import js in this order:
zip, zip-ext
Can someone help me?

**Comment by atharuddin786** [comment]
problem solved or not I have same issue

**Comment by gildas-lormeau** [comment]
@atharuddin786 This issue is obsolete (` zip-ext.js` does not exist anymore), How did you include zip.js in your project? Could you please share some code?

**Comment by atharuddin786** [comment]
Actually I am using cdn for importing zip.js in my project

**Comment by atharuddin786** [comment]
Your issue is solved or not

**Comment by atharuddin786** [comment]
Can you help??

**Comment by atharuddin786** [comment]
![IMG_20220903_203836_445](https://user-images.githubusercontent.com/70073908/188276742-16586b22-a2ee-4c01-91d4-39a0f1ce255e.jpg)

**Comment by gildas-lormeau** [comment]
I confirm the issue is obsolete and fixed for more than 2 years now.

I also confirm that importing zip.js from a CDN works, see https://jsfiddle.net/dns7pkxt/. This example is taken from the `README`. It imports the library from the deno.land. As an alternative, you can rely on unpkg.com, see https://unpkg.com/@zip.js/zip.js/dist/zip.js.

The code in your screenshot is almost the same as https://github.com/gildas-lormeau/zip.js/blob/gh-pages/demos/demo-read-file.js#L82-L94 which works well, see https://gildas-lormeau.github.io/zip.js/demos/demo-read-file.html.

Unfortunately, your screenshot does not include the import so I won't be able to tell you what could be wrong on your end.

**Comment by atharuddin786** [comment]
Uploading VID20220903233209.mp4…

**Comment by atharuddin786** [comment]
Uploading VID20220903233209.mp4…

**Comment by atharuddin786** [comment]
![Uploading IMG20220903233841.jpg…]()

**Comment by atharuddin786** [comment]
![Uploading IMG20220903233916.jpg…]()

**Comment by atharuddin786** [comment]
![IMG20220903233841](https://user-images.githubusercontent.com/70073908/188283232-56a6b881-d390-4201-a5ee-68c1be9e2ab9.jpg)

**Comment by atharuddin786** [comment]
![IMG20220903233916](https://user-images.githubusercontent.com/70073908/188283305-971a0988-d6b4-4d9a-8775-c8f6a4d78201.jpg)

**Comment by atharuddin786** [comment]
Can I share code with you

**Comment by gildas-lormeau** [comment]
Indeed, if you want help, you have to show some code. These screenshots tell me absolutely nothing, I don't even know what it is.

**Comment by gildas-lormeau** [comment]
So, I confirm https://extract.me/ does not work. You should use the link "Contact us" as the bottom of the page.

**Comment by atharuddin786** [comment]
I have to make like https://extract.me/ this website

**Comment by atharuddin786** [comment]
I have to make like this website https://extract.me/

For practice purpose

**Comment by gildas-lormeau** [comment]
I guess the simplest way to fix your problem is to add this tag in your page:
```html
<script src="https://unpkg.com/@zip.js/zip.js/dist/zip.js"></script>
```

**Comment by gildas-lormeau** [comment]
By the way, if you happen to copy code (like the one in the zip.js demo), don't forget to credit the author of the code.

**Comment by atharuddin786** [comment]
Can I share code you on telegram or any other platform

**Comment by gildas-lormeau** [comment]
I'm sorry, I don't use telegram. You can send me a direct message on twitter if you want.

**Comment by atharuddin786** [comment]
var dots = document.getElementById("dots");
var more = document.getElementById("more");
var btn = document.getElementById("btnMore");

more.style.display = "none";

function otherformates() {
  if (dots.style.display === "none") {
    dots.style.display = "inline";
    more.style.display = "none";
  } else {
    dots.style.display = "none";
    btn.style.display = "none";
    more.style.display = "inline";
  }
}

/* js*/
(() => {
  if (typeof TransformStream == "undefined") {
    const script = document.createElement("script");
    script.src = "lib/web-streams-polyfill.min.js";
    document.body.appendChild(script);
  }
  
  const model = (() => {
  

    return {
      getEntries(file, options) {
        const zipReader = new zip.ZipReader(new zip.BlobReader(file));
        const entries = zipReader.getEntries(options);
        console.log(entries);
      },
      async getURL(entry, options) {
        return URL.createObjectURL(
          await entry.getData(new zip.BlobWriter(), options)
        );
      },
    };
  })();

  (() => {
    const appContainer = document.querySelector(".container");
    const fileInput = document.querySelector(".file-input");
    const fileInputButton = document.querySelector(".btn");
    let fileList = document.getElementById("file-list");

    let entries;
    let selectedFile;

    fileInput.onchange = selectFile;

    appContainer.onclick = downloadFile;
    fileInputButton.onclick = () =>
      fileInput.dispatchEvent(new MouseEvent("click"));

    async function downloadFile(event) {
      const target = event.target;
      let href = target.getAttribute("href");
      if (
        target.dataset.entryIndex !== undefined &&
        !target.download &&
        !href
      ) {
        target.removeAttribute("href");
        event.preventDefault();
        try {
          await download(
            entries[Number(target.dataset.entryIndex)],
            target.parentElement.parentElement,
            target
          );
          href = target.getAttribute("href");
        } catch (error) {
          alert("error", error);
        }
        target.setAttribute("href", href);
      }
    }

    async function selectFile() {
      try {
       
        selectedFile = fileInput.files[0];
        console.log(selectedFile);

        await loadFiles();
      } catch (error) {
        alert(error);
      } finally {
        fileInputButton.disabled = false;
        fileInput.value = "";
      }
    }
    async function loadFiles(zipReader, options) {
      let entries = await zipReader.getEntries(options);
      console.log(entries);
      entries = await Promise.all(
        entries.map(async (entry) => {
          if (entry.filename.toLowerCase().endsWith(".zip")) {
            const innerZipReader = new zip.ZipReader(
              new zip.BlobReader(await entry.getData(new zip.BlobWriter()))
            );
            return loadFiles(innerZipReader, options);
          } else {
            return entry;
          }
        })
      );
      refreshList();
      return entries.flat();
    }
    
    console.log(loadFiles());
    function refreshList() {
      const newFileList = fileList.cloneNode();

      entries.forEach((entry, entryIndex) => {
        const li = document.createElement("li");
        const filenameContainer = document.createElement("span");
        const filename = document.createElement("a");
        filenameContainer.classList.add("filename-container");
        li.appendChild(filenameContainer);
        filename.classList.add("filename");
        filename.dataset.entryIndex = entryIndex;
        filename.textContent = filename.title = entry.filename;
        filename.title = `${
          entry.filename
        }\n  Last modification date: ${entry.lastModDate.toLocaleString()}`;
        if (!entry.directory) {
          filename.href = "";
          filename.title += `\n  Uncompressed size: ${entry.uncompressedSize.toLocaleString()} bytes`;
        }
        filenameContainer.appendChild(filename);
        newFileList.appendChild(li);
      });
      fileList.replaceWith(newFileList);
      fileList = newFileList;
    }

    async function download(entry, li, a) {
      if (!li.classList.contains("busy")) {
        const unzipProgress = document.createElement("progress");
        li.appendChild(unzipProgress);
        const controller = new AbortController();
        const signal = controller.signal;
        const abortButton = document.createElement("button");
        abortButton.onclick = () => controller.abort();
        abortButton.textContent = "✖";
        abortButton.title = "Abort";
        li.querySelector(".filename-container").appendChild(abortButton);
        li.classList.add("busy");
        li.onclick = (event) => event.preventDefault();
        try {
          const blobURL = await model.getURL(entry, {
            password: passwordInput.value,
            onprogress: (index, max) => {
              unzipProgress.value = index;
              unzipProgress.max = max;
            },
            signal,
          });
          a.href = blobURL;
          a.download = entry.filename;
          const clickEvent = new MouseEvent("click");
          a.dispatchEvent(clickEvent);
        } catch (error) {
          if (signal.reason != error) {
            throw error;
          }
        } finally {
          li.classList.remove("busy");
          unzipProgress.remove();
          abortButton.remove();
        }
      }
    }
  })();
})();

**Comment by atharuddin786** [comment]
You can check I have made diffrent Loadfile function

**Comment by gildas-lormeau** [comment]
If you don't want to add the `<script>` tag as I suggested in my previous answer (see https://github.com/gildas-lormeau/zip.js/issues/202#issuecomment-1236182537), then add this to the top of your code:

`js
import * as zip from "https://unpkg.com/@zip.js/zip.js/index.js";
`

**Comment by atharuddin786** [comment]
I have add that script tag in  html page

**Comment by atharuddin786** [comment]
same error is coming

**Comment by gildas-lormeau** [comment]
It should work. Here's an example:

```html
<script src="https://unpkg.com/@zip.js/zip.js/dist/zip.js"></script>
<script>
  console.log(zip);
</script>
```

It displays the content of the `zip` variable as expected.

**Comment by atharuddin786** [comment]
![console](https://user-images.githubusercontent.com/70073908/188285240-692d890a-70d6-4860-99cc-382cd2e7a87f.PNG)
after putting this <script>
  console.log(zip);
</script>

**Comment by atharuddin786** [comment]
File reading is working perfectly

**Comment by gildas-lormeau** [comment]
Great!

**Comment by atharuddin786** [comment]
but 
![getEntries](https://user-images.githubusercontent.com/70073908/188285318-4472e891-f01c-4443-bb57-2f73fe8a3da2.PNG)

**Comment by atharuddin786** [comment]
plz help what I have used to loadFiles

**Comment by gildas-lormeau** [comment]
You copied my code and broke it. I'm sorry but, I won't fix the bugs you introduced... The function `loadFiles` requires the first parameter to be defined. So, it means that you have to replace ```loadFiles()``` with ```loadFiles(new zip.ZipReader(new zip.BlobReader(file))```.

**Comment by atharuddin786** [comment]
actually I have looking  zip.js or treejs for zip file reader then your library is comming out in google search

**Comment by atharuddin786** [comment]
plz help me bro

**Comment by atharuddin786** [comment]
got frustrated with this error

**Comment by gildas-lormeau** [comment]
I already answered you! Replace ```loadFiles()``` with ```loadFiles(new zip.ZipReader(new zip.BlobReader(file))```. In order to use zip.js, you have to know how to program in JavaScript. Please read the following pages before contacting me.

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/, in particular https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function
- https://developer.chrome.com/docs/devtools/javascript/

**Comment by atharuddin786** [comment]
loadFiles(new zip.ZipReader(new zip.BlobReader(file))
 it is showing an error

**Comment by gildas-lormeau** [comment]
And this article as well: http://testthewebforward.org/docs/bugs.html. Thanks!
