### ISSUE TITLE
Large file causes "Error while reading zip file" on browser

### ISSUE THREAD

**Issue by koray1396** [gildas-lormeau/zip.js#204]
When trying to read a zip file in Chrome, it produces "Error while reading zip file". This happens for files over 6 gb. I'm just reading filenames like this in Angular.

    this.zip.createReader(new this.zip.BlobReader(file), reader => {
        reader.getEntries(entries => {
          observer.next(entries.map(x => x.filename));
          observer.complete();
        });
      });

Thanks again.

**Comment by duanyao** [comment]
Is it a zip64 file? zip64 is not supported yet, see #180 .

**Comment by koray1396** [comment]
Yes, sorry I missed that. Closing this.

**Comment by AurelienMendes** [comment]
Hi,  even if this issue is closed I would like to know if someone knows a way to deal with this kind of large zip files (just to read their entries) ?
