### ISSUE TITLE
Extra fields while unzipping and zipping

### ISSUE THREAD

**Issue by jssuttles** [gildas-lormeau/zip.js#207]
Is there a way that this module can read extra fields and reappend them? I see that it's skipping it in zipReader.getEntries. It reads the filename and then skips it to read the comment. I'm currently using this module to read a zip that contains a .app and then write a zip with that same .app inside. (In case you don't have a Mac, .app is the extension of a Mac application. It's basically a folder with a specific structure. There are executables nested somewhere inside.) When reading the zip, it ignores the extra fields. So, definitely, when writing them, it won't be able to maintain those extra fields. This is particularly frustrating in my case because the executables have their permissions stripped. I've been trying to decipher the unix extra fields, but it might be nice to just pass them along to the calling function, so that they can be tacked on when the file is being written again.

**Comment by Rob--W** [comment]
The zip.js's source code shows that the extra field information is not being read and not processed either. If you want to add the data, you can fork the library. If you want to be in sync with upstream, then you can submit a PR and I'll review it.

Here are some implementation details to get you started:

Reading:
- Reading size of extra fields: https://github.com/gildas-lormeau/zip.js/blob/3e7920810f63d5057ef6028833243105521da369/WebContent/zip.js#L554
- Skipping over extra fields when reading content: https://github.com/gildas-lormeau/zip.js/blob/3e7920810f63d5057ef6028833243105521da369/WebContent/zip.js#L596
- Skipping over extra fields when extracting metadata: https://github.com/gildas-lormeau/zip.js/blob/3e7920810f63d5057ef6028833243105521da369/WebContent/zip.js#L670-L674

Writing:
- Writing the header, with extra field size of zero: https://github.com/gildas-lormeau/zip.js/blob/3e7920810f63d5057ef6028833243105521da369/WebContent/zip.js#L741-L756
- Writing more metadata, without extra field: https://github.com/gildas-lormeau/zip.js/blob/3e7920810f63d5057ef6028833243105521da369/WebContent/zip.js#L757-L761

**Comment by jssuttles** [comment]
What is the following doing? Why does it not skip over the commentLength? Does the common header not include the commentLength?
https://github.com/gildas-lormeau/zip.js/blob/3e7920810f63d5057ef6028833243105521da369/WebContent/zip.js#L596

**Comment by Rob--W** [comment]
The header for a file entry does not have a comment, see https://en.wikipedia.org/wiki/Zip_(file_format)#Local_file_header

Only the central directory record has a comment: https://en.wikipedia.org/wiki/Zip_(file_format)#Local_file_header

**Comment by jssuttles** [comment]
I see. Thanks.

**Comment by jssuttles** [comment]
I'm unable to come to a usable solution on this because I don't understand extra fields enough to be able to understand why when I move it from the unzipped file to the zipped file it does not work.
The documentation from other projects doesn't seem to clear it up either.
```
 * TTTTsstrwxrwxrwx0000000000ADVSHR
 * ^^^^____________________________ file type, see zipinfo.c (UNX_*)
 *     ^^^_________________________ setuid, setgid, sticky
 *        ^^^^^^^^^________________ permissions
 *                 ^^^^^^^^^^______ not used ?
 *                           ^^^^^^ DOS attribute bits : Archive, Directory, Volume label, System file, Hidden, Read only
```

**Comment by Rob--W** [comment]
See section 4.5 "Extensible data fields" of the zip specification at https://pkware.cachefly.net/webdocs/APPNOTE/APPNOTE-6.3.6.TXT

**Comment by gildas-lormeau** [comment]
I'm closing the issue because extra fields are supported today. There are used for encryption and zip64, for example.
