### ISSUE TITLE
HttpReader silently inserting HTTP errors into ZIPs

### ISSUE THREAD

**Issue by bgaspic** [gildas-lormeau/zip.js#211]
When a HTTP response returns a 4xx / 5xx code, `HttpReader` will relay the "error body response" to the `zipWriter`
-- as if everything were fine -- _silently_ writing that error text into the ZIP instead of the desired document.

This is not the behaviour that any library client would expect.

It stems from how `HttpReader.getData()` is written. It forwards only the `XmlHttpRequest:error` events to `onerror`,
whereas problematic HTTP status codes make it into the `XmlHttpRequest:load`, which itself never checks for the said status.

I've provisorily added the 2nd and 3rd line in this block into my copy of the `zip-ext.js`, after which the library behaves as expected

```
    request.addEventListener("load", function() {
        if (request.status >= 300) // Errors are 400+, but 3xx redirections (incl. "304 Not Modified") aren't handled yet either
            return onerror('HTTP Status ' + request.status + ' ' + request.statusText);
        if (!that.size)
        ...
```
Please consider which solution you'd deem fully appropriate.

**Comment by bgaspic** [comment]
If the request above (with a possible solution already provided) does calrify adequately what the problem is,
perhaps this code snippet will. (it's ready to run if placed in a <script> that includes zip.js and zip-ext.js)

```
const FILEURL  = "https://upload.wikimedia.org/wikipedia/commons/NO_SUCH_FILE_HERE.jpg";
const FILENAME = "badcontent.jpg";
const ZIPNAME  = "badcontent.zip";

zip.createWriter(
	new zip.BlobWriter("application/zip"),
	function(zipWriter) {
		zipWriter.add(FILENAME, new zip.HttpReader(FILEURL), function() {
			console.error('A BAD FILE HAS JUST BEEN WRITTEN INTO THE ZIP');
			zipWriter.close(function (zippedBlob) {
				const a = document.createElement('a');
				a.download = ZIPNAME;
				a.rel = 'noopener';
				a.href = URL.createObjectURL(zippedBlob);
				setTimeout(function () {
					a.click();
					setTimeout(function () { URL.revokeObjectURL(a.href) }, 120);
				}, 0);
	})})},
	function(errormsg) {
		console.error('I AM NOT BEING CALLED FOR THIS!');
	}
);
```

This will save a badcontent.zip containing a badcontent.jpg whose literal content will be:
`Regexp failed to match URI: "/wikipedia/commons/NO_SUCH_FILE_HERE.jpg"`

Expected result: the onerror stub being called...

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. It's fixed now.
