### ISSUE TITLE
using with webpack

### ISSUE THREAD

**Issue by rrrepos** [gildas-lormeau/zip.js#212]
I have been able to use zip.js by downloading the z-worker.js, inflate.js, deflate.js and placing them in the app directory and calling them from the html page. It works well.

The rest of the project has a single bundle using webpack. However, when I try to import the inflate.js or z-worker.js from the source, it gives a run time error. My guess being that during run time it tries to load these files.

What would be the best option to bundle it with webpack? Thanks

**Comment by johnmarinelli** [comment]
i'm having the same problem.  the docs are very unclear as far as how to use this package with es6 imports

**Comment by gildas-lormeau** [comment]
@rrrepos Right now, I use rollup to bundle the library. I'll try to do some tests with webpack and see how it supports Web Workers. If you really want to have only one file, you can do this today by setting `useWebWorkers` to `false` and concatenating `inflate.js` and `deflate.js` to your bundle. This will have an impact of performances if you try to unzip/zip multiple files in parallel though.

@johnmarinelli That's because I did not have the time to test and document it yet.

**Comment by johnmarinelli** [comment]
@gildas-lormeau that's fair, i can take a look over the weekend to see if i can break some ground on this issue

**Comment by gildas-lormeau** [comment]
@johnmarinelli thank you!

**Comment by rrrepos** [comment]
@gildas-lormeau : Thanks for the immediate response. I tried:

```
const zip = require("./zip.min.js");
import "./inflate.js";
import "./deflate.js";
zip.configure({
    useWebWorkers: false
});
```
While loading a zip it gives a runtime error: `ZipInflate is not defined`. Do I need to import with some functions or default? Thanks

```

**Comment by gildas-lormeau** [comment]
@rrrepos You cannot import these scripts because they aren't es6 modules currently. You just need to include them in your bundle.

**Comment by rrrepos** [comment]
Thanks @gildas-lormeau . This is what I have revised to:
```js
// app.js in src
const zip = require("./zip.min.js");

zip.configure({
    useWebWorkers: false
});
```

The following is the webpackconfig.js
```js
 ...
  entry : {
   "dist/app.js": ["src/app.min.js", "src/inflate.js", "src/deflate.js"]
  ...
 }
...
```
The zip dist files viz. zip.min.js, z-worker.js, inflate.js, deflate.js as well as app.js ( my custom js) are in the `src` directory

The bundle is getting successfully generated. Yet I still see a `ZipInflate is not defined` error when loading a zip file. Wondering what am I missing! Thanks

**Comment by gildas-lormeau** [comment]
I guess you might need to use the loader `raw-loader`, see https://webpack.js.org/loaders/raw-loader/. The problem is that I don't know how to make it work.

**Comment by rrrepos** [comment]
okay. Let me figure it out. If I can work it out, then will update it here. Thanks

**Comment by gildas-lormeau** [comment]
@rrrepos I updated the build script and the code in order to include `deflate.js` and `inflate.js` in `zip.min.js` in the v2.0.12. Your problem should now be fixed with `useWebWorkers` set to `false`.

**Comment by rrrepos** [comment]
Wonderful @gildas-lormeau . Lemme check and thanks for this. Much appreciated

**Comment by rrrepos** [comment]
Works @gildas-lormeau  

I tried 
1. By downloading the `zip.min.js` in the required directory, and
2. By installing the npm.
Both work.
```
// app.js in src
const zip = require("./zip.min.js");

zip.configure({
    useWebWorkers: false
});
```
```
// app.js in src
const zip = require(".,/node_modules/@zip.js/zip.js/dist/zip.min.js");

zip.configure({
    useWebWorkers: false
});
```
Thanks. I will close the issue now.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback!

**Comment by 101arrowz** [comment]
I've faced this exact same problem before with my own compression library [fflate](https://github.com/101arrowz/fflate) - it seems difficult to support different bundlers and environments when using web workers. I found an interesting solution that generates a worker from a Blob URL, which is in turn created by a source code string, which is dynamically generated at runtime using clever tricks such as `Function.prototype.toString()`. If you're interested in supporting this use case let me know @gildas-lormeau - you can check [this repo](https://github.com/101arrowz/isoworker) for extra info.

**Comment by gildas-lormeau** [comment]
@101arrowz what you described is hopefully what I will implement soon. It tried [rollup-plugin-web-worker-loader](https://www.npmjs.com/package/rollup-plugin-web-worker-loader) but I was not able to make it work. I might code a plugin for rollup or something else of necessary.

**Comment by 101arrowz** [comment]
The library I linked is actually a runtime library, not a compile-time plugin for build tooling. The main idea was actually to prevent the need for a build tool plugin or any other configuration for web workers to function properly, which is why I suggested it. If you're planning to write a plugin, that would probably be useful too but consumers need to take an extra step as opposed to the approach I mentioned. Plus, one fewer network request - all the code for both the worker and the main-thread stuff can be bundled into a single file. Though I totally understand if the lack of browser support makes it unfeasible.

**Comment by gildas-lormeau** [comment]
@101arrowz Sorry, I somehow missed totally the link in your previous post. I've just taken a look at 
isoworker. It's an interesting approach but, on my end, I would like to use as much as I can standard APIs in the code and not rely on external modules. Ideally, I would like to have the same code than today but, once built, the web worker code would be embedded as a string. This string would be transformed into a Blob URI with code executed in runtime. `rollup-plugin-web-worker-loader` is almost okay but it generates a data URI in base 64 to embed the code of the web worker.

**Comment by gildas-lormeau** [comment]
I just released the version 2.2.0. Now, the web worker script is embedded into the library (as a string) so it makes obsolete the setting `workerScriptsPath` an dthe need to copy `z-worker.js`.
@rrreposthat means should be able to set `useWebWorkers` to `true` if you update the module
@101arrowz if you're curious on how I did, see https://github.com/gildas-lormeau/zip.js/blob/master/rollup-inline-worker.config.js

**Comment by rrrepos** [comment]
@gildas-lormeau : Thanks for the update.

I seem to be getting a ` can't resolve 'url' in ...` error while compiling in webpack. I tried two methods both resulting in the same.

1. Using latest npm: ` "@zip.js/zip.js": "2.2.1"` and using `const zip = require(..{path to node_modules}..);`
2. Downloading the zip.min.js from your dist directory and using `const zip = require('./zip.min.js);` from in the src directory.

And again by reverting to 2.0.12 the webpack compilation is successful.

Perhaps will await someone else trying out the latest version, just in case some mistake I am making.

**Comment by gildas-lormeau** [comment]
@rrrepos  That's weird. Unfortunately, I don't have enough information do understand what's going on.

I did a test and I confirm I cannot reproduce your issue. On my end, Webpack bundles `zip.js` in the application and the application runs as expected.  FYI, I attached the project to this issue. Feel free to test it or tell me the differences with yours.

[zip.js-demo.zip](https://github.com/gildas-lormeau/zip.js/files/5872793/zip.js-demo.zip)

**Comment by gildas-lormeau** [comment]
>     1. const zip = require(..{path to node_modules}..);

I guess this might be the cause of your issue, you should write `require('@zip.js/zip.js');`

**Comment by gildas-lormeau** [comment]
Here is the same project. The only difference is that it uses `require` instead of `import`. It runs fine as well.

[zip.js-demo-require.zip](https://github.com/gildas-lormeau/zip.js/files/5872997/zip.js-demo-require.zip)

**Comment by rrrepos** [comment]
@gildas-lormeau . This works! ... thanks. Yes, similar to your demo app I imported the required functions and used them. They work very well. Superb. Thanks!

**Comment by gildas-lormeau** [comment]
@rrrepos I'm glad to hear it :) Thank you for the feedback!

**Comment by johnmarinelli** [comment]
@rrrepos how did you get it to work with webpack?  i am getting this error:

```
ERROR in ./node_modules/@zip.js/zip.js/lib/core/codecs/codec-pool.js 112:70
    Module parse failed: Unexpected token (112:70)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    |   let task;
    |   if (!workerData.interface) {
    >           workerData.worker = new Worker(new URL(workerData.scripts[0], import.meta.url));
```

looking at the outputted source it seems like the output of the inlined worker script is interpolated via string into an IIFE, no idea how webpack would handle this

**Comment by johnmarinelli** [comment]
@gildas-lormeau i was trying the rollup web worker loader with some success, however it seems like the current structure of the code would need to be changed to use it correctly, i can keep trying but it's difficult to avoid merge conflicts with the constant updates

**Comment by rrrepos** [comment]
The following are my settings:

```
// package.json
{
  ...
  "dependencies": {
    ...
    "@zip.js/zip.js": "2.2.1"
 }
...
}
```
Then in my source code
```
import { BlobReader, BlobWriter, ZipWriter, ZipReader, TextWriter, TextReader, Uint8ArrayReader, Uint8ArrayWriter, configure } from "@zip.js/zip.js";

configure({useWebWorkers: true});
..
...
// to open a file when sending a file object (blob)
// this._password has password provided by user in case file uses password
//
 ...
 this._zip = new ZipReader(new BlobReader(fileobj), {password: this._password});
 ...

// and to save
 const _blobWriter = new BlobWriter("application/zip");
 this._zip = new ZipWriter(_blobWriter, {password: this._password});
...
// this is followed by adding conentt
// in my case content has been stored as buffer array
// and hence I am using the Uint8  
 await this._zip.add(_component.data.content, new Uint8ArrayReader(_component.data.arraybuffer));
...
```

Hope this helps. The example provided by @gildas-lormeau helped.

**Comment by johnmarinelli** [comment]
@rrrepos so no webpack?

**Comment by gildas-lormeau** [comment]
@johnmarinelli Please take a look in the zip here: https://github.com/gildas-lormeau/zip.js/issues/212#issuecomment-767481550. It is a complete example on how to use zip.js with webpack.

**Comment by junkkerrigan** [comment]
@johnmarinelli I did manage to bundle my code that utilizes `zip.js` with Webpack 4 (Webpack [added](https://github.com/webpack/webpack/issues/6719#issuecomment-662426535) support for `import.meta` in `v5.0.0-beta.21`) when replaced `import`ing from package with `require`ing from specific file. E.g.
```javascript
// doesn't bundle
import { HttpReader, ZipReader, Data64URIWriter } from '@zip.js/zip.js'

// bundles 
const { HttpReader, ZipReader, Data64URIWriter } = require('@zip.js/zip.js/dist/zip-full');
```

**Comment by rrrepos** [comment]
> @rrrepos so no webpack? i've ran the example and it doesn't help.

Of course, webpack is used

```
...
  entry : {
   "dist/app.min.js": ["src/app.js"]
  ...
 }
```

**Comment by gildas-lormeau** [comment]
> @gildas-lormeau is the way I use the lib here correct? (i.e. `require('@zip.js/zip.js/dist/zip-full')`)

I think it's okay. It's surprising though that you have to import "zip-full". Doesn't it work if you write  `require('@zip.js/zip.js')` instead?

**Comment by junkkerrigan** [comment]
Looks like my internal radar felt something would be wrong if I'll `require('@zip.js/zip.js')` 🙂 
I tested this now - and nope, it doesn't work - produces the same old error either.
```
Module parse failed: Unexpected token (112:70)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 	let task;
| 	if (!workerData.interface) {
> 		workerData.worker = new Worker(new URL(workerData.scripts[0], import.meta.url));
| 		workerData.worker.addEventListener(MESSAGE_EVENT_TYPE, onMessage, false);
| 		workerData.interface = {
 @ ../node_modules/@zip.js/zip.js/lib/core/zip-writer.js 59:0-68 341:22-33 342:14-27
 @ ../node_modules/@zip.js/zip.js/lib/core/zip-core.js
 @ ../node_modules/@zip.js/zip.js/index.js
```

**Comment by gildas-lormeau** [comment]
@junkkerrigan Thank you for the feedback. I wasn't aware of this bug in Webpack 4. Out of curiosity, did you try to use this loader https://www.npmjs.com/package/@open-wc/webpack-import-meta-loader?

**Comment by gildas-lormeau** [comment]
So, I just did a test and I confirm zip.js can be bundled with webpack 4 by using the loader https://www.npmjs.com/package/@open-wc/webpack-import-meta-loader installed. See the attached zip.

[zip.js-demo-webpack4.zip](https://github.com/gildas-lormeau/zip.js/files/5893699/zip.js-demo-webpack4.zip)

**Comment by junkkerrigan** [comment]
@gildas-lormeau thx, didn't figure out to look for a loader for this `import.meta` thingie.
Unfortunately, I use kinda wrapper on top of webpack that doesn't allow to integrate extra loaders, so if there're no objections against `require('@zip.js/zip.js/dist/zip-full')` way - I'll continue with it.

**Comment by gildas-lormeau** [comment]
@junkkerrigan No problem, that's fine too :)

**Comment by johnmarinelli** [comment]
it works now, thank you @gildas-lormeau @junkkerrigan

**Comment by gildas-lormeau** [comment]
Glad to hear it @johnmarinelli!

**Comment by Gedux-lt** [comment]
I have issue on prod build. Works correctly in dev build. Have you any idea? 

![image](https://user-images.githubusercontent.com/13381637/106534509-ec10eb00-64fc-11eb-8a3e-ce3534bed57a.png)

**Comment by gildas-lormeau** [comment]
@Gedux-lt I added `mode: 'production',` in the `webpack.config.js` file of the project I posted here https://github.com/gildas-lormeau/zip.js/issues/212#issuecomment-767454269. I was not able to reproduce the issue. Do you confirm you're using webpack 5?
if that's the case, could you beautify the minified JS code with a tool like https://beautifier.io/ after it is built, take a screenshot of the stack trace and maybe also each corresponding line in the code?

**Comment by Gedux-lt** [comment]
> @Gedux-lt I added `mode: 'production',` in the `webpack.config.js` file of the project I posted here [#212 (comment)](https://github.com/gildas-lormeau/zip.js/issues/212#issuecomment-767454269). I was not able to reproduce the issue. Do you confirm you're using webpack 5?
> if that's the case, could you beautify the minified JS code with a tool like https://beautifier.io/ after it is built, take a screenshot of the stack trace and maybe also each corresponding line in the code? Edit: you can also simply take a screenshot of the error (with "pause on exceptions" enabled) and pretty print the code in the debugger.

Thank you for your fast response. No it was webpack 4. I updated to webpack 5 and now zipjs works correctly!

**Comment by AFlowOfCode** [comment]
The installation instructions are woefully incomplete without some sort of note about this obscure detour required for a common usage scenario

**Comment by gildas-lormeau** [comment]
I'm sorry but webpack 4 is obsolete...

**Comment by AFlowOfCode** [comment]
Totally. But then again you might be amazed how many projects aren't doing major version upgrades within the first 5 months of a new release 🙄 Plus time was already spent documenting the workaround here, never know how far a simple "works with webpacker >= 5 without [this](https://www.npmjs.com/package/@open-wc/webpack-import-meta-loader)" note or a link to this issue might go. That's just my theory about installation instructions though!

**Comment by gildas-lormeau** [comment]
Note that it's already documented here too: https://github.com/gildas-lormeau/zip.js/discussions/229

**Comment by JJ** [comment]
This kind of error also shows up if you try to test with cypress, since it uses webpack by default. Configuring webpack from cypress in the way you suggest might not be trivial, but I will give it a try.
