### ISSUE TITLE
"Read a zip file" demo doesn't work with a password-protected archive

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/zip.js#213]
1. Navigate to the "Read a zip file" demo on the zip.js webpage, https://gildas-lormeau.github.io/zip.js/demos/demo-read-file.html.
2. Click on "Open..." and upload this archive: [test.zip](https://github.com/gildas-lormeau/zip.js/files/5865176/test.zip) (includes files [1.txt](https://github.com/gildas-lormeau/zip.js/files/5865126/1.txt), [2.txt](https://github.com/gildas-lormeau/zip.js/files/5865127/2.txt)). 
The archive was created with the command `7z.exe a -p123 test.zip 1.txt 2.txt`, 7z.exe from the [7-Zip 19.00 (2019-02-21) for Windows 32-bit x86 Installer](https://www.7-zip.org/a/7z1900.exe).
3. Type `123` in the "set the password" field.
4. Click on either "1.txt" or "2.txt" in the "download uncompressed files" field. A window alert saying "Error: Invalid pasword" pops up.

**Comment by gildas-lormeau** [comment]
ZipCrypto is not supported. You have to select AES-256 instead to encrypt your zip file.

**Comment by lkintact** [comment]
I see, thanks. The issue can be closed, I guess.

**Comment by gildas-lormeau** [comment]
Thank you, I'm closing the isssue because I do not plan to implement ZipCrypto which is notoriously known to be insecure.

**Comment by lkintact** [comment]
>Edit: it looks like you have to pass -mem=AES256 when creating the zip file.

Yes, thanks, that's the switch -- I was just experimenting with zip encryption methods supported by 7-Zip, and looks like AES128 and AES192 aren't supported by zip.js either, as well as ZipCrypto. Is this intentional?

**Comment by gildas-lormeau** [comment]
I plan to integrate AES-128 and AES-192 encryption because it should just be a matter a changing some parameters.

**Comment by gildas-lormeau** [comment]
@lkintact the support of AES-128 and AES-192 has been added in the version2.2.1. AES-192 is not supported in Chrome though

**Comment by lkintact** [comment]
@gildas-lormeau Thanks, just tried the demo with AES-128 and AES-192 encrypted archives created with 7-Zip, both worked.
