### ISSUE TITLE
Running zip.js inside a service worker script

### ISSUE THREAD

**Issue by jonknapp** [gildas-lormeau/zip.js#216]
I am downloading a zip file behind the scenes in a service worker and I'd like to unzip and cache the contents there if possible. I was wondering if there's a recommended way to run the library inside of a service worker? I can include a pre-built `dist/` file with:

```
importScripts('zip.min.js');

zip.configure({
  webWorkers: false
});
```

However, it looks like `URL.createObjectURL` removed blob support inside of service workers for security concerns.

If this is not a use-case that's not supported, feel free to close it out. I have been trying to get things running a few different ways and have been failing. Thanks for the library!

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. It's fixed in the version 2.2.6 I just published. I did a test and I also confirm zip.js can run in a service worker. Note that you have to import 'zip-full.min.js' instead of 'zip.min.js' (because web workers are disabled) and the related option is `useWebWorkers` instead of `webWorkers`.

**Comment by jonknapp** [comment]
You are amazing. Thank you for the fast response!

**Comment by gildas-lormeau** [comment]
You're welcome!

**Comment by gildas-lormeau** [comment]
@jonknapp FYI, I coded a small test with a service worker which detects fetched URLs ending with `.zip#<filename>` and returns the entry matching `<filename>`.

- main script:
https://github.com/gildas-lormeau/zip.js/blob/01d88f96568c0ff78721092db947a2e21ad8e9d3/tests/pages/test-sw.js

-service worker script:
https://github.com/gildas-lormeau/zip.js/blob/01d88f96568c0ff78721092db947a2e21ad8e9d3/tests/pages/test-sw-worker.js

**Comment by jonknapp** [comment]
That's awesome. I checked it out for my project earlier today and it worked perfectly. Thank you again for such a fast turn around.

**Comment by gildas-lormeau** [comment]
That could be improved by coding an  `HTTPRangeReader` class using `fetch` under the hood though. Thus, zip.js would not need to download the whole file in order to extract an entry.
