### ISSUE TITLE
NPM library not working in Angular

### ISSUE THREAD

**Issue by janesenaj** [gildas-lormeau/zip.js#217]
Used Angular 10 with `@zip.js/zip.js@2.0.12` and tested using the sample code:

```
// - create the inputBlob object storing the data to compress
const inputBlob = new Blob(
  ["Lorem ipsum dolor sit amet, consectetuer adipiscing elit..."], 
  { type: "text/plain" });

// - create a Data64URIWriter object to write the zipped data into a data URI
// - create a ZipWriter object with the Data64URIWriter object as parameter
const zipWriter = new zip.ZipWriter(new zip.Data64URIWriter("application/zip"));

// - create a BlobReader object to read the content of inputBlob
// - add a new file named "text.txt" in the zip and associate it to the BlobReader object
await zipWriter.add("test.txt", new zip.BlobReader(inputBlob));

// - close the ZipWriter object and get compressed data
const dataURI = await zipWriter.close();
// - log compressed data
console.log(dataURI);
// data:application/zip;base64,UEsDBBQACAgIAJuFO1IAAAAAAAAAAAAAAAAIAAAAdGVzdC50e...


// - create a Data64URIReader object with the zipped content 
// - create a ZipReader object to read the zipped data
const zipReader = new zip.ZipReader(new zip.Data64URIReader(dataURI));

// - get entries from the zip file
const entries = await zipReader.getEntries();

// - use a TextWriter object to write the unzipped data of the first entry into a string
const data = await entries[0].getData(new zip.TextWriter());
// - close the ZipReader object
await zipReader.close();

// - log data
console.log(data);
// Lorem ipsum dolor sit amet, consectetuer adipiscing elit...
```

The code hangs at `await zipWriter.add("test.txt", new zip.BlobReader(inputBlob));` it doesn't throw any errors, nor does it proceed to print the data at `console.log(data)`.

However, the sample code works if the raw code was used instead (i.e. `zip.min.js` from [github](https://github.com/gildas-lormeau/zip.js/tree/master/dist)) and `<script type="text/javascript" src="assets/zip.min.js"></script>` was added to `index.html`.

Had reference #191 but the solutions there don't seem to work for me.

**Comment by gildas-lormeau** [comment]
The way web workers are loaded changed in the latest versions of zip.js. Could you please try to do the same test with the version 2.2.8?

**Comment by janesenaj** [comment]
Not using custom webpack to build the project, so the latest version 2.2.8 gives the import.meta error.

**Comment by gildas-lormeau** [comment]
If I'm not wrong Angular is using webpack 4 under the hood. If that's the case, you might need to add an additional loader, see https://github.com/gildas-lormeau/zip.js/issues/212#issuecomment-769766135.

**Comment by mebibou** [comment]
@janesenaj I got it working with the latest version and edited [my comment](https://github.com/gildas-lormeau/zip.js/issues/191#issuecomment-763650835)

**Comment by gildas-lormeau** [comment]
@mebibou Thank you for the information, what did you do to make it work?

**Comment by mebibou** [comment]
@gildas-lormeau you can see it in my comment above

**Comment by gildas-lormeau** [comment]
@mebibou Thank you! I was checking the wrong issue

**Comment by gildas-lormeau** [comment]
I pasted below your fix.

1. Install the custom webpack builder: `npm install -D @angular-builders/custom-webpack`
2. Install the plugin to load metadata: `npm install -D @open-wc/webpack-import-meta-loader`
3. Edit your `angular.json` file:
```json
"architect": {
      "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./custom-webpack.config.js"
            },
  ...
      "serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
  ...
```
4. Add a `custom-webpack.config.js` with the following content:
```javascript
const webpack = require('webpack');

module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: require.resolve('@open-wc/webpack-import-meta-loader')
      }
    ]
  }
};

```

**Comment by gildas-lormeau** [comment]
I'm closing the issue. I added a response here: https://github.com/gildas-lormeau/zip.js/discussions/229
