### ISSUE TITLE
TypeError: zip.createWriter is not a function

### ISSUE THREAD

**Issue by kas2ri** [gildas-lormeau/zip.js#220]
Unhandled rejection ClientPrintJob.prototype._genPFGArrayAsync/<@http://127.0.0.1:8000/js/JSPrintManager.js:164:25

Sir, what kind of error is this?

**Comment by gildas-lormeau** [comment]
I guess you're trying to update zip.js in [this project](https://github.com/neodynamic/JSPrintManager). Unfortunately, the version 2.x of zip.js is not compatible with the previous version. It means you need to apply also some changes in the code of JSPrintManager.

**Comment by kas2ri** [comment]
thankyou sir its working

**Comment by gildas-lormeau** [comment]
Glad to hear it!

**Comment by Irykson** [comment]
Just to let you know, JSPrintManager got updated to support version 2.x!

**Comment by gildas-lormeau** [comment]
Great, I'm glad to hear it :)
