### ISSUE TITLE
Unzipping seems to break in Firefox

### ISSUE THREAD

**Issue by Akrabut** [gildas-lormeau/zip.js#222]
I go to the same (private) URL then fetch the same (zipped) data.

On Chrome everything works as expected.
On Firefox however, unzipping breaks with `Error: File format is not recognized`, originated in `dist/zip-full.js` line 5830.

When inspecting the `HttpReader` instance, this is how it looks in Chrome:

```
{
  "url": "some-url.zip",
  "reader": {
    "size": 680054,
    "url": "some-url.zip",
    "options": {},
    "initialized": true,
    "data": {
     lots of data   
    }
  },
  "initialized": true
}
```

In Firefox there seems to be no `data` and thus no `size`:

```
{
  "url": "some-url.zip",
  "reader": {
    "size": 0,
    "url": "some-url.zip",
    "options": {},
    "initialized": true
  },
  "initialized": true
}
```

I'm using the latest version.
Any ideas?

**Comment by gildas-lormeau** [comment]
When you open the network tab, do you see the request and the response of `some-url.zip`? Is there any HTTP error?

**Comment by Akrabut** [comment]
It looks like there are only relevant `HEAD` requests in Firefox, compared to `HEAD` and `GET` in Chrome.

**Comment by gildas-lormeau** [comment]
Is there any difference in the response of the `HEAD` requests?

**Comment by gildas-lormeau** [comment]
BTW, note that the [tests](https://github.com/gildas-lormeau/zip.js/tree/master/tests) related to `HttpReader` works well in Firefox.

**Comment by gildas-lormeau** [comment]
@Akrabut Were you able to identify the cause of the issue?

**Comment by Akrabut** [comment]
Hi, was AFK for a few days.
The issue has been fixed by

```
const zipReader = new ZipReader(
    new HttpReader(archiveURL, { preventHeadRequest: true }),
  );
```

If you don't think that's an appropriate solution for the general use case (it is in my case), I'll be happy to check if there's a difference in the `HEAD` requests.

**Comment by gildas-lormeau** [comment]
Well, that will indeed fix the issue without any particular downside and long as you don't plan to set `useRangeHeader` to `true`. However, this does not tell me what the cause of the issue was unfortunately. What HTTP server/App server are you using? Maybe I could try to reproduce it.

**Comment by Akrabut** [comment]
The server I'm accessing wont be reachable for you.
I'll try to get to it and provide more info as soon as I can, hopefully in the next few days.

**Comment by Akrabut** [comment]
Unfortunately I didn't have the time to debug it yet but I didn't forget to do so 😄 
If you prefer that I reopen the issue when I have the time to debug it feel free to close it.

**Comment by gildas-lormeau** [comment]
Thank you for the update. We can keep the issue open. Maybe someone else will be able to reproduce it and provide some info meanwhile.

**Comment by Akrabut** [comment]
Looks like its fixed and cant be reproduced anymore going from Firefox version 86.0.1 to 87.0.0.

**Comment by gildas-lormeau** [comment]
@Akrabut Thank you very much for the feedback! I'm closing the issue. Feel free to reopen it or comment it if necessary.
