### ISSUE TITLE
Can we zip folders now?

### ISSUE THREAD

**Issue by av01d** [gildas-lormeau/zip.js#226]
Great to see that this lib is being worked on again.
I am the developer of files2zip.com, and have already integrated the new zip.js there.
Now I'm wondering: does zip.js support deflating folders?
In Chrome, you can drag folders onto a window/DOM element, and access the contents of that folder.
It would be great to be able to deflate a dragged folder.
Is this possible with zip.js? Is there a demo or test available maybe? Any pointers if not?
Thanks!

**Comment by gildas-lormeau** [comment]
It's possible with the filesystem API thanks to the method `ZipDirectoryEntry#addFileSystemEntry(fileSystemEntry)`. You can test it in the [third demo](https://gildas-lormeau.github.io/zip.js/demos/demo-zip-manager.html) by dropping a folder in the left part of the explorer. Then you can download the zip by hovering the folder and click on the second icon at the right of the folder name. The method to 

If you're using the core API, you have to code the function that will import the folder and its files recursively. This function would be very similar to the code below.

https://github.com/gildas-lormeau/zip.js/blob/8f80db102ecd13edd86d9393817271fdf6d8d65a/lib/core/zip-fs-core.js#L506-L554

**Comment by gildas-lormeau** [comment]
@av01d It's actually much simpler with than I thought with an `<input>` tag. Here is an example that allows you to creates zip files from a folder: https://jsfiddle.net/4o7pe0xa/23/

**Comment by av01d** [comment]
That's quite brilliant, thanks!

**Comment by gildas-lormeau** [comment]
You're welcome! I'm closing the issue but I added the question in the discussions, see https://github.com/gildas-lormeau/zip.js/discussions/233.

**Comment by av01d** [comment]
Well, thanks to your excellent feedback, our tool is now capable of zipping entire folders.
Both by a `<input type=file>` tag, *and* drag/drop of folders now works as well.
It's a much simpler tool than your example 3, but for novice users it should be good.
https://www.files2zip.com

**Comment by gildas-lormeau** [comment]
I tested your tool and it works very well :). Thank you for using zip.js too!

Note that you could improve the performance of the compression by replacing the `for of loop` with a `Promise.all call` when iterating on file entries. See the code below (this is the obfuscated source of the JS on files2zip.com). Using fflate instead of pako should also help.

```js

// for (c of h) { old code

await Promise.all(Array.from(h).map(c => { // new code

  var e = $('#pb' + p(c.name + c.size)).addClass('progress-bar-striped');
  const f = await t.addFile(c, {
    bufferedWrite: !0,
    password: b,
    onprogress: (d, k) => {
      d = Math.round(d / k * 100);
      $('.progress-bar', e).css('width', d + '%');
      100 == d && e.removeClass('progress-bar-striped')
    }
  });
  a += f.compressedSize

// }  old code

});  // new code

```

**Comment by av01d** [comment]
Thanks for the pointers, both implemented and live!

You can choose methods via a hash on the url:
https://www.files2zip.com/#pako
https://www.files2zip.com/#fflate
https://www.files2zip.com/#zipjs

Thanks for all your help, have a good weekend!

**Comment by gildas-lormeau** [comment]
Thank you, have a nice weekend too!
