### ISSUE TITLE
onprogress - dont work

### ISSUE THREAD

**Issue by KiborgMaster** [gildas-lormeau/zip.js#234]
Good day, progress function undefined when set options
My code
entries[0].getData(new zip.TextWriter(), { 
		'onprogress': (current, total)=>{
			progress.xhr(i, {'total': total, 'loaded': current});
		},
	}
)

I fixed zip.js

![image](https://user-images.githubusercontent.com/20395262/111983509-e0ac6a00-8b12-11eb-952f-671ab5d67416.png)

**Comment by gildas-lormeau** [comment]
Thank you! It's fixed in the version 2.2.24 i just published.

**Comment by KiborgMaster** [comment]
Please ))) I'm waiting for an updated version

**Comment by gildas-lormeau** [comment]
Well, I published the fix yesterday.
