### ISSUE TITLE
How to limit the number of simultaneous downloads

### ISSUE THREAD

**Issue by mebibou** [gildas-lormeau/zip.js#235]
I am zipping a lot of files from a remote server using:
```javascript
const zip = require('@zip.js/zip.js');

zip.configure({
  workerScriptsPath: 'zip/'
});

await writer.add('http://file1', new zip.HttpReader(url));
await writer.add('http://file1', new zip.HttpReader(url));
...
```
But when I have thousands of files to include, it is making a lot of requests at the same time.

It would be nice to be able to set a limit of parallel downloads

**Comment by gildas-lormeau** [comment]
This problem is related to the support of zip64 and the fact that zip.js uses its pool worker only for compressing/uncompressing data. A proper fix would be to let workers handle the metadata as well (filename, modification date, compressed size, uncompressed size etc.).

I pushed a fix in the version 2.2.26 I just deployed but you will have to set the `zip64` option explicitly (set it to `false` if you know the output file won't exceed 4GB, `true` otherwise) when creating the `ZipWriter` instance or when calling `ZipWriter#add`.

**Comment by mebibou** [comment]
@gildas-lormeau I was using version `2.0.1` in Angular before and it worked well, but with `2.2.26` it wont even compile anymore:
```
Error: ./node_modules/@zip.js/zip.js/lib/core/codecs/codec-pool-worker.js 82:70
Module parse failed: Unexpected token (82:70)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 	let messageTask;
| 	if (!workerData.interface) {
> 		workerData.worker = new Worker(new URL(workerData.scripts[0], import.meta.url));
| 		workerData.worker.addEventListener(MESSAGE_EVENT_TYPE, onMessage, false);
| 		workerData.interface = {
```

**Comment by mebibou** [comment]
Ok, fixed the problem above, will test the latest version and see if improves the requests

**Comment by mebibou** [comment]
@gildas-lormeau ok so it seems to be better at downloading the resources without trying to run thousands of requests at once, but now my code to show a progress bar doesn't work anymore (it doesnt move at all until the end of the process).

My whole code is:
```typescript
const zip = require('@zip.js/zip.js');

zip.configure({
  workerScriptsPath: 'zip/'
});

const addUrl = async (writer, { url, filepath }: IZipResource) => {
  try { return await writer.add(filepath, new zip.HttpReader(url)); } catch (_err) {}
};

export interface IZipResource {
  url: string;
  filepath: string;
}

type progressCallback = (percentage: number) => void;

export const zipResources = async (resources: IZipResource[], onProgress?: progressCallback) => {
  // use a BlobWriter to store with a ZipWriter the zip into a Blob object
  const blobWriter = new zip.BlobWriter('application/zip');
  const writer = new zip.ZipWriter(blobWriter, { zip64: false });
  let downloaded = 0;
  await Promise.all(resources.map(async resource => {
    await addUrl(writer, resource);
    downloaded = downloaded + 1;
    return !!onProgress && onProgress(downloaded / resources.length * 100);
  }));
  await writer.close();
  const blob = await blobWriter.getData();
  return URL.createObjectURL(blob);
};
```

So before it used to call the `onProgress` function quite regularly and show a nice process bar, but not anymore. How could I do a nice progress bar on the latest version `2.2.26`?

**Comment by gildas-lormeau** [comment]
This issue should be fixed by replacing

```js
const writer = new zip.ZipWriter(blobWriter, { zip64: false });
```

with:
```js
const writer = new zip.ZipWriter(blobWriter, { zip64: false, bufferedWrite: true });
```

**Comment by mebibou** [comment]
Oh nice `bufferedWrite` seems to do the trick
