### ISSUE TITLE
Exposing compression method in Entry

### ISSUE THREAD

**Issue by matthiasharrer** [gildas-lormeau/zip.js#238]
Hey,

I am trying to validate a zip file before uploading it to a backend service. 
This backend service can only work with certain compression methods and I would like to show a hint about non processable archives in the frontend as soon as possible.

I am wondering if you have any objections against exposing the compression method in the FileReader API.
I am happy to try to do this and open a PR.

As far as I could tell I would need to update the copied properties in the Entry class:
https://github.com/gildas-lormeau/zip.js/blob/master/lib/core/zip-entry.js#L31

and the (I think two) places where the class is instanciated in zipReader and zipWriter.

I am not completely sure on how to represent the compression method in the API though. 
It could either be the raw int value or I could try to convert it into some kind of more self-descriptive string.

Looking forward to you opinions

Regards
Matthias

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion and the use-case description. It's fixed in the version 2.2.27 I just published. Currently, it's exposed as a Number storing the raw integer value.

**Comment by matthiasharrer** [comment]
Oh that was fast .. thanks a lot!

**Comment by gildas-lormeau** [comment]
You're welcome!
