### ISSUE TITLE
Error creating zip when a single file in the zip is large

### ISSUE THREAD

**Issue by ChrisMedicom** [gildas-lormeau/zip.js#239]
Hello, I am getting an error when creating a zip that involves a large single file (Mac and Windows Chrome). I first saw it on chrome on a 3.24GB file but after some testing with different sizes, it seems to happen when a file 2.5gb or above is included.

To test different sized files I used this tool:
https://fastest.fish/test-files

In testing, 2.5gb, 3gb, and 3.5gb test files failed but a 2gb test file worked. Here's the 2.5GB file from a Google drive link as well if that is easier to obtain than the tool above:
https://drive.google.com/file/d/1tTH-xSTGfX82jPi15X9YZqmo-2uRmM2B/view?usp=sharing

I have encountered the failure on both our own code and the create a zip sample (https://gildas-lormeau.github.io/zip.js/). The error seen when using the create a zip sample code looks like this:
![image](https://user-images.githubusercontent.com/69816670/115305072-c8d8fd80-a133-11eb-8088-1807bfdb2d0e.png)

Thanks for any help that can be provided!

**Comment by gildas-lormeau** [comment]
I confirm I can reproduce the issue in Firefox and Chrome. Is the zip file you're creating intended to be "downloaded" by the user or to be uploaded to a server?

**Comment by ChrisMedicom** [comment]
hi @gildas-lormeau , the zip file being created is intended to be downloaded by the user to their browser after the zip is complete

**Comment by gildas-lormeau** [comment]
I did more tests. The issue is related to the fact that an `ArrayBuffer` is used internally when the option `bufferedWrite` is set to `true` or if you attempt to compress multiple files in parallel. Currently, to circumvent this issue, you have to set `bufferedWrite` to `false` and avoid compressing multiple files in parallel.
