### ISSUE TITLE
Add support of binary strings

### ISSUE THREAD

**Issue by Sharcoux** [gildas-lormeau/zip.js#241]
Maybe I misunderstood the documentation, but here is what I'm doing:

1. getting the data from a local file:

I'm just using an input field, and this part was tested in other parts of my app and I'm 100% sure that it's working. Basically, it reads the file's content and return it as

```typescript
    const input = document.createElement('input')
    input.type = 'file'
    input.accept = '.zip'
    input.onchange = async (e: React.ChangeEvent<HTMLInputElement>) => {
      const files = Array.from(e.target.files || [])
      if (files.length === 0) return reject(Error('no file selected'))
      
      // read the content of the picked files
      const readingAllFiles = files.map(async file => {
        return new Promise<FileInfo>(resolve => {
          const reader = new FileReader()
          // We convert the raw content into a binary string
          reader.onload = () => resolve(Buffer.from(reader.result as ArrayBuffer).toString('binary'))
          reader.readAsArrayBuffer(file)
        })
      })

      Promise.all(readingAllFiles).then(res => resolve(res))
    }
  })
  input.click()
}
```

2. Trying to unzip it with zip.js:

Here is what I did:

```typescript
    const reader = new ZipReader(new TextReader(content))
    const entries = await reader.getEntries()
```

I get: `File format is not recognized`

Did I miss something?

Here is a [codesandbox](https://codesandbox.io/s/bitter-fast-v27nv?file=/src/App.js) showing the code, but I couldn't make the import work.

**Comment by gildas-lormeau** [comment]
zip.js does not support binary string out of the box. Actually, `TextReader` is used to read text content from a zip file. This could be fixed by implementing a `BinaryStringReader` though. 

If you don't really need to use binary strings, I would recommend to use `BlobReader` instead and pass [`File`](https://developer.mozilla.org/docs/Web/API/File) instances as parameters, `File` inherits from `Blob`.

**Comment by Sharcoux** [comment]
The thing is that I'm using a cross-platform code (react-native + react-native-web), so using Blob is not ideal... I finally made it work using UInt8Array:

```js
    const buffer = Buffer.from(content, 'binary')
    const ui8 = new Uint8Array(buffer.buffer, buffer.byteOffset, buffer.byteLength / Uint8Array.BYTES_PER_ELEMENT)
    const reader = new ZipReader(new Uint8ArrayReader(ui8))
```

A `BinaryStringReader` implementation could just make use of this code I guess.

Thanks for your time and your lib!

**Comment by gildas-lormeau** [comment]
@Sharcoux I think you made the good choice. `Uint8Array` is fast and seems appropriate. I'm not sure I'll implement a `BinaryStringReader`class though because reading binary strings is very inefficient unfortunately.

**Comment by gildas-lormeau** [comment]
I think I won't implement this feature in zip.js because it can't really be optimized, i.e. each byte has to be processed in JavaScript. Moreover, binary strings are obsolete I think. Although, feel free to discuss about the issue if you think I'm wrong.

**Comment by Sharcoux** [comment]
Well, actually, the best implementation would be:

```js
const binaryString2UintArray = binaryString => {
    const buffer = Buffer.from(content, 'binary')
    return new Uint8Array(buffer.buffer, buffer.byteOffset, buffer.byteLength / Uint8Array.BYTES_PER_ELEMENT)
}
   
class BinaryStringReader extends Uint8ArrayReader {
  constructor(binaryString) {
    super(binaryString2UintArray(binaryString))
  }
}
```

**Comment by gildas-lormeau** [comment]
Unfortunately, `[Buffer](https://nodejs.org/api/buffer.html)` does not exist in the browser.

**Comment by Sharcoux** [comment]
Well, you can always use [this polyfill](https://github.com/feross/buffer) (which is the one used by browserify), and if you don't want to make it a dependency, you can mark it as optional dependency and in the code, do sth like:

```js
try {
  return Buffer.from(content, 'binary')
} catch(e) {
  if(e instanceof ReferenceError) throw new Error('Buffer was not defined. Did you forget to add "buffer" to your dependencies? BinaryStringReader depends on it')
}
```

**Comment by gildas-lormeau** [comment]
I agree but this polyfill does not use any "trick" to process binary string faster in the browser (or Deno). Also, zip.js has not been designed for Node so it cannot really benefit from the native implementation of `Buffer`.

**Comment by Sharcoux** [comment]
Yes, I see your point. My point was that if the user was stuck with a binary string, at least he would have the reader for it, even if it is slow, and your point is that it's better to discourage the user to use binary string and encourage other formats, right?

Both arguments seems valid to me. Well, it's your lib. Do as you feel like :)

**Comment by gildas-lormeau** [comment]
Actually, I think the need for handling binary string is low. I don't have any study that proves it though ;)

Today, each `Reader`/`Writer` have dedicated implementations which ensure that RAM consumption is reasonable. An effort is also made to use the browser's native APIs as much as possible. These are the 2 main points that in my opinion justify the integration of a new `Reader`/`Writer` class in zip.js.

I think the best compromise would be to offer an implementation in the [Discussions](https://github.com/gildas-lormeau/zip.js/discussions) tab and add a link in the documentation. I will try to provide it.

**Comment by gildas-lormeau** [comment]
Here is the implementation: https://github.com/gildas-lormeau/zip.js/discussions/268
