### ISSUE TITLE
v2.2.31: Module not found: Error: Can't resolve './lib/zip-fs.js'

### ISSUE THREAD

**Issue by lucsoft** [gildas-lormeau/zip.js#246]
![image](https://user-images.githubusercontent.com/11093382/118324367-3a715500-b502-11eb-8351-27c9846df8de.png)

Webpack: 5.37.0
NodeJS: 16.1

Version 2.2.30 Works perfectly fine

**Comment by gildas-lormeau** [comment]
Thanks for reporting the problem. I made some mistakes when I released this version on npm. Version 2.2.32 fixes the problem.
