### ISSUE TITLE
Does extra field always exist?

### ISSUE THREAD

**Issue by Aeroblast** [gildas-lormeau/zip.js#253]
I use zip.js to create EPUB files (actually a zip file following [EPUB OCF standard](https://www.w3.org/publishing/epub3/epub-ocf.html#sec-zip-container-mime)), and then validate them using [EPUBCheck](https://github.com/w3c/epubcheck).

It says:
> ERROR(PKG-005): test.epub(-1,-1): The mimetype file has an extra field of length 9. The use of the extra field feature of the ZIP format is not permitted for the mimetype file.

Is that means even I don't use extra field, it still exist but just left empty? Could I erase it completely?

**Comment by gildas-lormeau** [comment]
Indeed, I added recently the support of UNIX and NTFS extended timestamps. This is why you see the extra field error.

To fix the issue, I added in the version `2.3.3` a new option you can pass when creating a `ZipWriter` object or when calling `ZipWriter#add`. The new option is `extendedTimestamp`. You have to set it to `false` to make sure no extra field will be written.
