### ISSUE TITLE
index.d.ts not up to date on NPM

### ISSUE THREAD

**Issue by tim-we** [gildas-lormeau/zip.js#256]
When I install the current version (`2.3.5`) with `npm i @zip.js/zip.js@2.3.5` I expect the current version of `index.d.ts` from this repo including [these](https://github.com/gildas-lormeau/zip.js/commit/577d684a9eb39bd8f2526df11e882d131389d700) changes but it seems to be an old version. I don't know much about npm publishing so sorry if this is a misunderstanding/error on my side. I made sure the installed version is `2.3.5` though.

**Comment by gildas-lormeau** [comment]
That's strange. I don't know what I did wrong... I published a new version on NPM to fix this.
