### ISSUE TITLE
Uncaught ReferenceError since Angular 12.2.4

### ISSUE THREAD

**Issue by mebibou** [gildas-lormeau/zip.js#267]
I just updated Angular to `12.2.4` (from `12.0.0`) and I have some strange error occurring now that I didnt have before:
```
Uncaught ReferenceError: Qn is not defined
    at ce503531-ed2d-47d5-bfa9-1a3e3d13284f:1
    at ce503531-ed2d-47d5-bfa9-1a3e3d13284f:1
```

This occurs when there are requests to download some `blob` version of the data, see screenshot below:

<img width="872" alt="Screenshot 2021-09-08 at 13 56 46" src="https://user-images.githubusercontent.com/305342/132505138-a590ebed-bd08-4828-86f7-6f51b2407b98.png">

If I use `useWebWorkers: false` then the issue disappears

**Comment by mebibou** [comment]
Note: I tried looking at what this `Qn` was referring to and I think its in the `configureWebWorker` function where it uses `await async` and it replaces that by `Qn`

**Comment by gildas-lormeau** [comment]
It looks like it's a regression in Angular. Did you report it to them? Unfortunately, I don't know what I can do since I did not change anything meanwhile on my end.

**Comment by mebibou** [comment]
> It looks like it's a regression in Angular. Did you report it to them? Unfortunately, I don't know what I can do since I did not change anything meanwhile on my end.

I know it wasn't a change in zip.js, but maybe someone has a similar issue and knows what is wrong?

Reporting to Angular usually doesnt get you anywhere...

**Comment by gildas-lormeau** [comment]
I did a quick test to ensure it is not a regression in webpack by building the app in the zip file here: https://github.com/gildas-lormeau/zip.js/issues/212#issuecomment-767454269. I was able to build it and run it without any particular issue with the latest version of webpack 5.

So, it would be an issue with the way angular configures webpack. I'm really not an expert of angular so it will take some time for me to investigate more on this issue. What's weird is that it seems to be the same problem as webpack 4. In the meantime, it might be interesting for me to know the exact version of angular that causes this problem.

**Comment by mebibou** [comment]
> In the meantime, it might be interesting for me to know the exact version of angular that causes this problem.

As stated in the issue title :)

**Comment by gildas-lormeau** [comment]
So you confirm the bug did not exist in version 12.2.3?

**Comment by mebibou** [comment]
Ah ok sorry havent tested different versions, I will try to dichotomise it down

**Comment by gildas-lormeau** [comment]
Thank you :)

**Comment by gildas-lormeau** [comment]
@mebibou Beware: the regression is probably in `angular-cli` actually.

**Comment by gildas-lormeau** [comment]
@mebibou Could you also do the test with the version 2.3.9 of zip.js? I did a slight change related to web workers in the version 2.3.10.

**Comment by mebibou** [comment]
I actually tried to revert back to `2.3.7` when I first had the problem and it was still the same
I tested with angular `12.1.4` and it works, does not work starting from `12.2.0`

**Comment by mebibou** [comment]
Ok I can confirm did a test with `12.2.0` and `2.3.7` and the problem is the same

**Comment by gildas-lormeau** [comment]
The version `2.3.8` I just published should fix the issue.

**Comment by mebibou** [comment]
it works, thanks for fixing it!

**Comment by gildas-lormeau** [comment]
You're welcome!
