### ISSUE TITLE
Fetch Range requests is using "header_range" header instead of "Range"; XHR Range not working (status on Uint8Array...; no return)

### ISSUE THREAD

**Issue by bwbroersma** [gildas-lormeau/zip.js#269]
This is a correct definition:
https://github.com/gildas-lormeau/zip.js/blob/bf322d19b387044e140b2a9a0aef0aedfb9d1141/lib/core/io.js#L39
It is used correctly by the `XHRReader`.`readUint8Array`:
https://github.com/gildas-lormeau/zip.js/blob/bf322d19b387044e140b2a9a0aef0aedfb9d1141/lib/core/io.js#L301
However the `FetchReader`.`readUint8Array` uses `HEADER_RANGE`:
https://github.com/gildas-lormeau/zip.js/blob/bf322d19b387044e140b2a9a0aef0aedfb9d1141/lib/core/io.js#L234
Resulting in a CORS Preflight with `Access-Control-Request-Headers: header_range` .

**Working code** using [ES6 ComputedPropertyName](https://262.ecma-international.org/6.0/#sec-object-initializer) would be:
```js
	{[HTTP_HEADER_RANGE]: HTTP_RANGE_UNIT + "=" + index + "-" + (index + length - 1) }));
```

**Comment by gildas-lormeau** [comment]
Thank you! I'm sorry, it looks like I fixed the issue just before your PR.

**Comment by bwbroersma** [comment]
Yeah I was slow, you beat me :+1: :slightly_smiling_face:

BTW I'm also not sure that the XHR Range is working in Firefox, I got an `Error(ERR_HTTP_RANGE)` and my debugger said the `status` was `""` (empty string).
https://github.com/gildas-lormeau/zip.js/blob/88cef5886c6ad2886cf1ef04b52c7b92d2b5e4f0/lib/core/io.js#L300-L304

**Comment by gildas-lormeau** [comment]
That's weird, what do you see in the Network panel of the Dev tools?

**Comment by bwbroersma** [comment]
I use FireFox Nightly (`94.0a1 (2021-09-07)`), but it's also not working in Google Chrome (`93.0.4577.63 (Official Build) (64-bit)`)
Goto https://cors-anywhere.herokuapp.com/corsdemo and click "Request temporary access to the demo server".
Goto https://gildas-lormeau.github.io/zip.js/demos/demo-read-file.html
Open Console:
```js
let rangeReader=new zip.HttpRangeReader('https://cors-anywhere.herokuapp.com/https://geodata.nationaalgeoregister.nl/inspireadressen/extract/inspireadressen.zip',{forceRangeRequests:true,useXHR:true});
let zipReader=new zip.ZipReader(rangeReader);
zipReader.getEntries();
```
and get a `Uncaught (in promise) Error: HTTP Range not supported`
if you go to Debugger (FF) or Sources (Chrome) and pretty `/lib/zip.min.js` and set a breakpoint on line 1401 (FF) or 1101 (Chrome) it will hit there with a `status = ""` while the response in the Network tab says `206` .. 

Looks like this is because of:
```js
response = new Promise( ... => resolve(new Uint8Array(request.response))
```
The wrapping should not (yet).
Look again at this code, the code in the first if never returns anything:
https://github.com/gildas-lormeau/zip.js/blob/88cef5886c6ad2886cf1ef04b52c7b92d2b5e4f0/lib/core/io.js#L298-L312
I fixed it faster this time :slightly_smiling_face:

**Comment by bwbroersma** [comment]
And now I wonder: since both fetch & XHR code was broken, did it ever work and/or how did you test it?

**Comment by gildas-lormeau** [comment]
Thank you for the fix, I'll merge it ASAP. I thought I was testing it in [`/tests/pages/test-sw.html`](https://github.com/gildas-lormeau/zip.js/blob/88cef5886c6ad2886cf1ef04b52c7b92d2b5e4f0/tests/pages/test-sw.js) but since the header name was incorrect, the test was working without doing range requests. I confirm it has been tested and worked in the past, it's a regression.

**Comment by gildas-lormeau** [comment]
I tested the following code with the current implementation in Firefox and Chrome with Apache and it works as expected with `useXHR: false` and `useXHR: true`. In both browsers and both cases, the test runs fine and I see 206 responses in the Network panel.

```js
const zipReader = new zip.ZipReader(new zip.HttpRangeReader("../data/lorem.zip", { useXHR: false }));
const entries = await zipReader.getEntries();
const dataBlobWriter = new zip.BlobWriter();
let data = await entries[0].getData(dataBlobWriter);
await zipReader.close();
```

**Comment by bwbroersma** [comment]
Great! I was reading [a 1.79 GiB zip file](https://geodata.nationaalgeoregister.nl/inspireadressen/extract/inspireadressen.zip)*, so I could not get away with not using Range :upside_down_face:.
Thanks a lot for the extremely fast response :rocket: (BTW I also tested the code before the PR's)

\* which supports CORS & Ranges, but not the combination, just send [a request (🇳🇱)](https://geoforum.nl/t/cors-range-request-op-geodata-nationaalgeoregister-nl/6309) to fix that, that's why I used a [CORS proxy](https://cors-anywhere.herokuapp.com).

**Comment by gildas-lormeau** [comment]
I'm really glad to hear that zip.js is useful for you. I was fast because I was doing some changes when you created the issue and also because I hate bugs viscerally. Thank you also very much for your help, you have done an excellent job in identifying and correcting these 2 problems that I consider as major.

I must admit that CORS is quite painful to configure correctly, I hope this problem will be solved.

**Comment by bwbroersma** [comment]
Thanks for creating zip.js, it makes it possible to handle really large zip files in the browser and just extracting a tiny portion. I was actually looking at [jszip](https://github.com/Stuk/jszip) which has [a reference to this project about the ranges](https://github.com/Stuk/jszip/issues/576#issuecomment-552477977).

Next up for me is checking the boundaries of [XSLTProcessor](https://developer.mozilla.org/en-US/docs/Web/API/XSLTProcessor) :slightly_smiling_face: . My whole goal is extracting a XML selection from a ZIP and executing a XSLT to produce some useful result for non-tech users, part one ✅.

BTW do you know 'command line tools' that support `$ unzip -l https://url` stuff with range queries?

**Comment by gildas-lormeau** [comment]
In fact, I created zip.js because I needed to generate large zip files without eating all the RAM in a old Chrome extension. I was not satisfied with jszip because it was not able to do so (and also because its DEFLATE implementation was buggy with binary data).

I played with XSLT (in Java) approximately 15 years ago. I have a mixed memory of it. I was still happy the first time I wrote a recursive template. The fact that this API has been "experimental" in browsers for more than 10 years does not inspire confidence in the durability of the code either :p. I wish you good luck anyway!

I don't know any command line tool that supports range requests. You could however write your own by using zip.js in Deno ;)

**Comment by bwbroersma** [comment]
Haha, I have **very** mixed emotions with XML too :slightly_smiling_face:, but at the moment breathing it since we have our (🇳🇱) election results in [EML (Election Markup Language)](https://en.wikipedia.org/wiki/Election_Markup_Language). Per election we publish all polling stations results in one 50 MB zip that extracts to 2GB of XML, but most users just want a CSV of one municipality. Hosting stuff in (central) government setting is hard, so an all static tool on GitHub would be a lifesaver.

BTW xmlstarlet can [generate display generated](http://xmlstar.sourceforge.net/doc/xmlstarlet.txt) XSLT with `-C` or `--comp`, which makes writing XSLTs a lot less verbose.

The most bizarre thing is that the main tooling is stuck at XSLT 1.0, forever.

**Comment by gildas-lormeau** [comment]
@bwbroersma Here is a basic implementation of the `unzip` command: https://gist.github.com/gildas-lormeau/731485821c9237b638d01bb4074a6369

**Comment by ddelapasse2** [comment]
Hi @bwbroersma & @gildas-lormeau!  Do you happen to have any example of reading through a huge zip file in chunks?  I see the classes, but struggling on how to combine them without finding any examples.  We had another library working great, but now we have a huge zip to process and it's too big for browser memory.

**Comment by gildas-lormeau** [comment]
@ddelapasse2 If your HTTP server supports [range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) then all you have to do is use the `HttpRangeReader` class to read the file, e.g. `zipReader = new zip.ZipReader(new zip.HttpRangeReader("https://yourserver.com/file.zip"));`

**Comment by ddelapasse2** [comment]
hmm, I did see something similar to that in a test file, but I'm trying to read the file in chunks 

In one of the samples there is a chunk size. Is that intended to be range?  Clearly I am confused.  This file is huge  :-).

zip.configure({ chunkSize: 256, useWebWorkers: true });
const zipReader = new zip.ZipReader(new zip.HttpRangeReader(this.source, { useXHR: false }));

let options = { 'Range': 'bytes=0-224875393' };    **<--- is this a valid thing to do?  trying to just read a chunk**
let httpRange = new zip.HttpRangeReader(this.source, options);

httpRange.init(function (response) {
    console.log(response);            **<-- I never get here**
});

**In the network tab I see 206, but the response header is:  Content-Range: bytes 0-0/1124376971**

**Comment by gildas-lormeau** [comment]
If you see a `206` then it means the server supports range requests. You code is not ok. Here is an example showing how to read the first entry in a zip file.

```js
const zipReader = new zip.ZipReader(new zip.HttpRangeReader(this.source));
const entries = await zipReader.getEntries();
const firstEntry = entries[0];
const blob = await firstEntry.getData(new zip.BlobWriter());
console.log(firstEntry.name, blob);
await zipReader.close();
```

**Comment by ddelapasse2** [comment]
You code doesn't work for us.  Isn't there any example somewhere of using either chunking or "one file at a time"?

![image](https://github.com/gildas-lormeau/zip.js/assets/18335575/1b665916-c8fc-4434-bcfc-f897a7352e87)

**Comment by gildas-lormeau** [comment]
You must ensure that your HTTP server supports Range requests.

**Comment by ddelapasse2** [comment]
Yes, we confirmed that.   We are dissecting a zip from Azure blob storage.  But where do we specify the ranges?   Seems that some are being assigned to us - but they are very small and it's making thousands of calls just to read a small (1GB) zip. 

We read the documentation that we should set 'headers' and useXHR as below but it seems to just ignore us.  Is the way we are setting Range?
 

```
        const zipReader = new zip.ZipReader(new zip.HttpRangeReader(this.source, { **headers: { 'Range': 'bytes= 0-1124376967'** }, useXHR: false }));
        const entries = await zipReader.getEntries();
        await Promise.all(entries.map(async (entry, i = 1) => {
            if (entry.filename.endsWith(".jpg")) {
                let obj = {
                    'id': i,
                    'text': entry.filename,
                    blob: this.sanitizer.bypassSecurityTrustUrl(URL.createObjectURL(await entry.getData(new zip.BlobWriter("application/image"))))
                };
                console.log(i);
                this.addZipImage(obj);
            }
        }));
```

**Comment by ddelapasse2** [comment]
@bwbroersma  I'm curious how you might have used this?   Did you use getEntries?  Or did you try to read the whole file in chunks and then inside the chunks try to extract all the files?

**Comment by gildas-lormeau** [comment]
@ddelapasse2 Please attach a screenshot of your network tab in the debugger when using `HttpRangeReader` on a server which support range requests, i.e. when the `HTTP Range not supported` error is not thrown.

**Comment by ddelapasse2** [comment]
@gildas-lormeau  We believe blob storage DOES allow it and in fact, this is working fine BUT we are unable to control the ranges ourselves.  We are setting them in the contructor, but the package seems to ignore us and requests the small ranges.  We are so close - but we need largers "chunks" so our app doesn't have to make 10,000 requests to read the file.

![image](https://github.com/gildas-lormeau/zip.js/assets/18335575/3df61b65-a14b-4bd5-b428-348081349fd7)

**Comment by gildas-lormeau** [comment]
Can you please unselect the line you selected in order to see the of each requests? I would like to see the view as a grid.

**Comment by ddelapasse2** [comment]
![image](https://github.com/gildas-lormeau/zip.js/assets/18335575/77e30403-8f03-43dd-93f8-23252a04e3ee)

**Comment by gildas-lormeau** [comment]
Thank you. 

In your example, does the selected line correspond to the compressed data set of a zip file entry weighing `873` bytes? Or is it only a portion of the entry data in the zip file?

**Comment by TJ-Edwards** [comment]
We run the risk of cutting off files if we specify a singular byte range configuration. I was planning on looping through the sizes and adding them up until I reach 500 mb of content or the first entry over that. For instance if a file is 1 gig at a time, I would calculate 4 byte range chunks. Ill use 0-100 to illustrate. Byte ranges wont always be a fixed range because of varying file sizes.

0-27, (request 1)
28 - 56, (request 2)
57- 82, (request 3)
83 - 100 (request 4)

**Comment by gildas-lormeau** [comment]
If this is the case, which I suspect it is, then the `HttpRangeReader` class needs to be extended to include a data cache mechanism. In this way, the number of requests would be reduced in the case of reading entries (in order) whose compressed size is less than `chunkSize`.

**Comment by TJ-Edwards** [comment]
They are images. The tool we are building is an image viewer with a slider and auto play. From the tests I have done, it is very performant. Almost video speeds during playback. But the problem is the size of the archives we have to deal with (7gigs in some cases). 

The browser cant hold on to all of that at once. So I was planning on grabbing a single chunk of the archive at a time. And loading another while the user is watching one. Then disposing of the first chunk when the user is far enough along.

**Comment by gildas-lormeau** [comment]
I would recommend you to write a class like the one below to do some tests.

```js
class HttpRangeCacheReader  {
  
  constructor(url, options = {}) {
    options.useRangeHeader = true;
    super(url, options);
  }
  
  readUint8Array(index, length) {
    console.log("index", index, "length", length);
    return this.reader.readUint8Array(index, length);
  }
}
```

Then, you could add for example an instance property, e.g. `this.cacheData` containing a `Uint8Array`. You could use it in `readUint8Array` in order to call `this.reader.readUint8Array(index, length)` or return the data from `this.cacheData`. You would probably also need a property like `this.cacheDataIndex` to store the index of the cached data.

**Comment by TJ-Edwards** [comment]
Thanks for the idea. Ill give that a shot.

**Comment by gildas-lormeau** [comment]
You're welcome. I think this is the simplest solution. I might also implement it in the future in zip.js but maybe in a more generic way (i.e. not dependent on `HttpRangeReader` but on just a `Reader` instance). Note that I simplified a little bit the code meanwhile.
