### ISSUE TITLE
Reading EOCD twice

### ISSUE THREAD

**Issue by bwbroersma** [gildas-lormeau/zip.js#272]
I saw zip.js was requesting the <abbr title="End of Central Directory Record">EOCD</abbr> bytes again in the last fetch:
1. `HEAD` for length
2. `GET` EOCD (last 22 bytes)
3. `GET` Central Directory, but not using the Size of central directory from the EOCD:
https://github.com/gildas-lormeau/zip.js/blob/f3804c7b4c7d305c742e99d18bf36a009b1df124/lib/core/zip-reader.js#L137
I would expect it would use `directoryDataLength` for the length:
https://github.com/gildas-lormeau/zip.js/blob/f3804c7b4c7d305c742e99d18bf36a009b1df124/lib/core/zip-reader.js#L104-L107

So I changed it to use `directoryDataLength`, and it works for my non-zip64 files, but I did not test the zip64 stuff.

I think the other `reader.size - directoryDataOffset` on line 144 should be changed to `directoryDataLength` too, but I'm not really sure when this code is used.
https://github.com/gildas-lormeau/zip.js/blob/f3804c7b4c7d305c742e99d18bf36a009b1df124/lib/core/zip-reader.js#L144

**Comment by gildas-lormeau** [comment]
Thank you. I need to take some time to check your changes because it breaks the following tests:
- pages/test-zip64.html	
- pages/test-zip64-auto.html	
- pages/test-zip64-crypto.html

**Comment by gildas-lormeau** [comment]
So, I accepted your PR it was in fact a bug on my end.
