### ISSUE TITLE
macos zip utility can't open the zips

### ISSUE THREAD

**Issue by asturur** [gildas-lormeau/zip.js#274]
![image](https://user-images.githubusercontent.com/1194048/134020015-7db4b800-5bad-431d-918f-c19a6ef78abd.png)

Same zip file can be opened with another zip utility ( i tried keka for example ).

I tried to change the compression level or the zip64 format, but nothing change.
Is this a known issue?

**Comment by gildas-lormeau** [comment]
Can you try to set the option `dataDescriptor` to `false`?

**Comment by asturur** [comment]
sure let me try right now

**Comment by asturur** [comment]
seems to work. Does this diserve a readme or a changed default value?

**Comment by gildas-lormeau** [comment]
I prefer to let `dataDescriptor` to `true` because it allows to stream the zip file. Maybe moving this thread to the "Discussions" tab could suffice?

**Comment by asturur** [comment]
Yeas please make it a discussion. What does it mean that allow to stream the file?
