### ISSUE TITLE
How can I get the blob url when I finished zip

### ISSUE THREAD

**Issue by hugetiny** [gildas-lormeau/zip.js#276]
I console.log all the r,result,blob, can't find info like:
blob:http://localhost:8080/xxxxxxxxxxxx

```
					const blobWriter = new zip.BlobWriter("application/zip");
					const zipWriter = new zip.ZipWriter(blobWriter, {
						level: 9
					});
					const r = await zipWriter.add(fileName, new zip.BlobReader(inputBlob));
					const result = await zipWriter.close()
					const blob = await blobWriter.getData()
```

**Comment by gildas-lormeau** [comment]
You need to call `const blobURL = Object.createURL(blob)` (see https://developer.mozilla.org/docs/Web/API/URL/createObjectURL) after the code you posted and `blobURL` will contain the string you want.
