### ISSUE TITLE
support zip/unzip the zip file which be ziped by 7zip or rar 

### ISSUE THREAD

**Issue by dwj1979** [gildas-lormeau/zip.js#295]
I want to know if zip.js lib support zip/unzip the zip file which be zipped by 7zip or rar

**Comment by gildas-lormeau** [comment]
Unfortunately, this is out of the scope of the library. Regarding 7z files, maybe this library could help you: https://github.com/sonictruth/7zip.js. The license of the rar file format does not allow to distribute an open-source implementation.
