### ISSUE TITLE
Empty zip file crashes when trying to read entries in the zip file

### ISSUE THREAD

**Issue by Fineman22** [gildas-lormeau/zip.js#300]
Heya,

The library crashes when it tries to read an empty zip file  (empty as in no files in it).

For example this empty zip file file:
[empty.zip](https://github.com/gildas-lormeau/zip.js/files/7957098/empty.zip)

if I upload this here:
https://gildas-lormeau.github.io/zip.js/demos/demo-read-file.html

results in 
![image](https://user-images.githubusercontent.com/45386465/151515552-0d66e62f-1db3-48d5-8180-27964686612d.png)

I expect it not to crash and just return an empty array of entries.

Thanks in advance :)

**Comment by gildas-lormeau** [comment]
Thank you! This issue is fixed in the version 2.4.2
