### ISSUE TITLE
Website demo-create-file.html doesn't work

### ISSUE THREAD

**Issue by stampyzfanz** [gildas-lormeau/zip.js#304]
Whenever a file is uploaded to https://gildas-lormeau.github.io/zip.js/demos/demo-create-file.html, z-worker.js is attempted to be loaded but it appears the path is wrong.
![image](https://user-images.githubusercontent.com/34364128/152258129-8d5b34bb-bc07-4f80-b610-fb25cb23c179.png)

The download button continues to be greyed out, restricting the user's ability to download the zip file.

**Comment by gildas-lormeau** [comment]
Thank you! It should be fixed now (you might need to refresh your cache)
