### ISSUE TITLE
Read zip file on macos fails

### ISSUE THREAD

**Issue by tjwelde** [gildas-lormeau/zip.js#305]
I am trying to read out filenames from a zip file.
I made a new zip file with macos default compression tool (right click bunch of files & click compress) and tried to read it with following code:

```
async function filenamesZipJs() {
  const compressed = fs.readFileSync('./Archive.zip')
  const binaryReader = new zip.Uint8ArrayReader(compressed)
  const reader = new zip.ZipReader(binaryReader)
  const entries = await reader.getEntries()
  entries.forEach((entry) => {
    console.log(entry.filename)
  })
}
```

Expected result: Log of Filenames of the files in the zip file
Actual result: Following Error:
```
(node:27563) UnhandledPromiseRejectionWarning: Error: Central directory header not found
    at ZipReader.getEntries (file:///Users/myuser/Projects/JavaScript/zipping/node_modules/@zip.js/zip.js/lib/core/zip-reader.js:157:11)
    at async filenamesZipJs (file:///Users/myuser/Projects/JavaScript/zipping/index.js:17:19)
```

Do you have any idea what might be wrong?

**Comment by gildas-lormeau** [comment]
Can you open your large zip file here? https://gildas-lormeau.github.io/zip.js/demos/demo-read-file.html
If it works then it's an issue in the code itself. I was able to open Archive2.zip in the demo so I think it's probably related to the code. Do you confirm you're using Node? If this is the case, what is the version of Node?

**Comment by gildas-lormeau** [comment]
@tjwelde I think I was able to reproduce your issue. You have to replace `fs.readFileSync('./Archive.zip')` with `new Uint8Array(fs.readFileSync('./Archive.zip'))`.

**Comment by tjwelde** [comment]
@gildas-lormeau THANKS! that fixed it. I thought I wouldn't need to do that, because `Buffer` extends `UInt8Array`. But apparently it is different.

**Comment by gildas-lormeau** [comment]
You're welcome. I guess this issue is related to the use `TypedArray.prototype.slice()`.
