### ISSUE TITLE
Error [ERR_REQUIRE_ESM] on Typescript/Node

### ISSUE THREAD

**Issue by DavideMacchia** [gildas-lormeau/zip.js#309]
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/davide/project/node_modules/@zip.js/zip.js/index.js
require() of ES modules is not supported.
require() of /home/davide/project/node_modules/@zip.js/zip.js/index.js from /home/davide/project/src/utils/zipManager.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/davide/project/node_modules/@zip.js/zip.js/package.json.

I have already tried using different imports but nothing has changed:
`import * as zip from "@zip.js/zip.js";`
`const zip = await import("@zip.js/zip.js");`
`const zip = require("@zip.js/zip.js");`

**Comment by gildas-lormeau** [comment]
I never used TypeScript so it might be complicated for me to help you. However, isn't this issue the same than this one (for example)? https://github.com/tinyhttp/milliparsec/issues/8

**Comment by DavideMacchia** [comment]
> I never used TypeScript so it might be complicated for me to help you. However, isn't this issue the same than this one (for example)? [tinyhttp/milliparsec#8](https://github.com/tinyhttp/milliparsec/issues/8)

Yes, looks like that, but they haven't solved the problem.

**Comment by gildas-lormeau** [comment]
Well, there is nothing they can do. Like zip.js, they deliver their library as an ESM-library and declare it the `package.json` file (see `"type": "module"`). It looks like it's an issue specific to tsc. Are you using `require()` in your code?

**Comment by DavideMacchia** [comment]
I was using `require()` somewhere in the code but then changed all the occurences to `await import` or cancelled to be sure wasn't affecting in some way.
I have also tryed the the `"type": "module"`into package.json but then wasimpossibile to compile TS. I have then changed settings into tsconfig file to switch to ESM but again the error was occurring.

I also tryed with Node and JS and it works fine, so the problem is on TS for sure.

**Comment by DavideMacchia** [comment]
Two error: the first one if I use ts-node to compile, the other if I don't use it.

First error:
```
/home/davide/project/node_modules/ts-node/src/index.ts:828
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS5023: Unknown compiler option 'ts-node'.

```

Second error:
```
exports.__esModule = true;
^

ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/davide/Documenti/hudi-packages-connectors/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

```

**Comment by gildas-lormeau** [comment]
These errors are not easy to interpret. I find weird that the first message is saying that `ts-node` has been passed as an "option". Isn't it supposed to be an executable instead of an "option"?

**Comment by DavideMacchia** [comment]
You are right, it was specific test with an option on ts-node. The version without the option give this result that confirm that can found the ts-node module. 
`sh: 1: ts-node: not found

Process finished with exit code 127
`

**Comment by gildas-lormeau** [comment]
It looks like you did not install `ts-node` and that this executable is required.

**Comment by DavideMacchia** [comment]
yeah I forgot to reinstall it. The error now is: 

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './test.ts'
Require stack:
- /home/davide/Documenti/hudi-packages-connectors/src/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at requireResolveNonCached (/home/davide/project/node_modules/ts-node/dist/bin.js:375:16)
    at getProjectSearchDir (/home/davide/project/node_modules/ts-node/dist/bin.js:345:40)
    at main (/home/davide/project/node_modules/ts-node/dist/bin.js:220:27)
    at Object.<anonymous> (/home/davide/project/node_modules/ts-node/dist/bin.js:405:5)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/davide/project/src/imaginaryUncacheableRequireResolveScript'
  ]
}


```

**Comment by gildas-lormeau** [comment]
It looks like you have somewhere an `import ... from "./test.ts"` which is incorrect because the file containing this import it is not the same folder that `test.ts`.

**Comment by DavideMacchia** [comment]
There is not a import of test.ts, that's the file that I use to run the project

**Comment by gildas-lormeau** [comment]
Then you might need to go into the directory where `test.ts` is located with `cd` for example before launching it.

**Comment by gildas-lormeau** [comment]
BTW, make sure you're using Node 14+.

**Comment by DavideMacchia** [comment]
Yes I was using node 16.14, btw we found a solution to the initial error: the only way is to use the library in the same file that is going to be run (test.ts in this case) and not in an external class later imported by the run class. So you are costricted to program everything in a single file.

If we found another better solution I'll add it here, otherwise I'll close the thread.

**Comment by TheNuclearNexus** [comment]
I have TypeScript working with zip,js
`tsconfig.json`
```json
{
    "compilerOptions": {
        "target": "es2021",
        "module": "es2020",
        "declaration": true,
        "outDir": "./out",
        "strict": true,
        "esModuleInterop": true,
        "moduleResolution": "node",
        "lib": [
            "es2021", "DOM"
        ],
    },
    "include": ["src"],
    "exclude": ["node_modules", "**/__tests__/*"]
}
```
`package.json`
```json
{
    "name": "slimeball",
    "main": "out/index.js",
    "types": "out/index.d.ts",
    "version": "0.0.8-5",
    "type": "module",
    "dependencies": {
        ...
    },
    "scripts": {
        ...
    },
    "files": [
        ...
    ]
}
```

**Comment by TheNuclearNexus** [comment]
only issues is that I get a blob not defined error

**Comment by gildas-lormeau** [comment]
@TheNuclearNexus Thank you very much for your help. `Blob` does not exist in Node, you have to polyfill it, see this example of code: https://github.com/gildas-lormeau/zip.js/blob/master/tests/node/test-node.js

**Comment by TheNuclearNexus** [comment]
I tried that but it doesn't seem to work

**Comment by gildas-lormeau** [comment]
That's strange, I can confirm this test runs fine on my machine.

**Comment by TheNuclearNexus** [comment]
might be an issue with typescript?

**Comment by gildas-lormeau** [comment]
I don't think it's related to TS, did you import zip.js asynchronously to make sure `globalThis.Blob` is defined? (cf. the comment in the code)

**Comment by TheNuclearNexus** [comment]
ah got it, now i get 
```
file:///B:/Projects/TypeScript/Slimeball/node_modules/@zip.js/zip.js/lib/core/zip-writer.js:588
                        fileEntry.rawFilename.length +
```

**Comment by TheNuclearNexus** [comment]
I just forgot to add `await` to my `.add()` calls :P

**Comment by gildas-lormeau** [comment]
For the record, the next version will allow importing zip.js synchonously in Node.js.
