### ISSUE TITLE
ZipInflate.append cause endless loop

### ISSUE THREAD

**Issue by i2534** [gildas-lormeau/zip.js#311]
When I read an special zip entry ( Doc_0/PublicRes.xml ), it endless loop
call stack,
ZipFileEntry.getUint8Array -> processData -> ZipInflate.append

while (z.avail_in > 0 || z.avail_out === 0)
avail_in  and avail_out  never change...

[e.zip](https://github.com/gildas-lormeau/zip.js/files/8212737/e.zip)

**Comment by gildas-lormeau** [comment]
Thank you for the report. I was able to reproduce and fix the bug. It's fixed in the version 2.4.6  I just published.
