### ISSUE TITLE
How to get list of files in zip package with password？

### ISSUE THREAD

**Issue by lxz0510** [gildas-lormeau/zip.js#315]
If I want to unzip a zip package with a password and get a list of files in the zip package, what should I do, here is the code I try to solve the above problem
<img width="577" alt="image" src="https://user-images.githubusercontent.com/57799539/158838084-59f64793-33f1-4bf2-b05e-f992ecacb6b3.png">
The value of entries is the archive, not the file list. How should I get the file?
I would be very grateful if I could get an answer

**Comment by gildas-lormeau** [comment]
You have to call Entry#getData to get the data, e.g. `await entries[0].getData()`.

**Comment by lxz0510** [comment]
> 
ok , Thanks for your answer, but I have some problems with the next step.
```
  async function getPasswdZipFiles(file, password) { 
      const reader = new zip.ZipReader(new zip.BlobReader(file) ,{password:password})
      const entries= await reader.getEntries()
      console.log('[ entries[0] ] >', entries[0])
      const entry = await entries[0].getData(new zip.BlobWriter(), { password:password })
      console.log('[entry  ] >', entry )
      await reader.close()
   }
```
Error while getting file list.
<img width="551" alt="image" src="https://user-images.githubusercontent.com/57799539/158936091-336872db-0577-4ed9-a092-be5035892fe0.png">

Can you help me get a list of files with an encrypted zip by a demo ？
I would be very grateful if I could get an answer.

**Comment by gildas-lormeau** [comment]
It looks like [`crypto.subtle`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle) is not defined in your environment. You might need to use HTTPS to run the code. Otherwise, it shouls be available with HTTP on localhost.
