### ISSUE TITLE
Using zip.js with ngrx

### ISSUE THREAD

**Issue by eafiontzi** [gildas-lormeau/zip.js#316]
Hello all.

I am trying to use zip.js and pass all entries array into an ngrx action like this

```
this.reader.getEntries().then((entries: FileEntry[]) => {
    console.log(entries);
    this.store.dispatch(myActions.request(entries));
 });
```

While in console I can see the array clearly (though I am not sure what the Pt inside each object stands for), when I pass the array to the action I get the following error 

`Cannot freeze array buffer views with elements `

Having looked [here](https://stackoverflow.com/questions/62586297/angular-ngrx-typeerror-cannot-freeze-array-buffer-views-with-elements/71484839#71484839) I tried cloning the entries object first, but unfortunately that results in losing the getData() function that I need later to retrieve the blob.

Has anyone used the library with ngrx? What exactly is the type of the Entry objects?
Thanks a lot in advance

**Comment by gildas-lormeau** [comment]
I never use ngrx but I would say that you would have to store the content of `entries` in another variable in a upper scope so that you could use it when you need to get the data.

**Comment by eafiontzi** [comment]
Thanks a lot, I used [this](https://stackoverflow.com/a/38722431/12213555) deep cloning and got the elements along with the function. Will close now.
