### ISSUE TITLE
Files created with archiver-zip-encrypted can't be decrypted

### ISSUE THREAD

**Issue by ahwitz** [gildas-lormeau/zip.js#321]
Trying to create a password-protected ZIP on the backend using Node (so I can't use this because of no Blob support) and found [this module](https://www.npmjs.com/package/archiver-zip-encrypted) to use on the back end. Run `npm install archiver archiver-zip-encrypted` then run:

```js
const fs = require("fs");
const archiver = require("archiver");
archiver.registerFormat("zip-encrypted", require("archiver-zip-encrypted"));

// create archive and specify method of encryption and password
let archive = archiver.create("zip-encrypted", {
  zlib: {level: 8},
  encryptionMethod: "aes256",
  password: "123",
});
archive.append("this is test text", {name: "file.name"});

const output = fs.createWriteStream(__dirname + "/data.zip");
archive.pipe(output);
archive.finalize();
```
Password saved as `123`, file's name is `file.name`

With command-line 7z, I get:
```
$ 7z x data.zip

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02

Scanning the drive for archives:
1 file, 198 bytes (1 KiB)

Extracting archive: data.zip
--
Path = data.zip
Type = zip
Physical Size = 198

    
Enter password (will not be echoed): # enter `123`
Everything is Ok

Size:       17
Compressed: 198
$ cat file.name
this is test text
```

In the browser, with this library, I get the following:
```js
  console.log(data.constructor.name, data.length);
  const reader = new ZipReader(new TextReader(data), {password: origin});
  const entries = await reader.getEntries(); // error on this line
  // get first entry content as text by using a TextWriter
  const decrypted = await entries[0].getData(new TextWriter());
  ```

![Screenshot from 2022-04-30 20-58-47](https://user-images.githubusercontent.com/3514397/166127678-b942ce03-e89b-4f3e-887d-b68b16f891c7.png)

There something I'm doing wrong or should this be expected to work?|

Edit: got another issue with command-line zip and finally got it working with HttpReader instead, so it's like an issue with my use of TextReader? Couldn't find any docs on how to use that in context other than just the info under "Reader constructors", which says "pass it a string", effectively.

**Comment by gildas-lormeau** [comment]
I confirm you the issue is related to the usage of the `TextReader` instance to read the zip file. You cannot use it here because a zip file file is a binary content. The `TextReader` class is typically used when you want to add (i.e. read) a text file in a new zip file with `ZipWriter`.

**Comment by ahwitz** [comment]
The way I was doing it was originally sending the ZIP over the wire, so I'd assumed any constructor would work. Fair enough. Best bet to convert it to a buffer/base64?

**Comment by gildas-lormeau** [comment]
I would recommend to use `HttpRangeReader` if your server supports the `Range` HTTP header. Otherwise, you should use `HttpReader`.
