### ISSUE TITLE
Cannot unzip .kmz files

### ISSUE THREAD

**Issue by adriatomas** [gildas-lormeau/zip.js#322]
Hello im trying to unzip a .kmz file but i get the following error:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/22915551/166890170-e2b6bc24-dcf3-40d1-988b-8cc0f362488f.png">

Before I try to unzip the file I create a Blob from the API response:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/22915551/166890495-973770aa-a809-4a5b-aeb0-ad519e66b91e.png">

Any can help me? 

BTW this is the API response:

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/22915551/166890571-438184f9-efe6-4112-8e56-946907e0c98b.png">

Response headers: 

<img width="983" alt="image" src="https://user-images.githubusercontent.com/22915551/166890610-34c834b4-5405-40ec-92ed-23cdeccd175e.png">

Thank you guys.

**Comment by gildas-lormeau** [comment]
Are you able to open the kmz file here: https://gildas-lormeau.github.io/zip.js/demos/demo-read-file.html or does the demo show the same error?

**Comment by gildas-lormeau** [comment]
I did a test with this file https://example-files.online-convert.com/misc/kmz/example.kmz and it works fine for me so I'm closing this issue. Feel free to give more details if needed.
