### ISSUE TITLE
Expose mimeTypes

### ISSUE THREAD

**Issue by Sharcoux** [gildas-lormeau/zip.js#327]
Would you be ok to export the mimeTypes variable from mime-types.js file? If not publicly, at least export it from the file so we can import it. On mobile, we rely on a filePicker that requires us to pass all the `images/*` or `audio/*` mime types. We would like to manipulate the object to retrieve those. We don't mind importing it from `'@zip.js/zip.js/dist/...`

**Comment by Sharcoux** [comment]
Thanks a lot! ❤️

**Comment by gildas-lormeau** [comment]
You're welcome!
