### ISSUE TITLE
import Deflate from "./lib/core/codecs/deflate.js";    SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Wal1e** [gildas-lormeau/zip.js#329]
node : 14.17.6
![image](https://user-images.githubusercontent.com/20591468/172593307-63e42679-3c7e-4ac2-a71c-9608dfafb58c.png)

**Comment by Wal1e** [comment]
I imported zip.js according to the documentation, but compile error
`import * as zip from "@zip.js/zip.js";`

**Comment by gildas-lormeau** [comment]
Is your version of zip.js up to date? The line 31 in `index.js` does not contain this code, see below.

https://github.com/gildas-lormeau/zip.js/blob/458f115aee066e2793df6ff5137fe0a5f7dc59c6/index.js#L31

**Comment by Wal1e** [comment]
thank you for your comment, i saw my zip.js. it's version is  2.4.12,  please see below
![image](https://user-images.githubusercontent.com/20591468/172606474-12d87ab4-f1cf-4750-b71f-2a228e7b4d95.png)

**Comment by Wal1e** [comment]
setting "type": "module" in my project's package.json and makes it

**Comment by gildas-lormeau** [comment]
Thank you for the feedback!
