### ISSUE TITLE
Typescript error 'Generators are not allowed in an ambient context'

### ISSUE THREAD

**Issue by sbschorer** [gildas-lormeau/zip.js#332]
Starting with v.2.1.13 I get a Typescript compile error:
```
Error: node_modules/@zip.js/zip.js/index.d.ts:109:9 - error TS1221: Generators are not allowed in an ambient context.
109 *getEntriesGenerator(options?: ZipReaderGetEntriesOptions): AsyncGenerator<Entry, boolean>;
```

Typescript does not allow the symbol `*` in `d.ts` files. Instead, just remove the asterisk and simple write:
`getEntriesGenerator(options?: ZipReaderGetEntriesOptions): AsyncGenerator<Entry, boolean>;`

The return type already defines that the method is a generator method.

You can try it in the [Typescript Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAECiAeYC2AHEBTaBvAsAKGmgCoBzdAO3QCcwAXAeyoAoBKbAX33aA) and have a look on the generated `D.TS` file.

**Comment by gildas-lormeau** [comment]
Thank you! I just released the version 2.4.15 which fixes this issue.
