### ISSUE TITLE
"async* getEntriesGenerator" throw error when webpack build

### ISSUE THREAD

**Issue by Brandon-Xu** [gildas-lormeau/zip.js#334]
Hi,
I used cesium with zip.js, when I run `yarn build`，I got this.
It seemed like throwing by function `getEntriesGenerator` with `*`
I googled everything what I can, but got nothing.

ERROR in ./node_modules/cesium/Source/ThirdParty/zip.js
Module parse failed: Unexpected token (6897:6)
You may need an appropriate loader to handle this file type.
6895 |       }
6896 |
6897 |       async* getEntriesGenerator(options = {}) {
6898 |               const zipReader = this;
6899 |               const reader = zipReader.reader;

**need help >.<**

Environment: 
Windows 11
nodejs@14.17.6
npm@6.14.15
Cesium@1.94.3
webpack@3.6.0

**Comment by gildas-lormeau** [comment]
What version of webpack are you using?

**Comment by Brandon-Xu** [comment]
> 

3.6.0

**Comment by Brandon-Xu** [comment]
> What version of webpack are you using?

3.6.0

**Comment by gildas-lormeau** [comment]
Async generators is a feature of ES2018. Did you try to update the "presets" in the babel part?

**Comment by Brandon-Xu** [comment]
> Async generators is a feature of ES2018. Did you try to update the "presets" in the babel part? Otherwise you could use zip.js 2.4.12. This is the last version that does not use this feature.

thanks. closed
