### ISSUE TITLE
How to make IntelliSense work with Deno?

### ISSUE THREAD

**Issue by SettingDust** [gildas-lormeau/zip.js#335]
I import from `https://raw.githubusercontent.com/gildas-lormeau/zip.js/master/index.js`
But the `Entry` not export it attrs.

Edit:
- [x] https://github.com/denoland/deno/discussions/14902

**Comment by gildas-lormeau** [comment]
I'm sorry but I don't understand the issue.

**Comment by gildas-lormeau** [comment]
I'm sorry but I still don't understand the issue.

**Comment by SettingDust** [comment]
> I'm sorry but I still don't understand the issue.

I don't know how to import the index.js in deno correctly. The github raw won't provide info of type declaration. So the types isn't available

**Comment by SettingDust** [comment]
It's fine with a local file which `declare module "https://raw.githubusercontent.com/gildas-lormeau/zip.js/master/index.js"` or add `// @deno-types="./zip.js.d.ts"`(not declare module. But the classes can't be refered) before import.

**Comment by gildas-lormeau** [comment]
The problem is that I don't know to make the 2 syntaxes cohabit, the one that pleases deno and the one that pleases Node.js.

**Comment by SettingDust** [comment]
Node needn't declare module I think. Just declare namespace, functions, etc. and declare the type file in package.json
https://github.com/ndaidong/article-parser/blob/main/index.d.ts

**Comment by gildas-lormeau** [comment]
Thank you for the info, I'm going to do some tests ;)

**Comment by gildas-lormeau** [comment]
I published the version 2.4.16 with the module declaration removed. The autocomplete works for Node.js but not for Deno on my end in VSCode.

**Comment by gildas-lormeau** [comment]
I'm reopening the issue since I don't really know if it's fixed.

**Comment by SettingDust** [comment]
After add `/// <reference types="./index.d.ts" />` to the top of `index.js`. The completion is working in webstorm.
![图片](https://user-images.githubusercontent.com/19922286/174420013-418955f0-a9d6-4ca6-8036-c97390de1154.png)
But I can't jump to the type declaration and there isn't popup(will show it's signature) of fields or functions.
It's shows the signature in javascript file instead of types file. And the type of `Entry` even not display.
![图片](https://user-images.githubusercontent.com/19922286/174420124-e81eaffc-a98c-405d-81d6-b79ded89601b.png)

**Comment by SettingDust** [comment]
- [ ] https://github.com/denoland/deno/discussions/14902

**Comment by SettingDust** [comment]
https://github.com/denoland/deno/discussions/14902#discussioncomment-2975178

> As you mentioned in [gildas-lormeau/zip.js#335 (comment)](https://github.com/gildas-lormeau/zip.js/issues/335#issuecomment-1159348236), adding `/// <reference types="./index.d.ts" />` to the top of `index.js` fixes typing on Deno, you should go ahead and contribute that change. Beyond that is a problem with the webstorm extension.

**Comment by gildas-lormeau** [comment]
Thank you very much for your help @SettingDust ! I confirm it works fine now with the version 2.4.18 :)
