### ISSUE TITLE
ReadableStreamReader causing compile error, missing type

### ISSUE THREAD

**Issue by stanleydunneGMAIL** [gildas-lormeau/zip.js#337]
Error: node_modules/@zip.js/zip.js/index.d.ts:181:71 - error TS2314: Generic type 'ReadableStreamReader<Type>' requires 1 type argument(s).

181     public add<ReaderType>(name: string, reader: Reader<ReaderType> | ReadableStreamReader | null, options?: ZipWriterAddDataOptions): Promise<Entry>;
                                                                          ~~~~~~~~~~~~~~~~~~~~

**Comment by gildas-lormeau** [comment]
Thank you and sorry for the inconvenience, it's fixed in the version 2.4.24 I just published.
