### ISSUE TITLE
BlobWriter mime type not present after 2.6.16

### ISSUE THREAD

**Issue by Jyrka98** [gildas-lormeau/zip.js#360]
Possibly caused by the following commit [e467d8e](https://github.com/gildas-lormeau/zip.js/commit/e467d8e56541ac04539d64be5afc23ff123e6c50#diff-440eed3dc557244bf594310c7a97bc61d155b999e7643deedd534b6c6212ee6eR248), as Response.blob() doesn't accept any parameters as per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Response/blob#parameters)

Using the example from the [ZipWriter](https://gildas-lormeau.github.io/zip.js/api/classes/ZipWriter.html) docs, with the addition of `console.log(blob.type)`, results in the default [empty string](https://developer.mozilla.org/en-US/docs/Web/API/Blob/type#value)

**Comment by gildas-lormeau** [comment]
Thank you very much! It's fixed in the version 2.6.23 that I just published.
