### ISSUE TITLE
Not working in Node.js 16.13.0

### ISSUE THREAD

**Issue by hornta** [gildas-lormeau/zip.js#376]
I'm getting this error when running this package in Node.js 16.13.2

```
ReferenceError: TransformStream is not defined
```

Version: 2.6.50

It looks like TransformStream was introduced in version 16.5.0 so I expect it should work. This is my code:

```ts
import { BlobReader, ZipReader } from "@zip.js/zip.js";

export const loadXlsx = async (data: Blob) => {
  const zipFileReader = new BlobReader(data);
  const zipReader = new ZipReader(zipFileReader);
  const entries = await zipReader.getEntries()
  for(const entry of entries) {
    console.log({ entry: entry.filename, directory: entry.directory })
  }
  await zipReader.close();
}
```

**Comment by hornta** [comment]
Closing. I tested version 18 of node and it works so I guess the MDN documentation was lying to me: 
![image](https://user-images.githubusercontent.com/4553604/197333252-a0ad4b85-90e6-4115-ba35-b8ab21c58078.png)

**Comment by gildas-lormeau** [comment]
Actually, the implementation exists in Node.js 16.18.0 but it is not exposed via the `globalThis` object. See https://nodejs.org/docs/latest-v16.x/api/webstreams.html#class-transformstream.
