### ISSUE TITLE
Error while type checking with dnt

### ISSUE THREAD

**Issue by gauthier-th** [gildas-lormeau/zip.js#382]
Hi, thanks for this great library 😉
I'm trying to build my Deno project to publish it on NPM, but i have the following error during the type checking of dnt:
```
src/deps/deno.land/x/zipjs@v2.6.57/lib/core/streams/codecs/sjcl.js:53:1 - error TS9005: Declaration emit for this file requires using private name 'sha1'. An explicit type annotation may unblock declaration emit.
```
Do you have any idea to solve this issue?

**Comment by gildas-lormeau** [comment]
I don't know what dnt is. However I suspect this issue is related to the fact that a class was not ported into ES6 class. The last version that I've just published fixes this issue. Can you tell me if it's OK on your end?

**Comment by gauthier-th** [comment]
Yep, no more error, thanks!

**Comment by gildas-lormeau** [comment]
You're welcome :)
