### ISSUE TITLE
When trying to use with meteorjs it seems to modify the global package variable

### ISSUE THREAD

**Issue by imdark** [gildas-lormeau/zip.js#393]
even just 
```
require('@zip.js/zip.js')
```
will cause everything to crash
Uncaught SyntaxError: Cannot use 'import.meta' outside a module (at modules.js?hash=886c0c85d0b952d506ded4b863a6b4c16b334665:105718:19)
react-fast-refresh.js?hash=2d2cfb538903e27f542f73469113bb56a27e2a7e:17 Uncaught TypeError: Cannot read properties of undefined (reading 'meteorInstall')
    at react-fast-refresh.js?hash=2d2cfb538903e27f542f73469113bb56a27e2a7e:17:37
    at react-fast-refresh.js?hash=2d2cfb538903e27f542f73469113bb56a27e2a7e:982:3
(anonymous) @ react-fast-refresh.js?hash=2d2cfb538903e27f542f73469113bb56a27e2a7e:17
(anonymous) @ react-fast-refresh.js?hash=2d2cfb538903e27f542f73469113bb56a27e2a7e:982

**Comment by gildas-lormeau** [comment]
You're trying run the library outside an ECMAScript Module but you did not build the library in order to do so.

**Comment by imdark** [comment]
I just did a meteor npm install which works for most other libraries, how would i go about building to not be a module

**Comment by gildas-lormeau** [comment]
How do you import zip.js in your project?

**Comment by imdark** [comment]
By doing, npm install and calling  require('@zip.js/zip.js')

**Comment by gildas-lormeau** [comment]
If you use `require`, you should write `const zip = require("@zip.js/zip.js/index.cjs");` as documented here: https://gildas-lormeau.github.io/zip.js/.
