### ISSUE TITLE
Naming scheme

### ISSUE THREAD

**Issue by sugoidesune** [gildas-lormeau/zip.js#398]
Yo who came up with using a reader for writing files inside a writer
```js
await zipWriter.add("hello.txt", helloWorldReader);
```

and a writer for reading files coming from a reader:

```js
const firstEntry = (await zipReader.getEntries()).shift();
const helloWorldText = await firstEntry.getData(helloWorldWriter);
```

Whichever way you think about it atleast keep it consistent!
Put readers into readers and writers into writers. 

```js
await zipWriter.add("hello.txt", helloWorldWriter);
```

**Comment by gildas-lormeau** [comment]
Thank you for your future contributions.
