### ISSUE TITLE
Entry#getData not work since from v2.6.24 on Android System WebView

### ISSUE THREAD

**Issue by liuwin7** [gildas-lormeau/zip.js#400]
Operation system: Android 10.0

Browser: Android system WebView 74 or 79

Description: 
After call the `Entry.getData()`, there is nothing callback.
```ts
  const data = await entry.getData!(new BlobWriter());
```

From the release notes, the `transferStreams ` was introduced from v2.6.24,  is that why?

**Comment by liuwin7** [comment]
Nothing at all on Android system WebView 74, but, `Fetch failed` will be thrown on  the 79.
I added the `EntryDataOnprogressOptions`, `onstart` \ `onprogress` \ `onend`, the callbacks will be called but there is no value from the callback function.

**Comment by liuwin7** [comment]
Yes, I have tried.

**Comment by liuwin7** [comment]
Hi, I forked the project and run the web test on the Android 10.0 emulator shipped with the Chrome v74.
Many errors had been thrown.
```ts
Uncaught (in promise) TypeError: blob.arrayBuffer is not a function
```
According the [Blob.arrayBuffer](https://developer.mozilla.org/zh-CN/docs/Web/API/Blob/arrayBuffer), the function `arrayBuffer` need the minimum version is 76.
```ts
Uncaught (in promise) TypeError: Object.hasOwn is not a function
```
According the [Object.hasOwn](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn) function `hasOwn` needs 93+.

**Comment by liuwin7** [comment]
Ok, this is indeed a compatibility issue, however, the incompatibility is not in the APIs `blob.arrayBuffer` `Object.hasOwn` above, but the `WritableStream`.
`WritableStream.close` must be 81 and above, if it is lower than this version, `WritableStream` dose not work, the `close` function will not been called.

**Comment by gildas-lormeau** [comment]
It can be polyfilled, see https://www.npmjs.com/package/web-streams-polyfill. I tested it and it works fine.

**Comment by liuwin7** [comment]
When disable web workers, an error will occur.
```ts
writable.close is not a function
```
