### ISSUE TITLE
Add 'lib/*' to package.json exports

### ISSUE THREAD

**Issue by TJKoury** [gildas-lormeau/zip.js#410]
Working with versions > 2.5 has given me headaches as I am used to being able to import everything in [this directory](https://github.com/gildas-lormeau/zip.js/tree/master/lib) right into my code.  Now I get the "./lib/xxxxxx.js' path is not exported" error.

Some large / very well known packages like [Cesium](https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/DataSources/exportKml.js#L23) use this pattern.

**Comment by gildas-lormeau** [comment]
People using zip.js could contact me if they have an issue with the library. I can fix them sometimes.

This issue should be fixed in the version `2.7.3` I've just published.

**Comment by TJKoury** [comment]
That was quick!  Thanks so much

**Comment by gildas-lormeau** [comment]
You're welcome!
