### ISSUE TITLE
Possible to get a WritableStream handle to add file?

### ISSUE THREAD

**Issue by gizahNL** [gildas-lormeau/zip.js#411]
Is it possible to create a WritableStream when adding a file? 

I have a ton of ReadableStreams (from response.body) that need to be concatted into a single file that needs to be made part of a zip. Having a WritableStream would allow me to simply pipe my readable streams into the file.

**Comment by 0f-0b** [comment]
You can get a pair of readable and writable streams from a transform stream.

```js
const { readable, writable } = new TransformStream();
(async () => {
  for (const body of responseBodies) {
    await body.pipeTo(writable, { preventClose: true });
  }
  await writable.close();
})();
await zipWriter.add("concatenated_files", { readable });
```

[Another example from the spec](https://streams.spec.whatwg.org/#example-transform-identity).

**Comment by gizahNL** [comment]
Thanks, I think that should work :)
