### ISSUE TITLE
Files within encrypted zip are visible even with wrong password

### ISSUE THREAD

**Issue by trock-broadinst** [gildas-lormeau/zip.js#415]
I was recently experimenting with the password-encrypted winzip aes funcitonality this library provides, however I've noticed that even when the wrong password is provided, the files within the zip can still be seen. Aside from zipping the files, then externally encrypting the resulting blob, is there any way to prevent the zip filestructure from being read by unauthenticated openers?

**Comment by gildas-lormeau** [comment]
You want what is called "Central Directory Encryption" which is patented, see https://stackoverflow.com/questions/58394110/pkware-zip-central-directory-encryption.

**Comment by trock-broadinst** [comment]
hah! that's real rich, thanks for the prompt response, let's hope the patent expires soon

**Comment by gildas-lormeau** [comment]
You're welcome, I hope indeed that zip.js will still be maintained when it expires ;)
