### ISSUE TITLE
nodejs v16.16.0 [BUG] CommonJS require!

### ISSUE THREAD

**Issue by gowy222** [gildas-lormeau/zip.js#418]
"@zip.js/zip.js": "^2.7.14",

I tried:
const zip = require("@zip.js/zip.js");
ERR:
class Crc32Stream extends TransformStream {
                          ^
ReferenceError: TransformStream is not defined

----------
also  tried:
require.resolve('@zip.js/zip.js/dist/zip-fs-full.min.js');  =>'./dist/zip-full.min.js' is not defined by "exports"

-----------
I wanna to addup zip to my project, fully CommonJS  type! can NOT change package.json module type, cus a big project within 30+ CommonJS packages,...
any idea to use require() in nodejs ?

**Comment by Rajek88** [comment]
Did you find the solution ?

**Comment by gildas-lormeau** [comment]
@Rajek88 update Node.js.
