### ISSUE TITLE
compressing a file of ~100MB gives incomplete zip file

### ISSUE THREAD

**Issue by jokester** [gildas-lormeau/zip.js#42]
Got an incomplete zip file of 100 bytes, when I tried to compress a ~100MB xml file via temporary storage in RAM.

It seems only zip header(PK~) / filename are there, not compressed date itself.

Didn't observe exception in browser console or demo page.

I can reproduce it by:

```
1. open http://gildas-lormeau.github.com/zip.js/demos/demo1.html  , with chromium 25.0.1364.172 (187217)
2. add the 100MB file when RAM is chosen for temp storage
3. wait till finish, and click "download".
```

By the way, a few tests
- For ~50MB file, temporary storage at RAM still works
- For ~500MB file, temporary storage at HDD still works

Any idea about the real threshold?

**Comment by gildas-lormeau** [comment]
This bug is fixed in Chrome 42.
