### ISSUE TITLE
[QUESTION] How does one mock zip.js in Jest tests?

### ISSUE THREAD

**Issue by remarkablemark** [gildas-lormeau/zip.js#421]
I'm using `zip.js` in my frontend project and I'm trying to write Jest tests but they're failing with:

```
    ReferenceError: TransformStream is not defined

    > 1 | import { BlobReader, BlobWriter, ZipWriter } from '@zip.js/zip.js';
        | ^
```

I'm using `jsdom` for my test environment.

Is the best way to resolve this is to [mock the node module](https://jestjs.io/docs/manual-mocks#mocking-node-modules)? I have seen other projects provide a [mock file for Jest](https://github.com/stripe/stripe-react-native#testing).

**Comment by gildas-lormeau** [comment]
Depending on the Nodejs version, you could simply inject the code below to circumvent this issue.

```js
import { TransformStream } from "node:stream/web";

globalThis.TransformStream = TransformStream
```

**Comment by remarkablemark** [comment]
Thanks! I ended up creating a module mock for the package:

```sh
mkdir -p __mocks__/@zip.js/
echo "module.exports = {};" > __mocks__/@zip.js/zip.js.js
```
