### ISSUE TITLE
[Compatibility issues] parameter initialization

### ISSUE THREAD

**Issue by nenge123** [gildas-lormeau/zip.js#429]
```
class  {
    constructor(options={}){ ...}
}
```
Some packaged OEM browsers do not support. like "Tencent QQ mobile browser","WeChat browser"

```
class  {
    constructor(options){options=options||{}; ...}
}
```

**Comment by gildas-lormeau** [comment]
This feature has been introduced 8 years ago in ES2015. You should use babel to build your project. I am sorry but I have no intention of making the library compatible in such old environments.

**Comment by gildas-lormeau** [comment]
BTW, I already provide a script to fix this issue. You just have to fork the project and follow the instructions in the comments here: https://github.com/gildas-lormeau/zip.js/blob/master/rollup-es5.config.js
