### ISSUE TITLE
The sendErrorMessage function is called with undefined.

### ISSUE THREAD

**Issue by negezor** [gildas-lormeau/zip.js#439]
Hi, I've discovered an intermittent bug that is only fixed by reloading the browser.
```
Uncaught (in promise) TypeError: Cannot destructure property 'message' of 'e' as it is undefined.
    at Pe (49d3298e-9912-4393-a26f-6a7894623a15:1:13914)
    at De (49d3298e-9912-4393-a26f-6a7894623a15:1:13750)
Pe @ 49d3298e-9912-4393-a26f-6a7894623a15:1
De @ 49d3298e-9912-4393-a26f-6a7894623a15:1
await in De (async)
(anonymous) @ 49d3298e-9912-4393-a26f-6a7894623a15:1
```
![image_2023-08-07_19-58-01](https://github.com/gildas-lormeau/zip.js/assets/9392723/c56e6090-10ba-499d-9b32-8a6732164586)
The only place I found in the code that refers to this error is here

https://github.com/gildas-lormeau/zip.js/blob/4ab1265c570f9508d35a72b36dc56810e54ef58c/lib/core/z-worker-core.js#L127-L129

Versions
@zip.js/zip.js: `2.7.20`
Chrome: `115.0.5790.171`

**Comment by gildas-lormeau** [comment]
Thank you for the report. I added a default value for the parameter passed to `sendErrorMessage()`.
