### ISSUE TITLE
Provide `zip.esm.min.js`

### ISSUE THREAD

**Issue by rwv** [gildas-lormeau/zip.js#441]
Could you please provide a `zip.esm.min.js` in `dist/`? `index.js` is `esm` but not suitable for browser usage.

**Comment by gildas-lormeau** [comment]
I added it in the version `2.7.22`.

**Comment by rwv** [comment]
> What do you mean by "not suitable for browser usage"? Here is a demo which imports `index.js` and works fine in browsers: https://jsfiddle.net/dns7pkxt/

`index.js` is not bundled and minified. In browser environment this will have multiple http request and increase latency.

**Comment by gildas-lormeau** [comment]
In 2023, as a library provider and even though I added the minified modules in the project, I consider I am not supposed to provide a bundled ES module. You're supposed, as an integrator, to do this job via the toolchain of your application.

**Comment by rwv** [comment]
My use case is to import @zip.js/zip.js directly in browser from public CDN like JsDelivr, increase performance and cache can be shared across sites. But you’re right, this is a niche case. Thank you again for creating such a wonderful project!

**Comment by gildas-lormeau** [comment]
You're welcome and thank you for your continued support!

I agree that HTTP/3 and QUIC are not yet sufficient to solve this issue, unfortunately. I hope that in the future, no one will have to use bundlers, like in the 90s :)
