### ISSUE TITLE
addUint8Array is not a function

### ISSUE THREAD

**Issue by jobisoft** [gildas-lormeau/zip.js#448]
This is an awesome library, thanks for creating this exceptional piece of code.

While playing around with it, I found that `fs.addUint8Array`  is not available. I had to add an entry here, similar to addBlob:
https://github.com/gildas-lormeau/zip.js/blob/master/lib/core/zip-fs-core.js#L535-L537

**Comment by gildas-lormeau** [comment]
Thank you very much for the kind words and the bug report. I confirm that it was an unfortunate oversight, it's fixed in version `2.7.28` that I've just released.
