### ISSUE TITLE
The extracted file size and the archive header information are different

### ISSUE THREAD

**Issue by sunclx** [gildas-lormeau/zip.js#453]
When I open the zip file producted by `zip.js` with bandzip, it report error "The extracted file size and the archive header information are different".
![](https://github.com/sunclx/pics/blob/main/2023-10-06%20161559.png?raw=true)

**Comment by gildas-lormeau** [comment]
Unfortunately, I have absolutely no idea of what "header identification information" is. When I run `7z t` with a file compressed with [this demo](https://gildas-lormeau.github.io/zip-manager/), everything looks fine.

```
t test-integ.zip 

7-Zip [64] 17.05 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.05 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs LE)

Scanning the drive for archives:
1 file, 4143058 bytes (4046 KiB)

Testing archive: test-integ.zip
--
Path = test-integ.zip
Type = zip
Physical Size = 4143058

Everything is Ok

Files: 4
Size:       6384084
Compressed: 4143058
```

**Comment by gildas-lormeau** [comment]
How did you create your zip file?

**Comment by sunclx** [comment]
By `cli-deno` command.

**Comment by gildas-lormeau** [comment]
I cannot reproduce the issue. On my end, the demo always generate a zip file that does not end with NUL characters. I use https://hexed.it/ to check the content.

**Comment by sunclx** [comment]
deno --version 
`deno 1.37.1 (release, x86_64-pc-windows-msvc)
v8 11.8.172.6
typescript 5.2.2
`
command:
` deno run -A clie-deno/mc-zip.js out.zip C:\dev\scripts`

**Comment by gildas-lormeau** [comment]
I'm still unable to reproduce the issue when I run `deno run mc-zip.js test.zip ..\` from the `cli-deno` folder. The zip file is weighting `30 459 859` bytes and is valid.

```
deno --version
deno 1.37.1 (release, x86_64-pc-windows-msvc)
v8 11.8.172.6
typescript 5.2.2
```

**Comment by sunclx** [comment]
I  try in anthor PC, and the issue happend again. I run `deno run mc-zip.js test.zip ..\`  from the `cli-deno` folder on Windows 11. When I unzip the `test.zip` file, I find that  the files size  is differnet from original and the size is multiples of 64k. 
![](https://github.com/sunclx/pics/blob/main/2023-10-07%20211446.png?raw=true)

**Comment by sunclx** [comment]
When I set the option `useWebWorkers` to `false`, the issue disappear. Maybe there is a bug in Deno Web Workers.

**Comment by gildas-lormeau** [comment]
That's weird because I did several tests and I cannot reproduce the issue at all on Windows.
