### ISSUE TITLE
Security - CRITICAL - Unsafe dynamic method access

### ISSUE THREAD

**Issue by Gaetanbrl** [gildas-lormeau/zip.js#471]
Hi,

According to CodeQL scan, z-worker return a CRITICAL issue.

See https://github.com/mviewer/mviewer/security/code-scanning/23 to get more details.

**Comment by gildas-lormeau** [comment]
The link returns a 404.

**Comment by Gaetanbrl** [comment]
Yes, sry, it's private security page. GitHub return 404, i will share a screen capture.

![image](https://github.com/gildas-lormeau/zip.js/assets/16317988/b4ea9518-4bb8-4118-b7d7-428e199e53e9)

**Comment by Gaetanbrl** [comment]
Our project use zip.js lib, and a security scan return this alert.

**Comment by gildas-lormeau** [comment]
This line of code is related to the legacy version of zip.js. It is only found in the previous version of the documentation, see https://github.com/gildas-lormeau/zip.js/blob/gh-pages/old-docs/demos/z-worker.js#L45. This code is not used in the current version of zip.js.

**Comment by Gaetanbrl** [comment]
ok thanks.

I will upgrade. Do you know from wich version of zip.js this code come from ?

https://raw.githubusercontent.com/mviewer/mviewer/master/demo/addons/fileimport/lib/zip.js

**Comment by gildas-lormeau** [comment]
This is the old version of zip.js. FYI, here is the last commit of this version: https://github.com/gildas-lormeau/zip.js/tree/3e7920810f63d5057ef6028833243105521da369.

**Comment by Gaetanbrl** [comment]
Ok Thanks. Weird to have too old lib (external contribution)... need real update of zip.js in my project.
I close.
Thx.

**Comment by gildas-lormeau** [comment]
You're welcome!

Kenavo
