### ISSUE TITLE
Publish zip.js to the JSR

### ISSUE THREAD

**Issue by lino-levan** [gildas-lormeau/zip.js#506]
As part of my process of porting [Astral](https://github.com/lino-levan/astral) to the [JSR](https://jsr.io), and this is the last remaining dependency that remains unpublished. Is there any chance this could be published to the JSR as well as deno.land/x and npm?

**Comment by gildas-lormeau** [comment]
Well, it's already published to the JSR, see https://jsr.io/@zip-js/zip-js

**Comment by lino-levan** [comment]
Ah, I somehow missed that. Sorry for the trouble!

**Comment by gildas-lormeau** [comment]
No problem ;)
