### ISSUE TITLE
Error in compiled deno executable

### ISSUE THREAD

**Issue by Mutefish0** [gildas-lormeau/zip.js#519]
When running deno executable, the following error occurs:
```js
error: Uncaught (in worker "") Module not found: blob:null/d75b07ad-f560-48f7-ad16-ec44df0eaca3
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:168:7)
```
Because Deno's Worker does not support blob URLs after being compiled into an executable file, there is the issue: https://github.com/denoland/deno/issues/23431

As suggested, can we use a base64 encoded data URL instead of a blob URL since both can work?

https://github.com/gildas-lormeau/zip.js/blob/969f6589f3a979a9ed7eb6c6dfa8e32f8c51a62a/lib/z-worker-inline-template.js#L37

for example:
```ts
const uri = () => `data:text/javascript;base64,${btoa(__workerCode__)}`;
```

**Comment by gildas-lormeau** [comment]
I've just published a new version 2.7.46 which adds the export `data-uri`. So, you just have to import `@zip-js/zip-js/data-uri` to fix the issue with the compiled code.
