### ISSUE TITLE
Export Issues

### ISSUE THREAD

**Issue by salivity** [gildas-lormeau/zip.js#525]
Hiya, im in the middle of creating an online zip file manager and im having difficulties exporting a zip file using FS.exportBlob() function that has Entry encrypted previously through FS.exportBlob() as it requires all the password to be re-entered into each encrypted Entry before attempting to export. This seems very pointless i believe that FS.exportBlob() should ignore encrypted Entry and just export as normal.

i get the Error "File contains encrypted entry" i don't see the point of this error

**Comment by gildas-lormeau** [comment]
If I understand correctly, you want compressed (and possibly encrypted) data to be transferred as is. This feature does not exist today. I've just added the `passThrough` option in `ZipReader` to read the raw data. I still need to code the same option in `ZipWriter` in order to use it in the `FS` API. It's a little more complicated because some additional data, such as the size of the decompressed file or the information for extra-field AES, must also be passed as an option. I'll try to look into this in the next few days.

For the record, here is below an example of test code for testing the complete feature (i.e. support of the option `passThrough` in `ZipWriter`).

```js
/* global Blob */

import * as zip from "../../index.js";

const TEXT_CONTENT = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.";
const FILENAME = "lorem.txt";
const BLOB = new Blob([TEXT_CONTENT], { type: zip.getMimeType(FILENAME) });

export { test };

async function test() {
	zip.configure({ chunkSize: 128, useWebWorkers: true });
	let blobWriter = new zip.BlobWriter("application/zip");
	let zipWriter = new zip.ZipWriter(blobWriter, { password: "password", encryptionStrength: 3 });
	await zipWriter.add(FILENAME, new zip.BlobReader(BLOB));
	await zipWriter.close();
	let zipReader = new zip.ZipReader(new zip.BlobReader(await blobWriter.getData()));
	let entries = await zipReader.getEntries();
	let data = await entries[0].getData(new zip.BlobWriter(), { passThrough: true });
	await zipReader.close();
	await zip.terminateWorkers();
	if (data.size != entries[0].compressedSize) {
		throw new Error();
	}
	blobWriter = new zip.BlobWriter("application/zip");
	zipWriter = new zip.ZipWriter(blobWriter);
	await zipWriter.add(FILENAME, new zip.BlobReader(data), { passThrough: true });
	await zipWriter.close();
	zipReader = new zip.ZipReader(new zip.BlobReader(await blobWriter.getData()));
	entries = await zipReader.getEntries();
	data = await entries[0].getData(new zip.BlobWriter(), { password: "password" });
	await zipReader.close();
	await zip.terminateWorkers();
	if (data.size != TEXT_CONTENT.length) {
		throw new Error();
	}
}
```

**Comment by gildas-lormeau** [comment]
I've added the support of `passThrough` option in the FS API on the `master` branch. It would be great if you could provide me some feedback before releasing the new version. Here is below a basic example showing how to use it.

https://github.com/gildas-lormeau/zip.js/blob/e1821bd1fa19d2cceae9e4f718433309e754bb0a/tests/all/test-fs-passthrough.js#L1-L22

**Comment by salivity** [comment]
Needs publishing can't get latest version

**Comment by salivity** [comment]
passThrough creates corrupt files and does not work, I published my tool at https://davidclews.com/article/40.html not using passThrough. There is alot more features im going to add like read only mode and file blob previews, using intersection observer while scrolling.

**Comment by gildas-lormeau** [comment]
Could you **please** provide more details about the issue? "It does not work" is obviously insufficient. The same applies to the first message in the issue which is very vague. If you're a Full Stack Web Developer, please provide some code showing the issue, this is how you are supposed to do.

**Comment by gildas-lormeau** [comment]
I fixed a bug meanwhile. Maybe this will fix the issue you encountered.

**Comment by salivity** [comment]
I think you misinterpreted what i meant, i was looking for a way to export an entire archive with password protected entries that has been imported with different passwords without manually entering each and every password per entry. There is currently no way to ignore the entries with password protected files while exporting an entire zip archive. Someone may wish to add a single entry to an archive without entering all the password per Entry from pre existing content. as export will be blocked by an exception. There could be many thousands of passwords per file which would be inefficient for users and would reduce the Quality of Service.

**Comment by salivity** [comment]
It seems to be working now i was using the wrong version of repo

**Comment by gildas-lormeau** [comment]
I'm glad to hear it fulfills your needs.
