### ISSUE TITLE
checkPasswordOnly is not marked as optional but mandatory in ZipReaderOptions

### ISSUE THREAD

**Issue by Scarabol** [gildas-lormeau/zip.js#526]
Thank you all for this great library! I appreciate using it in my project. I just updated my version from `2.7.47` to `2.7.51` and noticed that this line was added https://github.com/gildas-lormeau/zip.js/blob/v2.7.51/index.d.ts#L809 with mandatory field `checkPasswordOnly: boolean;` and default value `false`.

I'd expect that the field is marked as optional like `checkPasswordOnly?: boolean;`, as all other fields are optional and the default value is `false` anyway.

What do you think? Is it worth to specify the value in my code or can you make it optional?

**Comment by gildas-lormeau** [comment]
Thank you very much for the kind words and thank you also for the bug report. It's indeed an error on my part, the property should be optional. I've fixed the issue, the fix will be available in the next version.

**Comment by gildas-lormeau** [comment]
For the record, the version [v2.7.52](https://github.com/gildas-lormeau/zip.js/releases/tag/v2.7.52) should fix the issue.
