### ISSUE TITLE
Does not support trailing descriptor (informal) signatures

### ISSUE THREAD

**Issue by simonbuchan** [gildas-lormeau/zip.js#539]
As described in APPNOTE.TXT:

> 4.3.9.3 Although not originally assigned a signature, the value
>         0x08074b50 has commonly been adopted as a signature value
>         for the data descriptor record.  Implementers SHOULD be
>         aware that ZIP files MAY be encountered with or without this
>         signature marking data descriptors and SHOULD account for
>         either case when reading ZIP files to ensure compatibility.

In other words, the local entry for such files looks like:

```
[header...] [data...] "PK\7\8" crc32  compressed_size uncompressed_size
```

The AWS CloudFormation resource schema is (currently?) an example of such a file: https://schema.cloudformation.us-east-1.amazonaws.com/CloudformationSchema.zip

**Comment by simonbuchan** [comment]
Same issue in `jsr:@quentinadam/zip`: https://github.com/quentinadam/deno-zip/issues/1

**Comment by gildas-lormeau** [comment]
You have to set the option `dataDescriptorSignature` to `true`, see https://gildas-lormeau.github.io/zip.js/api/interfaces/ZipWriterConstructorOptions.html#dataDescriptorSignature.
