### ISSUE TITLE
Some possible problem in ZipReader.getEntries(...) and getData

### ISSUE THREAD

**Issue by vitaly-tatarintsev** [gildas-lormeau/zip.js#63]
It happens, for example. in next case:

zip.createReader(new zip.BlobReader(epubfile), function (zipReader) {
        zipReader.getEntries(function (entries) {
            for (var i in entries) {
                var e = entries[i];
                files[e.filename] = e;
            }

files[id].getData(writer, ongetdata,)

```
    function ongetdata(get_data)
    {
                    var mydoc = new DOMParser().parseFromString(get_data, "text/xml");
```

Problem. get_data is xml-file beginning from space. Google-browsered version work good. But Opera version parseFromString get output-xml with "Error Unknown source". 

My proposal. Use final trim() in getData or parseFromString(get_data.trim(). trim() in getData is better, i think.

**Comment by gildas-lormeau** [comment]
I'm closing this issue as obsolete.
