### ISSUE TITLE
Abort ZipWriter.prototype.add() request

### ISSUE THREAD

**Issue by guari** [gildas-lormeau/zip.js#69]
Hi, thanks for this great library!
By reading documentation (and source code) I haven't found a way to simply abort a process started with `ZipWriter.prototype.add()`. Is there some way to do this?
If not, it would be useful to have eg. a reference returned from the `add` method to allow an `abort()` call on it.

**Comment by gildas-lormeau** [comment]
zip.js uses promises under the hood. While they help to make the code easier to maintain, the drawback is that they cannot be cancelled. So, I'm closing this issue because of this technical limitation.

**Comment by gildas-lormeau** [comment]
https://github.com/gildas-lormeau/zip.js/commit/a95625730b0c5911b657b1015cb88f12f140de32 fixes this issue
