### ISSUE TITLE
Chrome: File format is not recognized

### ISSUE THREAD

**Issue by skrat** [gildas-lormeau/zip.js#8]
It doesn't seem to recognize 0 (aka. store)  compression method in any browser, but in Chrome everything is failing. I don't want to go into base64 encoding my data before hand to employ `importData64URI` as it is unnecessary extra cycles. You could perhaps add importArrayBuffer (as in `xhr.responseType = 'arraybuffer'`). Test case here: https://docs.google.com/open?id=0B5sQ3oZM4e3yZkdab0RsOVBRdktFUjBXMzg3YU5XZw

You can change image.def.zip for image.zip in `xhr3`

**Comment by baoxiehao** [comment]
So how you solve this problem? I have also encountered this.
