### ISSUE TITLE
compressing a file of ~100MB gives incomplete zip file (chrome 31)

### ISSUE THREAD

**Issue by duanyao** [gildas-lormeau/zip.js#80]
This issue seems come back with chrome 29-31:
https://github.com/gildas-lormeau/zip.js/issues/42
https://code.google.com/p/chromium/issues/detail?id=224251

**Comment by ODelibalta** [comment]
@duanyao Awesome ... I can sleep now. It's been bugging me for days. Thank you !!!

**Comment by Rob--W** [comment]
https://crbug.com/224251 has been fixed in Chrome 42, so this issue is now obsolete.
