### ISSUE TITLE
deflate.js - status never gets set to INIT_STATE so header never gets written

### ISSUE THREAD

**Issue by jamesbrobb** [gildas-lormeau/zip.js#87]
Apologises if i'm missing something obvious. I'm attempting to use your deflate.js to compress some image data and noticed that at line 1776 there's logic (that appears) to add the zlib header. 

It gets run when 'status == INIT_STATE' but it doesn't appear that status ever gets set to INIT_STATE, so the header's never actually added. Is this intentional?

**Comment by puzrin** [comment]
If you need pure inflate/deflate/gzip - use [pako](https://github.com/nodeca/pako). It was written later than this lib, but has better implementation (speed, tests).
