### ISSUE TITLE
unzip a big file 

### ISSUE THREAD

**Issue by ghost** [gildas-lormeau/zip.js#89]
It's possible to decompress/unzip a big file (more than 100 MB) without load the whole content in memory? Decompress by parts, and save it in one file?

**Comment by sguha-work** [comment]
I'm using Zip.js for extraction archive size more that 800mb, it works fine but as my program have multiple section where user can trigger unzipping archive the extraction process getting too slow. Is there any guide to optimizee the memory and CPU used by zip.js
